// dbmolapice.h
////////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2014 PYR Software Ltd. All rights reserved.
////////////////////////////////////////////////////////////////////////////////

#ifndef dbmolapice_h_included
#define dbmolapice_h_included

///////////////////////////////////////////////////////////////////////////////
// PYR-29926 - ice 100 messages range begins with 20428 and ends with 20528
//
// ***** DO NOT EXTEND THAT RANGE BECAUSE IT WILL TRAMPLE OVER dbmolap.h *****
//
// When adding a new message - make sure you update all processing functions appear for both _Q_OLAP_ and _A_OLAP_ messages
// check any message above and implement the new one similarly
//

#define DBM_Q_OLAP_ICE_EVENT_REGISTER_IN_DUMMY_TOURN	20428
#define DBM_A_OLAP_ICE_EVENT_REGISTER_IN_DUMMY_TOURN	(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_REGISTER_IN_DUMMY_TOURN) //21428

#define DBM_Q_OLAP_ICE_EVENT_PLAY_TOURNAMENT			20429
#define DBM_A_OLAP_ICE_EVENT_PLAY_TOURNAMENT			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_PLAY_TOURNAMENT)	//21429

#define DBM_Q_OLAP_ICE_EVENT_FINISH_TOURNAMENT			20430
#define DBM_A_OLAP_ICE_EVENT_FINISH_TOURNAMENT			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_FINISH_TOURNAMENT) //21430

#define DBM_Q_OLAP_ICE_EVENT_KICKED_TOURN_PLAYER		20431
#define DBM_A_OLAP_ICE_EVENT_KICKED_TOURN_PLAYER		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_KICKED_TOURN_PLAYER) //21431

#define DBM_Q_OLAP_ICE_EVENT_TOURNAMENT_AWARD			20432
#define DBM_A_OLAP_ICE_EVENT_TOURNAMENT_AWARD			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_TOURNAMENT_AWARD) //21432

#define DBM_Q_OLAP_ICE_EVENT_RING_HAND					20433
#define DBM_A_OLAP_ICE_EVENT_RING_HAND					(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_RING_HAND) //21433

#define DBM_Q_OLAP_ICE_EVENT_QUEST_COMPLETE				20434
#define DBM_A_OLAP_ICE_EVENT_QUEST_COMPLETE				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_QUEST_COMPLETE) //21434

#define DBM_Q_OLAP_ICE_EVENT_TICKET_USED				20435
#define DBM_A_OLAP_ICE_EVENT_TICKET_USED				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_TICKET_USED) //21435

#define DBM_Q_OLAP_ICE_EVENT_VPPS_EARNED				20436
#define DBM_A_OLAP_ICE_EVENT_VPPS_EARNED				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_VPPS_EARNED) //21436

#define DBM_Q_OLAP_ICE_EVENT_RM_DEPOSIT					20437
#define DBM_A_OLAP_ICE_EVENT_RM_DEPOSIT					(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_RM_DEPOSIT) //21437

#define DBM_Q_OLAP_ICE_EVENT_NEW_USER_ACCOUNT			20438
#define DBM_A_OLAP_ICE_EVENT_NEW_USER_ACCOUNT			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_NEW_USER_ACCOUNT) //21438

#define DBM_Q_OLAP_ICE_EVENT_USER_PRIVILEGE_CHANGE		20439
#define DBM_A_OLAP_ICE_EVENT_USER_PRIVILEGE_CHANGE		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_USER_PRIVILEGE_CHANGE) //21439

#define DBM_Q_OLAP_ICE_EVENT_FPP_CHANGED				20440
#define DBM_A_OLAP_ICE_EVENT_FPP_CHANGED				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_FPP_CHANGED) //21440

#define DBM_Q_OLAP_ICE_EVENT_VIP_LEVEL_CHANGED			20441
#define DBM_A_OLAP_ICE_EVENT_VIP_LEVEL_CHANGED			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_VIP_LEVEL_CHANGED) //21441

#define DBM_Q_OLAP_ICE_EVENT_DUEL_PLAY					20442	
#define DBM_A_OLAP_ICE_EVENT_DUEL_PLAY					(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_DUEL_PLAY) //21442

#define DBM_Q_OLAP_ICE_EVENT_DUEL_HAND					20443
#define DBM_A_OLAP_ICE_EVENT_DUEL_HAND					(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_DUEL_HAND) //21443

#define DBM_Q_OLAP_ICE_EVENT_DUEL_FINISH				20444
#define DBM_A_OLAP_ICE_EVENT_DUEL_FINISH				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_DUEL_FINISH) //21444

#define DBM_Q_OLAP_ICE_EVENT_USER_ACCOUNT_CHANGED		20445
#define DBM_A_OLAP_ICE_EVENT_USER_ACCOUNT_CHANGED		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_USER_ACCOUNT_CHANGED) // 21445

#define DBM_Q_OLAP_ICE_EVENT_CASINO_GAME_ROUND			20446	// PYR-34344
#define DBM_A_OLAP_ICE_EVENT_CASINO_GAME_ROUND			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_GAME_ROUND) // 21446

#define DBM_Q_OLAP_ICE_EVENT_BONUS						20447	// PYR-35734
#define DBM_A_OLAP_ICE_EVENT_BONUS						(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_BONUS) // 21447

#define DBM_Q_OLAP_ICE_EVENT_VIP_STEP_COMPLETED			20448	// PYR-38213
#define DBM_A_OLAP_ICE_EVENT_VIP_STEP_COMPLETED			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_VIP_STEP_COMPLETED) // 21448

#define DBM_Q_OLAP_ICE_EVENT_SPORTS_BET_PACED			20449	// PYR-37407
#define DBM_A_OLAP_ICE_EVENT_SPORTS_BET_PACED			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_SPORTS_BET_PACED) // 21449

#define DBM_Q_OLAP_ICE_EVENT_SPORTS_BET_SETTLED			20450	// PYR-37407
#define DBM_A_OLAP_ICE_EVENT_SPORTS_BET_SETTLED			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_SPORTS_BET_SETTLED) // 21450

#define DBM_Q_OLAP_ICE_EVENT_FIRST_LT_POINTS			20451	// PYR-40096
#define DBM_A_OLAP_ICE_EVENT_FIRST_LT_POINTS			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_FIRST_LT_POINTS) // 21451

#define DBM_Q_OLAP_ICE_EVENT_USER_TRACK_CODE_CHANGE		20452	// PYR-31472
#define DBM_A_OLAP_ICE_EVENT_USER_TRACK_CODE_CHANGE		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_USER_TRACK_CODE_CHANGE) // 21452

#define DBM_Q_OLAP_ICE_EVENT_CASINO_BLACKJACK_HAND		20453	// PYR-34347
#define DBM_A_OLAP_ICE_EVENT_CASINO_BLACKJACK_HAND		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_BLACKJACK_HAND) // 21453

#define DBM_Q_OLAP_ICE_EVENT_CASINO_BLACKJACK_SEAT		20454	// PYR-34347
#define DBM_A_OLAP_ICE_EVENT_CASINO_BLACKJACK_SEAT		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_BLACKJACK_SEAT) // 21454

#define DBM_Q_OLAP_ICE_EVENT_MG_COMPLETED				20455	// PYR-43429
#define DBM_A_OLAP_ICE_EVENT_MG_COMPLETED				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_MG_COMPLETED) // 21455

#define DBM_Q_OLAP_ICE_EVENT_FREEMIUM_PURCHASE			20456	// PYR-39805
#define DBM_A_OLAP_ICE_EVENT_FREEMIUM_PURCHASE			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_FREEMIUM_PURCHASE) // 21456

#define DBM_Q_OLAP_ICE_EVENT_CASINO_ROULETTE_SPIN		20457	// PYR-43854
#define DBM_A_OLAP_ICE_EVENT_CASINO_ROULETTE_SPIN		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_ROULETTE_SPIN) // 21457

#define DBM_Q_OLAP_ICE_EVENT_CASINO_ROULETTE_BET		20458	// PYR-43854
#define DBM_A_OLAP_ICE_EVENT_CASINO_ROULETTE_BET		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_ROULETTE_BET) // 21458

#define DBM_Q_OLAP_ICE_EVENT_ACCOUNT_VALIDATION			20459
#define DBM_A_OLAP_ICE_EVENT_ACCOUNT_VALIDATION			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_ACCOUNT_VALIDATION) //21459

#define DBM_Q_OLAP_ICE_EVENT_CASINO_SLOT_SPIN			20460
#define DBM_A_OLAP_ICE_EVENT_CASINO_SLOT_SPIN			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_SLOT_SPIN) //21460

#define DBM_Q_OLAP_ICE_EVENT_CASINO_SLOT_BONUS_PLAY		20461
#define DBM_A_OLAP_ICE_EVENT_CASINO_SLOT_BONUS_PLAY		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_SLOT_BONUS_PLAY) //21461

#define DBM_Q_OLAP_ICE_EVENT_CPPS_EARNED				20462
#define DBM_A_OLAP_ICE_EVENT_CPPS_EARNED				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CPPS_EARNED) //21462

#define DBM_Q_OLAP_ICE_EVENT_SPPS_EARNED				20463
#define DBM_A_OLAP_ICE_EVENT_SPPS_EARNED				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_SPPS_EARNED) //21463

#define DBM_Q_OLAP_ICE_EVENT_TOURN_HAND					20464
#define DBM_A_OLAP_ICE_EVENT_TOURN_HAND					(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_TOURN_HAND) //21464

#define DBM_Q_OLAP_ICE_EVENT_USER_DEFAULT_ACCOUNT		20465
#define DBM_A_OLAP_ICE_EVENT_USER_DEFAULT_ACCOUNT		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_USER_DEFAULT_ACCOUNT) //21465

#define DBM_Q_OLAP_ICE_EVENT_MG_PRIZE_AWARDED			20466	// PYR-52970
#define DBM_A_OLAP_ICE_EVENT_MG_PRIZE_AWARDED			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_MG_PRIZE_AWARDED) // 21466

#define DBM_Q_OLAP_ICE_EVENT_CRM_OFFER_ACCEPTED			20467	// PYR-54633
#define DBM_A_OLAP_ICE_EVENT_CRM_OFFER_ACCEPTED			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CRM_OFFER_ACCEPTED) // 21467

#define DBM_Q_OLAP_ICE_EVENT_CHEST_EARN					20468	// PYR-56058
#define DBM_A_OLAP_ICE_EVENT_CHEST_EARN					(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CHEST_EARN) // 21468

#define DBM_Q_OLAP_ICE_EVENT_DREAMCATCHER_GAME_ROUND	20469	// PYR-59835
#define DBM_A_OLAP_ICE_EVENT_DREAMCATCHER_GAME_ROUND	(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_DREAMCATCHER_GAME_ROUND) // 21469

#define DBM_Q_OLAP_ICE_EVENT_PREDICTOR_TICKET_CREDITED	20470
#define DBM_A_OLAP_ICE_EVENT_PREDICTOR_TICKET_CREDITED	(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_PREDICTOR_TICKET_CREDITED) // 21470

#define DBM_Q_OLAP_ICE_EVENT_LEADERBOARD_SEASON_FINISH	20471
#define DBM_A_OLAP_ICE_EVENT_LEADERBOARD_SEASON_FINISH	(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_LEADERBOARD_SEASON_FINISH) // 21471

#define DBM_Q_OLAP_ICE_EVENT_RING_GAME_BUYIN			20472
#define DBM_A_OLAP_ICE_EVENT_RING_GAME_BUYIN			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_RING_GAME_BUYIN)	//21472

#define DBM_Q_OLAP_ICE_EVENT_CASINO_TEXAS_HOLDEM_BONUS_HAND		20473	// PYR-67812
#define DBM_A_OLAP_ICE_EVENT_CASINO_TEXAS_HOLDEM_BONUS_HAND		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_TEXAS_HOLDEM_BONUS_HAND) // 21473

#define DBM_Q_OLAP_ICE_EVENT_CASINO_TEXAS_HOLDEM_BONUS_BET		20474	// PYR-67812
#define DBM_A_OLAP_ICE_EVENT_CASINO_TEXAS_HOLDEM_BONUS_BET		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_TEXAS_HOLDEM_BONUS_BET) // 21474

#define DBM_Q_OLAP_ICE_EVENT_CASINO_BACCARAT_HAND		20475	// PYR-66738
#define DBM_A_OLAP_ICE_EVENT_CASINO_BACCARAT_HAND		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_BACCARAT_HAND) // 21475

#define DBM_Q_OLAP_ICE_EVENT_CASINO_BACCARAT_BET		20476	// PYR-66738
#define DBM_A_OLAP_ICE_EVENT_CASINO_BACCARAT_BET		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_BACCARAT_BET) // 21476

#define DBM_Q_OLAP_ICE_EVENT_RING_CASH_OUT				20477
#define DBM_A_OLAP_ICE_EVENT_RING_CASH_OUT				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_RING_CASH_OUT)	//21477

#define DBM_Q_OLAP_ICE_EVENT_TOURN_REGISTER				20478
#define DBM_A_OLAP_ICE_EVENT_TOURN_REGISTER				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_TOURN_REGISTER)	//21478

#define DBM_Q_OLAP_ICE_EVENT_TOURN_UNREGISTER			20479
#define DBM_A_OLAP_ICE_EVENT_TOURN_UNREGISTER			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_TOURN_UNREGISTER)	//21479

#define DBM_Q_OLAP_ICE_EVENT_CASINO_DRAGON_TIGER_HAND	20480	// PYR-66224
#define DBM_A_OLAP_ICE_EVENT_CASINO_DRAGON_TIGER_HAND	(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_DRAGON_TIGER_HAND) // 21480

#define DBM_Q_OLAP_ICE_EVENT_CASINO_DRAGON_TIGER_BET	20481	// PYR-66224
#define DBM_A_OLAP_ICE_EVENT_CASINO_DRAGON_TIGER_BET	(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_DRAGON_TIGER_BET) // 21481

#define DBM_Q_OLAP_ICE_EVENT_MPC_CHEST_CREDITED			20482	// PYR-56058
#define DBM_A_OLAP_ICE_EVENT_MPC_CHEST_CREDITED			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_MPC_CHEST_CREDITED) // 21482

#define DBM_Q_OLAP_ICE_EVENT_COMMUNITY_JACKPOT			20483	// PYR-82915
#define DBM_A_OLAP_ICE_EVENT_COMMUNITY_JACKPOT			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_COMMUNITY_JACKPOT) // 21483

#define DBM_Q_OLAP_ICE_EVENT_VICTORY_TRIBES_BONUS_TOURN_FINISH	20484	// PYR-82915
#define DBM_A_OLAP_ICE_EVENT_VICTORY_TRIBES_BONUS_TOURN_FINISH	(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_VICTORY_TRIBES_BONUS_TOURN_FINISH) // 21484

#define DBM_Q_OLAP_ICE_EVENT_VICTORY_TRIBES_SLOT_SPIN	20485	// PYR-82915
#define DBM_A_OLAP_ICE_EVENT_VICTORY_TRIBES_SLOT_SPIN	(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_VICTORY_TRIBES_SLOT_SPIN) // 21485

#define DBM_Q_OLAP_ICE_EVENT_CASINO_RACE_FINISH			20486	// PYR-84989
#define DBM_A_OLAP_ICE_EVENT_CASINO_RACE_FINISH			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_CASINO_RACE_FINISH) // 21486

#define DBM_Q_OLAP_ICE_EVENT_KYCDOC_APPROVED			20487	// PYR-92702
#define DBM_A_OLAP_ICE_EVENT_KYCDOC_APPROVED			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_KYCDOC_APPROVED) // 21487

#define DBM_Q_OLAP_ICE_EVENT_REWARDPOINTS				20488	// PYR-54691
#define DBM_A_OLAP_ICE_EVENT_REWARDPOINTS				(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_REWARDPOINTS) // 21488

#define DBM_Q_OLAP_ICE_EVENT_GAMEDATAANALYTICS			20489	// PYR-96173
#define DBM_A_OLAP_ICE_EVENT_GAMEDATAANALYTICS			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_GAMEDATAANALYTICS) // 21489

#define DBM_Q_OLAP_ICE_EVENT_SPORTS_BET_CASHOUT			20490	// PYR-57429
#define DBM_A_OLAP_ICE_EVENT_SPORTS_BET_CASHOUT			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_SPORTS_BET_CASHOUT) // 21490

#define DBM_Q_OLAP_ICE_EVENT_LOGIN						20491	// PYR-107193
#define DBM_A_OLAP_ICE_EVENT_LOGIN						(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_LOGIN) // 21491

#define DBM_Q_OLAP_ICE_EVENT_TWITCH_ACCOUNT_LINKED		20492	// PYR-112222
#define DBM_A_OLAP_ICE_EVENT_TWITCH_ACCOUNT_LINKED		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_TWITCH_ACCOUNT_LINKED) // 21492

#define DBM_Q_OLAP_ICE_EVENT_POKER_SIDE_BET_SETTLED		20493	// PYR-106565
#define DBM_A_OLAP_ICE_EVENT_POKER_SIDE_BET_SETTLED		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_POKER_SIDE_BET_SETTLED) // 21493

#define DBM_Q_OLAP_ICE_EVENT_PROGRESSIVEPLUS_ENTRY		20494	// PYR-125878
#define DBM_A_OLAP_ICE_EVENT_PROGRESSIVEPLUS_ENTRY		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_PROGRESSIVEPLUS_ENTRY) // 20494
							 
#define DBM_Q_OLAP_ICE_EVENT_PROGRESSIVEPLUS_FINISH		20495	// PYR-125878
#define DBM_A_OLAP_ICE_EVENT_PROGRESSIVEPLUS_FINISH		(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_PROGRESSIVEPLUS_FINISH) // 20494

#define DBM_Q_OLAP_ICE_EVENT_NEW_TICKET					20496	// PYR-124673
#define DBM_A_OLAP_ICE_EVENT_NEW_TICKET					(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_NEW_TICKET) // 21496

#define DBM_Q_OLAP_ICE_EVENT_DEAL_JACKPOT_SETTLED		20497	// PYR-124673
#define DBM_A_OLAP_ICE_EVENT_DEAL_JP_SETTLED			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_DEAL_JP_SETTLED) // 21497

//////////////////////////////////////////////////////////////////////////
// PYR-29926 - 20528 is the last message in the ICE range. new ICE messages between 20528 and whatever is above
#define DBM_Q_OLAP_ICE_EVENT_ENTER_STAR_CODE			20528
#define DBM_A_OLAP_ICE_EVENT_ENTER_STAR_CODE			(DBM_OLAP_DELTA + DBM_Q_OLAP_ICE_EVENT_ENTER_STAR_CODE) //21528

// ***** DO NOT EXTEND THAT RANGE BECAUSE IT WILL TRAMPLE OVER dbmolap.h *****
///////////////////////////////////////////////////////////////////////////////


#endif //dbmolapice_h_included
