CREATE TABLE GENERATOR64 
(
    OBJECTNAME varchar(30) PRIMARY KEY NOT NULL,
    OBJECTID bigint NOT NULL
);

CREATE TABLE USERS
(
   USERINTID int PRIMARY KEY NOT NULL,
   USERID varchar(20) NOT NULL,
   EMAIL varchar(100) NOT NULL,
   REGISTERED timestamp NOT NULL,
   FIRSTNAME varchar(100) DEFAULT '' NOT NULL,
   MIDDLENAME varchar(100) DEFAULT '' NOT NULL,
   LASTNAME varchar(100) DEFAULT '' NOT NULL,
   BIRTHDATE date,
   ADDR_1 varchar(300) DEFAULT '' NOT NULL,
   ADDR_2 varchar(80) DEFAULT '' NOT NULL,
   CITY varchar(80) DEFAULT '' NOT NULL,
   STATE varchar(20) DEFAULT '' NOT NULL,
   COUNTRY varchar(20) DEFAULT '' NOT NULL,
   ZIPCODE varchar(10) DEFAULT '' NOT NULL,
   PHONE varchar(100) DEFAULT '' NOT NULL,
   SEX varchar(1) DEFAULT 'U' NOT NULL,
   PRIVILEGES bigint DEFAULT 0 NOT NULL,
   FLAGS bigint DEFAULT 0 NOT NULL,
   COMMENTS varchar(1000) DEFAULT '' NOT NULL,
   USERENCRPWD varchar(100) DEFAULT '' NOT NULL,
   LICENSEID int DEFAULT 0 NOT NULL,
   SITEID int DEFAULT 0 NOT NULL,
   DEFAULTCUR varchar(3) DEFAULT 'USD' NOT NULL,
)
;

CREATE UNIQUE INDEX USER_USERINTID ON USERS(USERINTID)
;
CREATE UNIQUE INDEX USER_USERID ON USERS(USERID)
;
CREATE UNIQUE INDEX USER_EMAIL ON USERS(EMAIL)
;