CREATE TABLE LOGGEDIN
(
   LOGINID bigint PRIMARY KEY NOT NULL,
   USERID varchar(20) NOT NULL,
   USERINTID int DEFAULT 0 NOT NULL,
   LOGINTIME datetime NOT NULL,
   CLIENTDEVICE int DEFAULT 0 NOT NULL,
   SESSIONFLAGS int DEFAULT 0 NOT NULL,
   LOGINAUTHMETHOD int DEFAULT 0 NOT NULL,
   SITEID int DEFAULT 0 NOT NULL,
   INSTALLID varchar(30) NOT NULL,
   IPADDRESS varchar(40),
   IPPORT int NOT NULL,
   IPCOUNTRY varchar(20) DEFAULT '' NOT NULL,
   IPSTATE varchar(20) DEFAULT '' NOT NULL,
   MACADDRESS varchar(20) NOT NULL,
   ROUTERMACADDR varchar(20) DEFAULT '' NOT NULL
)
;

CREATE UNIQUE INDEX PK_LOGGEDIN ON LOGGEDIN(LOGINID)
;

