CREATE TABLE LOGGEDOUT
(
   LOGINID bigint PRIMARY KEY NOT NULL,
   USERID varchar(20) NOT NULL,
   USERINTID int DEFAULT 0 NOT NULL,
   LOGINTIME datetime NOT NULL,
   LOGOUTTIME datetime NOT NULL,
   LOGOUTTYPE int DEFAULT 0 NOT NULL,
   CLIENTDEVICE int DEFAULT 0 NOT NULL,
   SESSIONFLAGS int DEFAULT 0 NOT NULL,
   LOGINAUTHMETHOD int DEFAULT 0 NOT NULL,
   SITEID int DEFAULT 0 NOT NULL,
   INSTALLID varchar(30) NOT NULL,
   IPADDRESS varchar(40),
   IPPORT int NOT NULL,
   IPCOUNTRY varchar(20) DEFAULT '' NOT NULL,
   IPSTATE varchar(20) DEFAULT '' NOT NULL,
   MACADDRESS varchar(20) NOT NULL,
   ROUTERMACADDR varchar(20) DEFAULT '' NOT NULL
)
;
CREATE UNIQUE INDEX PK_LOGGEDOUT ON LOGGEDOUT(LOGINID)
;
CREATE INDEX LOUT_USR_OUTTIME ON LOGGEDOUT ( USERID, LOGOUTTIME )
;

