// Copyright (C) 2001-2006 PYR Software Ltd.  All rights reserved.

#ifndef commhercules_h
#define commhercules_h

#define MSG_HERCULES_FIRST /* .............. */ 0x4900

#define MSG_HERCULES_SEND_REPORT /* ........ */ 0x4901
#define MSG_HERCULES_SEND_REPORT_REPLY /* .. */ 0x4902

#define MSG_HERCULES_REPORT_START /* ....... */ 0x4903

#define MSG_HERCULES_REPORT_FILE /* ........ */ 0x4904

#define MSG_HERCULES_INIT /* ............... */ 0x4905
#define MSG_HERCULES_INIT_REPLY /* ......... */ 0x4906

#define MSG_HERCULES_REPORTED_STATIONS /* .. */ 0x4907
#define MSG_HERCULES_REPORTED_STATIONS_REPLY	0x4908

#define MSG_HERCULES_REPORTED_PARAMS /* .... */ 0x4909
#define MSG_HERCULES_REPORTED_PARAMS_REPLY      0x490A

#define MSG_HERCULES_ENABLE_EMAIL /* ....... */	0x490B
#define MSG_HERCULES_ENABLE_EMAIL_REPLY /* . */	0x490C

#define MSG_HERCULES_GET_SENT_EMAILS /* .... */ 0x490D
#define MSG_HERCULES_GET_SENT_EMAILS_REPLY		0x490E

#define TIMER_HERCULES_MSG /* .............. */ 0x490F

#define TIMER_HERCULES_SNMP_MSG /* ......... */ 0x4910

#define MSG_HERCULES_GET_FULLMAP /* ........ */ 0x4911
#define MSG_HERCULES_GET_FULLMAP_REPLY /* .. */ 0x4912

#define MSG_HERCULES_GET_ALL_LIMITS /* ..... */ 0x4913
#define MSG_HERCULES_GET_ALL_LIMITS_REPLY       0x4914

#define MSG_HERCULES_GET_LOCAL_TIME /* ..... */ 0x4915
#define MSG_HERCULES_GET_LOCAL_TIME_REPLY       0x4916
#define MSG_HERCULES_GET_LOCAL_TIME_REPLY2      0x4917

#define TIMER_HERCULES_DB_MSG /* ........... */ 0x4918

#define MSG_HERCULES_I_AM_MNGM_TUNER /* .... */ 0x4919
#define MSG_HERCULES_I_AM_MNGM_TUNER_REPLY      0x491A

#define MSG_HERCULES_GET_ALL_LOCAL_TIMES        0x491B
#define MSG_HERCULES_GET_ALL_LOCAL_TIMES_REPLY  0x491C
#define MSG_HERCULES_GET_ALL_LOCAL_TIMES_REPLY2 0x491D

#define MSG_HERCULES_CLOSE_ALL /* .......... */ 0x491E

#define MSG_HERCULES_SET_TIME /* ........... */ 0x4921
#define MSG_HERCULES_SET_TIME_REPLY /* ..... */ 0x4922

#define MSG_HERCULES_SET_SPEC_TIME /* ...... */ 0x4923
#define MSG_HERCULES_SET_SPEC_TIME_REPLY        0x4924
#define MSG_HERCULES_SET_SPEC_TIME_REPLY2       0x4925

#define TIMER_HERCULES_DB_LONG_MSG /* ...... */ 0x4926

#define	MSG_HERCULES_GET_HISTORY /* ........ */ 0x4927
#define MSG_HERCULES_GET_HISTORY_REPLY /* .. */ 0x4928

#define MSG_HERCULES_I_HAVE_LOCAL_TIME /* .. */ 0x4929
#define MSG_HERCULES_I_HAVE_LOCAL_TIME_REPLY    0x492A

#define MSG_HERCULES_GET_LIMITS /* ......... */ 0x492B
#define MSG_HERCULES_GET_LIMITS_REPLY /* ... */ 0x492C

/* Deprecated
 * #define MSG_HERCULES_GET_HIST_BY_SEC         0x492D
 * #define MSG_HERCULES_GET_HIST_BY_SEC_REPLY   0x492E
*/

#define MSG_HERCULES_GET_GROUPS /* ......... */ 0x492F
#define MSG_HERCULES_GET_GROUPS_REPLY /* ... */ 0x4930

#define MSG_HERCULES_GET_TIME_DIFFERENCE        0x4931
#define MSG_HERCULES_GET_TIME_DIFFERENCE_REPLY  0x4932
#define MSG_HERCULES_GET_TIME_DIFFERENCE_REPLY2 0x4933

#define TIMER_HERCULES_TOOL_WAITING_MSG         0x4934

#define MSG_HERCULES_GET_GROUP_INFO /* ..... */ 0x4935
#define MSG_HERCULES_GET_GROUP_INFO_REPLY		0x4936

#define MSG_HERCULES_GET_HISTORY_FOR_TIME		0x4937
#define MSG_HERCULES_GET_HISTORY_FOR_TIME_REPLY	0x4938

/* Deprecated
 * #define MSG_HERCULES_GET_HISTORY_FOR_TIME_P		0x4939
 * #define MSG_HERCULES_GET_HISTORY_FOR_TIME_P_R	0x493A
*/

#define MSG_HERCULES_GET_SERVER_TEMPLATE		0x493B
#define MSG_HERCULES_GET_SERVER_TEMPLATE_REPLY	0x493C

#define MSG_HERCULES_RELOAD_SERVER_INI			0x493D
#define MSG_HERCULES_RELOAD_SERVER_INI_REPLY	0x493E

#define MSG_HERCULES_RELOAD_SENDER_INI			0x493F
#define MSG_HERCULES_RELOAD_SENDER_INI_REPLY	0x4940

#define MSG_HERCULES_REPORT_SENDER_STATUS		0x4941
#define MSG_HERCULES_REPORT_SENDER_STATUS_REPLY	0x4942

#define MSG_HERCULES_GET_SENDER_STATUS			0x4943
#define MSG_HERCULES_GET_SENDER_STATUS_REPLY	0x4944

#define MSG_HERCULES_REPORT_SERVER_STATUS		0x4945
#define MSG_HERCULES_REPORT_SERVER_STATUS_REPLY	0x4946

#define MSG_HERCULES_GET_SERVER_STATUS			0x4947
#define MSG_HERCULES_GET_SERVER_STATUS_REPLY	0x4948

#define MSG_HERCULES_SEND_EMAIL					0x4949

#define MSG_HERCULES_SET_ALERT					0x4950
#define MSG_HERCULES_SET_ALERT_REPLY			0x4951

#define MSG_HERCULES_HTTP_REQUEST				0x4952
#define MSG_HERCULES_HTTP_REQUEST_REPLY			0x4953

#define TIMER_HERCULES_LOGGER /* ........... */ 0x4955

#define MSG_HERCULES_SET_CLIENT_FILTER			0x4956

#define MSG_HERCULES_UPDATE_CLIENT_VALUES		0x4957

#define MSG_HERCULES_ALL_PARAMETERS				0x4958
#define MSG_HERCULES_ALL_PARAMETERS_REPLY		0x4959

#define MSG_HERCULES_UPLOAD_FILTER				0x495A
#define MSG_HERCULES_UPLOAD_FILTER_REPLY		0x495B

#define MSG_HERCULES_ALL_FILTERS				0x495C
#define MSG_HERCULES_ALL_FILTERS_REPLY			0x495D

#define MSG_HERCULES_REQUEST_FILTER				0x495E
#define MSG_HERCULES_REQUEST_FILTER_REPLY		0x495F

#define MSG_HERCULES_RESET_PARAMETER			0x4960
#define MSG_HERCULES_RESET_PARAMETER_REPLY		0x4961

#define MSG_HERCULES_DELETE_FILTER				0x4962
#define MSG_HERCULES_DELETE_FILTER_REPLY		0x4963

#define MSG_HERCULES_PUBLISH					0x4964

#define MSG_HERCULES_SEND_ALERT					0x4965
#define MSG_HERCULES_SEND_ALERT_REPLY			0x4966

#define MSG_HERCULES_REPORT_LOAD_PERFORMANCE	0x4967

#define MSG_HERCULES_LAST_REPORT_INFO			0x4968
#define MSG_HERCULES_LAST_REPORT_INFO_REPLY		0x4969

#define MSG_HERCULES_DUMMY						0x4970

#define MSG_HERCULES_SET_NICK_NAME				0x4971

#define MSG_HERCULES_GET_FULLMAP_EX				0x4972
#define MSG_HERCULES_GET_FULLMAP_EX_REPLY		0x4973

#define MSG_HERCULES_REQUEST_CALCULATING		0x4974

// !!! Attention !!!
// Please use Systools repository monitor\HeCommon\heMessages.h
// to define new Hercules related messages

// Free ....................................... 0x494A

#define MSG_HERCULES_LAST /* ............... */ 0x49FF

#define HERCULES_NO_MORE_DATA	0
#define HERCULES_HAS_DATA		1
#define HERCULES_HAS_EXT_DATA	2

#define HERCULES_OBJECT_NAME			"hercules"
#define HERCULES_INSTANCE_NAME			"herculesInstance"

#define HERCULES_MNGM_OBJECT_NAME		"herculesMngm"
#define HERCULES_MNGM_INSTANCE_NAME		"herculesMngmInstance"

#define HERCULES_SND_OBJECT_NAME		"herculesSnd"
#define HERCULES_SND_INSTANCE_NAME		"herculesSndInstance"

#define HERCULES_TOOL_OBJECT_NAME		"herculesTool"
#define HERCULES_TOOL_INSTANCE_NAME		"herculesToolInstance"

#define HERCULES_SUBSCRIBTION_NAME		"HERCULESDATA"
#define HERCULES_SUBSCRIBTION2_ALL		"HERCULESDATA2ALL"
#define HERCULES_SUBSCRIBTION2_DBM		"HERCULESDATA2DBM"

#define HERCULES_MNGM_CONN_NAME			"herculesMngmConnection"
#define HERCULES_SND_CONN_NAME			"herculesSndConnection"

#define HERCULES_OK			0
#define ERR_EMPTY_STATION	1

// !!! Attention !!!
// If any new error code has to be added,
// please create a new file in protocols
// to define new Hercules error codes.

#define HERCULES_HISTORY_UP			(-2)
#define HERCULES_HISTORY_DOWN		(-1)
#define HERCULES_HISTORY_BY_SECONDS	1
#define HERCULES_HISTORY_BY_MINUTES	2
#define HERCULES_HISTORY_BY_HOURS	3
#define HERCULES_HISTORY_BY_DAYS	4

#define HERCULES_PARAMETER_BUSY				"100C#"
#define HERCULES_PARAMETER_DISK_FAILURE		"100D#"
#define HERCULES_PARAMETER_EMPTY			"-2#"
#define HERCULES_PARAMETER_ENABLED			"100B#"
#define HERCULES_PARAMETER_DISABLED			"0B#"
#define HERCULES_PARAMETER_NEED_TO_RESTART	"100E#"
#define HERCULES_PARAMETER_NORMAL			"0D#"
#define HERCULES_PARAMETER_OK				"0C#"
#define HERCULES_PARAMETER_PRESENT			"100A#"
#define HERCULES_PARAMETER_UNAVAILABLE		"-1#"

#endif	
