{ "US","US" },
{ "U S","US" },
{ "USA","US" },
{ "USA.","US" },
{ "U S A","US" },
{ "U.S.A","US" },
{ "U.S.A.","US" },
{ "U. S. A.","US" },
{ "U.S","US" },
{ "U.S.","US" },
{ "U. S.","US" },
{ "United States","US" },
{ "UK","GB" },
{ "U.K","GB" },
{ "U.K.","GB" },
{ "England","GB" },
{ "Scotland","GB" },
{ "The Netherlands","NL" }
