// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_de.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "de" collation

{"Afghanistan","AF"},
{"\304gypten","EG"},
{"\305landinseln","AX"},
{"Albanien","AL"},
{"Algerien","DZ"},
{"Amerikanische Jungferninseln","VI"},
{"Amerikanische \334berseeinseln","UM"},
{"Amerikanisch-Samoa","AS"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarktis","AQ"},
{"Antigua und Barbuda","AG"},
{"\304quatorialguinea","GQ"},
{"Argentinien","AR"},
{"Armenien","AM"},
{"Aruba","AW"},
{"Aserbaidschan","AZ"},
{"\304thiopien","ET"},
{"Australien","AU"},
{"Bahamas","BS"},
{"Bahrain","BH"},
{"Bangladesch","BD"},
{"Barbados","BB"},
{"Belarus","BY"},
{"Belgien","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermuda","BM"},
{"Bhutan","BT"},
{"Bolivien","BO"},
{"Bonaire, Sint Eustatius und Saba","BQ"},
{"Bosnien und Herzegowina","BA"},
{"Botsuana","BW"},
{"Bouvetinsel","BV"},
{"Brasilien","BR"},
{"Britische Jungferninseln","VG"},
{"Britisches Territorium im Indischen Ozean","IO"},
{"Brunei Darussalam","BN"},
{"Bulgarien","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Cabo Verde","CV"},
{"Chile","CL"},
{"China","CN"},
{"Cookinseln","CK"},
{"Costa Rica","CR"},
{"C\364te d\222Ivoire","CI"},
{"Cura\347ao","CW"},
{"D\344nemark","DK"},
{"Deutschland","DE"},
{"Dominica","DM"},
{"Dominikanische Republik","DO"},
{"Dschibuti","DJ"},
{"Ecuador","EC"},
{"El Salvador","SV"},
{"Eritrea","ER"},
{"Estland","EE"},
{"Falklandinseln","FK"},
{"F\344r\366er","FO"},
{"Fidschi","FJ"},
{"Finnland","FI"},
{"Frankreich","FR"},
{"Franz\366sische S\374d- und Antarktisgebiete","TF"},
{"Franz\366sisch-Guayana","GF"},
{"Franz\366sisch-Polynesien","PF"},
{"Gabun","GA"},
{"Gambia","GM"},
{"Georgien","GE"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Grenada","GD"},
{"Griechenland","GR"},
{"Gr\366nland","GL"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guinea","GN"},
{"Guinea-Bissau","GW"},
{"Guyana","GY"},
{"Haiti","HT"},
{"Heard und McDonaldinseln","HM"},
{"Honduras","HN"},
{"Indien","IN"},
{"Indonesien","ID"},
{"Irak","IQ"},
{"Iran","IR"},
{"Irland","IE"},
{"Island","IS"},
{"Isle of Man","IM"},
{"Israel","IL"},
{"Italien","IT"},
{"Jamaika","JM"},
{"Japan","JP"},
{"Jemen","YE"},
{"Jersey","JE"},
{"Jordanien","JO"},
{"Jugoslawien","YU"},
{"Kaimaninseln","KY"},
{"Kambodscha","KH"},
{"Kamerun","CM"},
{"Kanada","CA"},
{"Kasachstan","KZ"},
{"Katar","QA"},
{"Kenia","KE"},
{"Kirgisistan","KG"},
{"Kiribati","KI"},
{"Kokosinseln","CC"},
{"Kolumbien","CO"},
{"Komoren","KM"},
{"Kongo-Brazzaville","CG"},
{"Kongo-Kinshasa","CD"},
{"Kroatien","HR"},
{"Kuba","CU"},
{"Kuwait","KW"},
{"Laos","LA"},
{"Lesotho","LS"},
{"Lettland","LV"},
{"Libanon","LB"},
{"Liberia","LR"},
{"Libyen","LY"},
{"Liechtenstein","LI"},
{"Litauen","LT"},
{"Luxemburg","LU"},
{"Madagaskar","MG"},
{"Malawi","MW"},
{"Malaysia","MY"},
{"Malediven","MV"},
{"Mali","ML"},
{"Malta","MT"},
{"Marokko","MA"},
{"Marshallinseln","MH"},
{"Martinique","MQ"},
{"Mauretanien","MR"},
{"Mauritius","MU"},
{"Mayotte","YT"},
{"Mexiko","MX"},
{"Mikronesien","FM"},
{"Monaco","MC"},
{"Mongolei","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Mosambik","MZ"},
{"Myanmar","MM"},
{"Namibia","NA"},
{"Nauru","NR"},
{"Nepal","NP"},
{"Neukaledonien","NC"},
{"Neuseeland","NZ"},
{"Nicaragua","NI"},
{"Niederlande","NL"},
{"Niederl\344ndische Antillen","AN"},
{"Niger","NE"},
{"Nigeria","NG"},
{"Niue","NU"},
{"Nordkorea","KP"},
{"N\366rdliche Marianen","MP"},
{"Nordmazedonien","MK"},
{"Norfolkinsel","NF"},
{"Norwegen","NO"},
{"Oman","OM"},
{"\326sterreich","AT"},
{"Osttimor","TP"},
{"Pakistan","PK"},
{"Pal\344stinensische Autonomiegebiete","PS"},
{"Palau","PW"},
{"Panama","PA"},
{"Papua-Neuguinea","PG"},
{"Paraguay","PY"},
{"Peru","PE"},
{"Philippinen","PH"},
{"Pitcairninseln","PN"},
{"Polen","PL"},
{"Portugal","PT"},
{"Puerto Rico","PR"},
{"Republik Moldau","MD"},
{"R\351union","RE"},
{"Ruanda","RW"},
{"Rum\344nien","RO"},
{"Russland","RU"},
{"Salomonen","SB"},
{"Sambia","ZM"},
{"Samoa","WS"},
{"San Marino","SM"},
{"S\343o Tom\351 und Pr\355ncipe","ST"},
{"Saudi-Arabien","SA"},
{"Schweden","SE"},
{"Schweiz","CH"},
{"Senegal","SN"},
{"Serbien","RS"},
{"Seychellen","SC"},
{"Sierra Leone","SL"},
{"Simbabwe","ZW"},
{"Singapur","SG"},
{"Sint Maarten","SX"},
{"Slowakei","SK"},
{"Slowenien","SI"},
{"Somalia","SO"},
{"Sonderverwaltungsregion Hongkong","HK"},
{"Sonderverwaltungsregion Macau","MO"},
{"Spanien","ES"},
{"Spitzbergen und Jan Mayen","SJ"},
{"Sri Lanka","LK"},
{"St. Barth\351lemy","BL"},
{"St. Helena","SH"},
{"St. Kitts und Nevis","KN"},
{"St. Lucia","LC"},
{"St. Martin","MF"},
{"St. Pierre und Miquelon","PM"},
{"St. Vincent und die Grenadinen","VC"},
{"S\374dafrika","ZA"},
{"Sudan","SD"},
{"S\374dgeorgien und die S\374dlichen Sandwichinseln","GS"},
{"S\374dkorea","KR"},
{"S\374dsudan","SS"},
{"Suriname","SR"},
{"Swasiland","SZ"},
{"Syrien","SY"},
{"Tadschikistan","TJ"},
{"Taiwan","TW"},
{"Tansania","TZ"},
{"Thailand","TH"},
{"Timor-Leste","TL"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad und Tobago","TT"},
{"Tschad","TD"},
{"Tschechien","CZ"},
{"Tunesien","TN"},
{"T\374rkei","TR"},
{"Turkmenistan","TM"},
{"Turks- und Caicosinseln","TC"},
{"Tuvalu","TV"},
{"Uganda","UG"},
{"Ukraine","UA"},
{"Ungarn","HU"},
{"Uruguay","UY"},
{"Usbekistan","UZ"},
{"Vanuatu","VU"},
{"Vatikanstadt","VA"},
{"Venezuela","VE"},
{"Vereinigte Arabische Emirate","AE"},
{"Vereinigtes K\366nigreich","GB"},
{"Vereinigte Staaten","US"},
{"Vietnam","VN"},
{"Wallis und Futuna","WF"},
{"Weihnachtsinsel","CX"},
{"Westsahara","EH"},
{"Zentralafrikanische Republik","CF"},
{"Zypern","CY"}