// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_fi.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "fi" collation

{"Afganistan","AF"},
{"Ahvenanmaa","AX"},
{"Alankomaat","NL"},
{"Alankomaiden Antillit","AN"},
{"Albania","AL"},
{"Algeria","DZ"},
{"Amerikan Samoa","AS"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarktis","AQ"},
{"Antigua ja Barbuda","AG"},
{"Arabiemiirikunnat","AE"},
{"Argentiina","AR"},
{"Armenia","AM"},
{"Aruba","AW"},
{"Australia","AU"},
{"Azerbaid\236an","AZ"},
{"Bahama","BS"},
{"Bahrain","BH"},
{"Bangladesh","BD"},
{"Barbados","BB"},
{"Belgia","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermuda","BM"},
{"Bhutan","BT"},
{"Bolivia","BO"},
{"Bosnia ja Hertsegovina","BA"},
{"Botswana","BW"},
{"Bouvet\222nsaari","BV"},
{"Brasilia","BR"},
{"Brittil\344inen Intian valtameren alue","IO"},
{"Brittil\344iset Neitsytsaaret","VG"},
{"Brunei","BN"},
{"Bulgaria","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Caymansaaret","KY"},
{"Chile","CL"},
{"Cookinsaaret","CK"},
{"Costa Rica","CR"},
{"Cura\347ao","CW"},
{"Djibouti","DJ"},
{"Dominica","DM"},
{"Dominikaaninen tasavalta","DO"},
{"Ecuador","EC"},
{"Egypti","EG"},
{"El Salvador","SV"},
{"Eritrea","ER"},
{"Espanja","ES"},
{"Etel\344-Afrikka","ZA"},
{"Etel\344-Georgia ja Etel\344iset Sandwichsaaret","GS"},
{"Etel\344-Korea","KR"},
{"Etel\344-Sudan","SS"},
{"Etiopia","ET"},
{"Falklandinsaaret","FK"},
{"Fid\236i","FJ"},
{"Filippiinit","PH"},
{"F\344rsaaret","FO"},
{"Gabon","GA"},
{"Gambia","GM"},
{"Georgia","GE"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Grenada","GD"},
{"Gr\366nlanti","GL"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guinea","GN"},
{"Guinea-Bissau","GW"},
{"Guyana","GY"},
{"Haiti","HT"},
{"Heard ja McDonaldinsaaret","HM"},
{"Honduras","HN"},
{"Hongkong \226 Kiinan e.h.a.","HK"},
{"Huippuvuoret ja Jan Mayen","SJ"},
{"Indonesia","ID"},
{"Intia","IN"},
{"Irak","IQ"},
{"Iran","IR"},
{"Irlanti","IE"},
{"Islanti","IS"},
{"Iso-Britannia","GB"},
{"Israel","IL"},
{"Italia","IT"},
{"It\344-Timor","TL"},
{"It\344-Timor","TP"},
{"It\344valta","AT"},
{"Jamaika","JM"},
{"Japani","JP"},
{"Jemen","YE"},
{"Jersey","JE"},
{"Jordania","JO"},
{"Joulusaari","CX"},
{"Jugoslavia","YU"},
{"Kambod\236a","KH"},
{"Kamerun","CM"},
{"Kanada","CA"},
{"Kap Verde","CV"},
{"Karibian Alankomaat","BQ"},
{"Kazakstan","KZ"},
{"Kenia","KE"},
{"Keski-Afrikan tasavalta","CF"},
{"Kiina","CN"},
{"Kirgisia","KG"},
{"Kiribati","KI"},
{"Kolumbia","CO"},
{"Komorit","KM"},
{"Kongon demokraattinen tasavalta","CD"},
{"Kongon tasavalta","CG"},
{"Kookossaaret (Keelingsaaret)","CC"},
{"Kreikka","GR"},
{"Kroatia","HR"},
{"Kuuba","CU"},
{"Kuwait","KW"},
{"Kypros","CY"},
{"Laos","LA"},
{"Latvia","LV"},
{"Lesotho","LS"},
{"Libanon","LB"},
{"Liberia","LR"},
{"Libya","LY"},
{"Liechtenstein","LI"},
{"Liettua","LT"},
{"Luxemburg","LU"},
{"L\344nsi-Sahara","EH"},
{"Macao \226 Kiinan e.h.a.","MO"},
{"Madagaskar","MG"},
{"Malawi","MW"},
{"Malediivit","MV"},
{"Malesia","MY"},
{"Mali","ML"},
{"Malta","MT"},
{"Mansaari","IM"},
{"Marokko","MA"},
{"Marshallinsaaret","MH"},
{"Martinique","MQ"},
{"Mauritania","MR"},
{"Mauritius","MU"},
{"Mayotte","YT"},
{"Meksiko","MX"},
{"Mikronesian liittovaltio","FM"},
{"Moldova","MD"},
{"Monaco","MC"},
{"Mongolia","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Mosambik","MZ"},
{"Myanmar (Burma)","MM"},
{"Namibia","NA"},
{"Nauru","NR"},
{"Nepal","NP"},
{"Nicaragua","NI"},
{"Niger","NE"},
{"Nigeria","NG"},
{"Niue","NU"},
{"Norfolkinsaari","NF"},
{"Norja","NO"},
{"Norsunluurannikko","CI"},
{"Oman","OM"},
{"Pakistan","PK"},
{"Palau","PW"},
{"Palestiinalaisalueet","PS"},
{"Panama","PA"},
{"Papua-Uusi-Guinea","PG"},
{"Paraguay","PY"},
{"Peru","PE"},
{"Pitcairn","PN"},
{"Pohjois-Korea","KP"},
{"Pohjois-Makedonia","MK"},
{"Pohjois-Mariaanit","MP"},
{"Portugali","PT"},
{"Puerto Rico","PR"},
{"Puola","PL"},
{"P\344iv\344ntasaajan Guinea","GQ"},
{"Qatar","QA"},
{"Ranska","FR"},
{"Ranskan etel\344iset alueet","TF"},
{"Ranskan Guayana","GF"},
{"Ranskan Polynesia","PF"},
{"R\351union","RE"},
{"Romania","RO"},
{"Ruanda","RW"},
{"Ruotsi","SE"},
{"Saint-Barth\351lemy","BL"},
{"Saint Helena","SH"},
{"Saint Kitts ja Nevis","KN"},
{"Saint Lucia","LC"},
{"Saint-Martin","MF"},
{"Saint-Pierre ja Miquelon","PM"},
{"Saint Vincent ja Grenadiinit","VC"},
{"Saksa","DE"},
{"Salomonsaaret","SB"},
{"Sambia","ZM"},
{"Samoa","WS"},
{"San Marino","SM"},
{"S\343o Tom\351 ja Pr\355ncipe","ST"},
{"Saudi-Arabia","SA"},
{"Senegal","SN"},
{"Serbia","RS"},
{"Seychellit","SC"},
{"Sierra Leone","SL"},
{"Singapore","SG"},
{"Sint Maarten","SX"},
{"Slovakia","SK"},
{"Slovenia","SI"},
{"Somalia","SO"},
{"Sri Lanka","LK"},
{"Sudan","SD"},
{"Suomi","FI"},
{"Suriname","SR"},
{"Swazimaa","SZ"},
{"Sveitsi","CH"},
{"Syyria","SY"},
{"Tad\236ikistan","TJ"},
{"Taiwan","TW"},
{"Tansania","TZ"},
{"Tanska","DK"},
{"Thaimaa","TH"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad ja Tobago","TT"},
{"T\232ad","TD"},
{"T\232ekki","CZ"},
{"Tunisia","TN"},
{"Turkki","TR"},
{"Turkmenistan","TM"},
{"Turks- ja Caicossaaret","TC"},
{"Tuvalu","TV"},
{"Uganda","UG"},
{"Ukraina","UA"},
{"Unkari","HU"},
{"Uruguay","UY"},
{"Uusi-Kaledonia","NC"},
{"Uusi-Seelanti","NZ"},
{"Uzbekistan","UZ"},
{"Valko-Ven\344j\344","BY"},
{"Wallis ja Futuna","WF"},
{"Vanuatu","VU"},
{"Vatikaani","VA"},
{"Venezuela","VE"},
{"Ven\344j\344","RU"},
{"Vietnam","VN"},
{"Viro","EE"},
{"Yhdysvallat","US"},
{"Yhdysvaltain erillissaaret","UM"},
{"Yhdysvaltain Neitsytsaaret","VI"},
{"Zimbabwe","ZW"}