// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_no.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "no" collation

{"Afghanistan","AF"},
{"Albania","AL"},
{"Algerie","DZ"},
{"Amerikansk Samoa","AS"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarktis","AQ"},
{"Antigua og Barbuda","AG"},
{"Argentina","AR"},
{"Armenia","AM"},
{"Aruba","AW"},
{"Aserbajdsjan","AZ"},
{"Australia","AU"},
{"Aust-Timor","TP"},
{"Bahamas","BS"},
{"Bahrain","BH"},
{"Bangladesh","BD"},
{"Barbados","BB"},
{"Belgia","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermuda","BM"},
{"Bhutan","BT"},
{"Bolivia","BO"},
{"Bosnia-Hercegovina","BA"},
{"Botswana","BW"},
{"Bouvet\370ya","BV"},
{"Brasil","BR"},
{"Brunei","BN"},
{"Bulgaria","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Canada","CA"},
{"Cayman\370yene","KY"},
{"Chile","CL"},
{"Christmas\370ya","CX"},
{"Colombia","CO"},
{"Cook\370yene","CK"},
{"Costa Rica","CR"},
{"Cuba","CU"},
{"Cura\347ao","CW"},
{"Danmark","DK"},
{"De amerikanske jomfru\370yene","VI"},
{"De britiske jomfru\370yene","VG"},
{"De forente arabiske emirater","AE"},
{"De franske s\370rterritorier","TF"},
{"Den dominikanske republikk","DO"},
{"De nederlandske antiller","AN"},
{"Den sentralafrikanske republikk","CF"},
{"Det britiske territoriet i Indiahavet","IO"},
{"Det palestinske omr\345det","PS"},
{"Djibouti","DJ"},
{"Dominica","DM"},
{"Ecuador","EC"},
{"Egypt","EG"},
{"Ekvatorial-Guinea","GQ"},
{"Elfenbenskysten","CI"},
{"El Salvador","SV"},
{"Eritrea","ER"},
{"Estland","EE"},
{"Eswatini","SZ"},
{"Etiopia","ET"},
{"Falklands\370yene","FK"},
{"Fiji","FJ"},
{"Filippinene","PH"},
{"Finland","FI"},
{"Frankrike","FR"},
{"Fransk Guyana","GF"},
{"Fransk Polynesia","PF"},
{"F\346r\370yene","FO"},
{"Gabon","GA"},
{"Gambia","GM"},
{"Georgia","GE"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Grenada","GD"},
{"Gr\370nland","GL"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guinea","GN"},
{"Guinea-Bissau","GW"},
{"Guyana","GY"},
{"Haiti","HT"},
{"Heard- og McDonald\370yene","HM"},
{"Hellas","GR"},
{"Honduras","HN"},
{"Hongkong S.A.R. Kina","HK"},
{"Hviterussland","BY"},
{"India","IN"},
{"Indonesia","ID"},
{"Irak","IQ"},
{"Iran","IR"},
{"Irland","IE"},
{"Island","IS"},
{"Israel","IL"},
{"Italia","IT"},
{"Jamaica","JM"},
{"Japan","JP"},
{"Jemen","YE"},
{"Jersey","JE"},
{"Jordan","JO"},
{"Jugoslavia","YU"},
{"Kambodsja","KH"},
{"Kamerun","CM"},
{"Kapp Verde","CV"},
{"Karibisk Nederland","BQ"},
{"Kasakhstan","KZ"},
{"Kenya","KE"},
{"Kina","CN"},
{"Kirgisistan","KG"},
{"Kiribati","KI"},
{"Kokos\370yene","CC"},
{"Komorene","KM"},
{"Kongo-Brazzaville","CG"},
{"Kongo-Kinshasa","CD"},
{"Kroatia","HR"},
{"Kuwait","KW"},
{"Kypros","CY"},
{"Laos","LA"},
{"Latvia","LV"},
{"Lesotho","LS"},
{"Libanon","LB"},
{"Liberia","LR"},
{"Libya","LY"},
{"Liechtenstein","LI"},
{"Litauen","LT"},
{"Luxemburg","LU"},
{"Macao S.A.R. Kina","MO"},
{"Madagaskar","MG"},
{"Malawi","MW"},
{"Malaysia","MY"},
{"Maldivene","MV"},
{"Mali","ML"},
{"Malta","MT"},
{"Man","IM"},
{"Marokko","MA"},
{"Marshall\370yene","MH"},
{"Martinique","MQ"},
{"Mauritania","MR"},
{"Mauritius","MU"},
{"Mayotte","YT"},
{"Mexico","MX"},
{"Mikronesiaf\370derasjonen","FM"},
{"Moldova","MD"},
{"Monaco","MC"},
{"Mongolia","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Mosambik","MZ"},
{"Myanmar (Burma)","MM"},
{"Namibia","NA"},
{"Nauru","NR"},
{"Nederland","NL"},
{"Nepal","NP"},
{"New Zealand","NZ"},
{"Nicaragua","NI"},
{"Niger","NE"},
{"Nigeria","NG"},
{"Niue","NU"},
{"Nord-Korea","KP"},
{"Nord-Makedonia","MK"},
{"Nord-Marianene","MP"},
{"Norfolk\370ya","NF"},
{"Norge","NO"},
{"Ny-Caledonia","NC"},
{"Oman","OM"},
{"Pakistan","PK"},
{"Palau","PW"},
{"Panama","PA"},
{"Papua Ny-Guinea","PG"},
{"Paraguay","PY"},
{"Peru","PE"},
{"Pitcairn\370yene","PN"},
{"Polen","PL"},
{"Portugal","PT"},
{"Puerto Rico","PR"},
{"Qatar","QA"},
{"R\351union","RE"},
{"Romania","RO"},
{"Russland","RU"},
{"Rwanda","RW"},
{"Saint-Barth\351lemy","BL"},
{"Saint Kitts og Nevis","KN"},
{"Saint-Martin","MF"},
{"Saint-Pierre-et-Miquelon","PM"},
{"Salomon\370yene","SB"},
{"Samoa","WS"},
{"San Marino","SM"},
{"S\343o Tom\351 og Pr\355ncipe","ST"},
{"Saudi-Arabia","SA"},
{"Senegal","SN"},
{"Serbia","RS"},
{"Seychellene","SC"},
{"Sierra Leone","SL"},
{"Singapore","SG"},
{"Sint Maarten","SX"},
{"Slovakia","SK"},
{"Slovenia","SI"},
{"Somalia","SO"},
{"Spania","ES"},
{"Sri Lanka","LK"},
{"St. Helena","SH"},
{"St. Lucia","LC"},
{"St. Vincent og Grenadinene","VC"},
{"Storbritannia","GB"},
{"Sudan","SD"},
{"Surinam","SR"},
{"Svalbard og Jan Mayen","SJ"},
{"Sveits","CH"},
{"Sverige","SE"},
{"Syria","SY"},
{"S\370r-Afrika","ZA"},
{"S\370r-Georgia og S\370r-Sandwich\370yene","GS"},
{"S\370r-Korea","KR"},
{"S\370r-Sudan","SS"},
{"Tadsjikistan","TJ"},
{"Taiwan","TW"},
{"Tanzania","TZ"},
{"Thailand","TH"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad og Tobago","TT"},
{"Tsjad","TD"},
{"Tsjekkia","CZ"},
{"Tunisia","TN"},
{"Turkmenistan","TM"},
{"Turks- og Caicos\370yene","TC"},
{"Tuvalu","TV"},
{"Tyrkia","TR"},
{"Tyskland","DE"},
{"Uganda","UG"},
{"Ukraina","UA"},
{"Ungarn","HU"},
{"Uruguay","UY"},
{"USA","US"},
{"USAs ytre \370yer","UM"},
{"Usbekistan","UZ"},
{"Vanuatu","VU"},
{"Vatikanstaten","VA"},
{"Venezuela","VE"},
{"Vest-Sahara","EH"},
{"Vietnam","VN"},
{"Wallis og Futuna","WF"},
{"Zambia","ZM"},
{"Zimbabwe","ZW"},
{"\330sterrike","AT"},
{"\330st-Timor","TL"},
{"\305land","AX"}