// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_et.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "et" collation

{"Afganistan","AF"},
{"Ahvenamaa","AX"},
{"Albaania","AL"},
{"Al\236eeria","DZ"},
{"Ameerika Samoa","AS"},
{"Ameerika \334hendriigid","US"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarktika","AQ"},
{"Antigua ja Barbuda","AG"},
{"Araabia \334hendemiraadid","AE"},
{"Argentina","AR"},
{"Armeenia","AM"},
{"Aruba","AW"},
{"Aserbaid\236aan","AZ"},
{"Austraalia","AU"},
{"Austria","AT"},
{"Bahama","BS"},
{"Bahrein","BH"},
{"Bangladesh","BD"},
{"Barbados","BB"},
{"Belau","PW"},
{"Belgia","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermuda","BM"},
{"Bhutan","BT"},
{"Boliivia","BO"},
{"Bosnia ja Hertsegoviina","BA"},
{"Botswana","BW"},
{"Bouvet\222 saar","BV"},
{"Brasiilia","BR"},
{"Briti India ookeani ala","IO"},
{"Briti Neitsisaared","VG"},
{"Brunei","BN"},
{"Bulgaaria","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Colombia","CO"},
{"Cooki saared","CK"},
{"Costa Rica","CR"},
{"C\364te d\222Ivoire","CI"},
{"Cura\347ao","CW"},
{"Djibouti","DJ"},
{"Dominica","DM"},
{"Dominikaani Vabariik","DO"},
{"Ecuador","EC"},
{"Eesti","EE"},
{"Egiptus","EG"},
{"Ekvatoriaal-Guinea","GQ"},
{"El Salvador","SV"},
{"Eritrea","ER"},
{"Etioopia","ET"},
{"Falklandi saared","FK"},
{"Fid\236i","FJ"},
{"Filipiinid","PH"},
{"F\344\344ri saared","FO"},
{"Gabon","GA"},
{"Gambia","GM"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Grenada","GD"},
{"Gruusia","GE"},
{"Gr\366\366nimaa","GL"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guinea","GN"},
{"Guinea-Bissau","GW"},
{"Guyana","GY"},
{"Haiti","HT"},
{"Heardi ja McDonaldi saared","HM"},
{"Hiina","CN"},
{"Hispaania","ES"},
{"Holland","NL"},
{"Hollandi Antillid","AN"},
{"Hollandi Kariibi mere saared","BQ"},
{"Honduras","HN"},
{"Hongkongi erihalduspiirkond","HK"},
{"Horvaatia","HR"},
{"Ida-Timor","TL"},
{"Ida-Timor","TP"},
{"Iirimaa","IE"},
{"Iisrael","IL"},
{"India","IN"},
{"Indoneesia","ID"},
{"Iraak","IQ"},
{"Iraan","IR"},
{"Island","IS"},
{"Itaalia","IT"},
{"Jaapan","JP"},
{"Jamaica","JM"},
{"Jeemen","YE"},
{"Jersey","JE"},
{"Jordaania","JO"},
{"Jugoslaavia","YU"},
{"J\365ulusaar","CX"},
{"Kaimanisaared","KY"},
{"Kambod\236a","KH"},
{"Kamerun","CM"},
{"Kanada","CA"},
{"Kasahstan","KZ"},
{"Katar","QA"},
{"Keenia","KE"},
{"Kesk-Aafrika Vabariik","CF"},
{"Kiribati","KI"},
{"Komoorid","KM"},
{"Kongo DV","CD"},
{"Kongo Vabariik","CG"},
{"Kookossaared","CC"},
{"Kreeka","GR"},
{"Kuuba","CU"},
{"Kuveit","KW"},
{"K\365rg\365zstan","KG"},
{"K\374pros","CY"},
{"Laos","LA"},
{"Leedu","LT"},
{"Lesotho","LS"},
{"Libeeria","LR"},
{"Liechtenstein","LI"},
{"Liibanon","LB"},
{"Liib\374a","LY"},
{"Luksemburg","LU"},
{"L\365una-Aafrika Vabariik","ZA"},
{"L\365una-Georgia ja L\365una-Sandwichi saared","GS"},
{"L\365una-Korea","KR"},
{"L\365una-Sudaan","SS"},
{"L\344ti","LV"},
{"L\344\344ne-Sahara","EH"},
{"Macau erihalduspiirkond","MO"},
{"Madagaskar","MG"},
{"Malaisia","MY"},
{"Malawi","MW"},
{"Maldiivid","MV"},
{"Mali","ML"},
{"Malta","MT"},
{"Mani saar","IM"},
{"Maroko","MA"},
{"Marshalli Saared","MH"},
{"Martinique","MQ"},
{"Mauritaania","MR"},
{"Mauritius","MU"},
{"Mayotte","YT"},
{"Mehhiko","MX"},
{"Mikroneesia","FM"},
{"Moldova","MD"},
{"Monaco","MC"},
{"Mongoolia","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Mosambiik","MZ"},
{"Myanmar (Birma)","MM"},
{"Namiibia","NA"},
{"Nauru","NR"},
{"Nepal","NP"},
{"Nicaragua","NI"},
{"Nigeeria","NG"},
{"Niger","NE"},
{"Niue","NU"},
{"Norfolk","NF"},
{"Norra","NO"},
{"Omaan","OM"},
{"Paapua Uus-Guinea","PG"},
{"Pakistan","PK"},
{"Palestiina alad","PS"},
{"Panama","PA"},
{"Paraguay","PY"},
{"Peruu","PE"},
{"Pitcairni saared","PN"},
{"Poola","PL"},
{"Portugal","PT"},
{"Prantsuse Guajaana","GF"},
{"Prantsuse L\365unaalad","TF"},
{"Prantsuse Pol\374neesia","PF"},
{"Prantsusmaa","FR"},
{"Puerto Rico","PR"},
{"P\365hja-Korea","KP"},
{"P\365hja-Makedoonia","MK"},
{"P\365hja-Mariaanid","MP"},
{"R\351union","RE"},
{"Roheneemesaared","CV"},
{"Rootsi","SE"},
{"Rumeenia","RO"},
{"Rwanda","RW"},
{"Saalomoni Saared","SB"},
{"Saint-Barth\351lemy","BL"},
{"Saint Helena","SH"},
{"Saint Kitts ja Nevis","KN"},
{"Saint Lucia","LC"},
{"Saint-Martin","MF"},
{"Saint-Pierre ja Miquelon","PM"},
{"Saint Vincent ja Grenadiinid","VC"},
{"Saksamaa","DE"},
{"Sambia","ZM"},
{"Samoa","WS"},
{"San Marino","SM"},
{"S\343o Tom\351 ja Pr\355ncipe","ST"},
{"Saudi Araabia","SA"},
{"Sei\232ellid","SC"},
{"Senegal","SN"},
{"Serbia","RS"},
{"Sierra Leone","SL"},
{"Singapur","SG"},
{"Sint Maarten","SX"},
{"Slovakkia","SK"},
{"Sloveenia","SI"},
{"Somaalia","SO"},
{"Soome","FI"},
{"Sri Lanka","LK"},
{"Sudaan","SD"},
{"Suriname","SR"},
{"Suurbritannia","GB"},
{"Svaasimaa","SZ"},
{"Svalbard ja Jan Mayen","SJ"},
{"S\374\374ria","SY"},
{"\212veits","CH"},
{"Zimbabwe","ZW"},
{"Taani","DK"},
{"Tad\236ikistan","TJ"},
{"Tai","TH"},
{"Taiwan","TW"},
{"Tansaania","TZ"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad ja Tobago","TT"},
{"T\232aad","TD"},
{"T\232ehhi","CZ"},
{"T\232iili","CL"},
{"Tuneesia","TN"},
{"Turks ja Caicos","TC"},
{"Tuvalu","TV"},
{"T\374rgi","TR"},
{"T\374rkmenistan","TM"},
{"Uganda","UG"},
{"Ukraina","UA"},
{"Ungari","HU"},
{"Uruguay","UY"},
{"USA Neitsisaared","VI"},
{"Usbekistan","UZ"},
{"Uus-Kaledoonia","NC"},
{"Uus-Meremaa","NZ"},
{"Valgevene","BY"},
{"Wallis ja Futuna","WF"},
{"Vanuatu","VU"},
{"Vatikan","VA"},
{"Venemaa","RU"},
{"Venezuela","VE"},
{"Vietnam","VN"},
{"\334hendriikide hajasaared","UM"}