// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_sv.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "sv" collation

{"Afghanistan","AF"},
{"Albanien","AL"},
{"Algeriet","DZ"},
{"Amerikanska Jungfru\366arna","VI"},
{"Amerikanska Samoa","AS"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarktis","AQ"},
{"Antigua och Barbuda","AG"},
{"Argentina","AR"},
{"Armenien","AM"},
{"Aruba","AW"},
{"Australien","AU"},
{"Azerbajdzjan","AZ"},
{"Bahamas","BS"},
{"Bahrain","BH"},
{"Bangladesh","BD"},
{"Barbados","BB"},
{"Belgien","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermuda","BM"},
{"Bhutan","BT"},
{"Bolivia","BO"},
{"Bosnien och Hercegovina","BA"},
{"Botswana","BW"},
{"Bouvet\366n","BV"},
{"Brasilien","BR"},
{"Brittiska Jungfru\366arna","VG"},
{"Brittiska territoriet i Indiska oceanen","IO"},
{"Brunei","BN"},
{"Bulgarien","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Cayman\366arna","KY"},
{"Centralafrikanska republiken","CF"},
{"Chile","CL"},
{"Colombia","CO"},
{"Cook\366arna","CK"},
{"Costa Rica","CR"},
{"Cura\347ao","CW"},
{"Cypern","CY"},
{"Danmark","DK"},
{"Djibouti","DJ"},
{"Dominica","DM"},
{"Dominikanska republiken","DO"},
{"Ecuador","EC"},
{"Egypten","EG"},
{"Ekvatorialguinea","GQ"},
{"Elfenbenskusten","CI"},
{"El Salvador","SV"},
{"Eritrea","ER"},
{"Estland","EE"},
{"Etiopien","ET"},
{"Falklands\366arna","FK"},
{"Fiji","FJ"},
{"Filippinerna","PH"},
{"Finland","FI"},
{"Frankrike","FR"},
{"Franska Guyana","GF"},
{"Franska Polynesien","PF"},
{"Franska sydterritorierna","TF"},
{"F\344r\366arna","FO"},
{"F\366renade Arabemiraten","AE"},
{"Gabon","GA"},
{"Gambia","GM"},
{"Georgien","GE"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Grekland","GR"},
{"Grenada","GD"},
{"Gr\366nland","GL"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guinea","GN"},
{"Guinea-Bissau","GW"},
{"Guyana","GY"},
{"Haiti","HT"},
{"Heard\366n och McDonald\366arna","HM"},
{"Honduras","HN"},
{"Hongkong","HK"},
{"Indien","IN"},
{"Indonesien","ID"},
{"Irak","IQ"},
{"Iran","IR"},
{"Irland","IE"},
{"Island","IS"},
{"Isle of Man","IM"},
{"Israel","IL"},
{"Italien","IT"},
{"Jamaica","JM"},
{"Japan","JP"},
{"Jemen","YE"},
{"Jersey","JE"},
{"Jordanien","JO"},
{"Jugoslavien","YU"},
{"Jul\366n","CX"},
{"Kambodja","KH"},
{"Kamerun","CM"},
{"Kanada","CA"},
{"Kap Verde","CV"},
{"Karibiska Nederl\344nderna","BQ"},
{"Kazakstan","KZ"},
{"Kenya","KE"},
{"Kina","CN"},
{"Kirgizistan","KG"},
{"Kiribati","KI"},
{"Kokos\366arna","CC"},
{"Komorerna","KM"},
{"Kongo-Brazzaville","CG"},
{"Kongo-Kinshasa","CD"},
{"Kroatien","HR"},
{"Kuba","CU"},
{"Kuwait","KW"},
{"Laos","LA"},
{"Lesotho","LS"},
{"Lettland","LV"},
{"Libanon","LB"},
{"Liberia","LR"},
{"Libyen","LY"},
{"Liechtenstein","LI"},
{"Litauen","LT"},
{"Luxemburg","LU"},
{"Macao","MO"},
{"Madagaskar","MG"},
{"Malawi","MW"},
{"Malaysia","MY"},
{"Maldiverna","MV"},
{"Mali","ML"},
{"Malta","MT"},
{"Marocko","MA"},
{"Marshall\366arna","MH"},
{"Martinique","MQ"},
{"Mauretanien","MR"},
{"Mauritius","MU"},
{"Mayotte","YT"},
{"Mexiko","MX"},
{"Mikronesien","FM"},
{"Mo\347ambique","MZ"},
{"Moldavien","MD"},
{"Monaco","MC"},
{"Mongoliet","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Myanmar (Burma)","MM"},
{"Namibia","NA"},
{"Nauru","NR"},
{"Nederl\344nderna","NL"},
{"Nederl\344ndska Antillerna","AN"},
{"Nepal","NP"},
{"Nicaragua","NI"},
{"Niger","NE"},
{"Nigeria","NG"},
{"Niue","NU"},
{"Nordkorea","KP"},
{"Nordmakedonien","MK"},
{"Nordmarianerna","MP"},
{"Norfolk\366n","NF"},
{"Norge","NO"},
{"Nya Kaledonien","NC"},
{"Nya Zeeland","NZ"},
{"Oman","OM"},
{"Pakistan","PK"},
{"Palau","PW"},
{"Palestinska territorierna","PS"},
{"Panama","PA"},
{"Papua Nya Guinea","PG"},
{"Paraguay","PY"},
{"Peru","PE"},
{"Pitcairn\366arna","PN"},
{"Polen","PL"},
{"Portugal","PT"},
{"Puerto Rico","PR"},
{"Qatar","QA"},
{"R\351union","RE"},
{"Rum\344nien","RO"},
{"Rwanda","RW"},
{"Ryssland","RU"},
{"S:t Barth\351lemy","BL"},
{"S:t Helena","SH"},
{"S:t Kitts och Nevis","KN"},
{"S:t Lucia","LC"},
{"S:t Pierre och Miquelon","PM"},
{"S:t Vincent och Grenadinerna","VC"},
{"Saint-Martin","MF"},
{"Salomon\366arna","SB"},
{"Samoa","WS"},
{"San Marino","SM"},
{"S\343o Tom\351 och Pr\355ncipe","ST"},
{"Saudiarabien","SA"},
{"Schweiz","CH"},
{"Senegal","SN"},
{"Serbien","RS"},
{"Seychellerna","SC"},
{"Sierra Leone","SL"},
{"Singapore","SG"},
{"Sint Maarten","SX"},
{"Slovakien","SK"},
{"Slovenien","SI"},
{"Somalia","SO"},
{"Spanien","ES"},
{"Sri Lanka","LK"},
{"Storbritannien","GB"},
{"Sudan","SD"},
{"Surinam","SR"},
{"Svalbard och Jan Mayen","SJ"},
{"Swaziland","SZ"},
{"Sverige","SE"},
{"Sydafrika","ZA"},
{"Sydgeorgien och Sydsandwich\366arna","GS"},
{"Sydkorea","KR"},
{"Sydsudan","SS"},
{"Syrien","SY"},
{"Tadzjikistan","TJ"},
{"Taiwan","TW"},
{"Tanzania","TZ"},
{"Tchad","TD"},
{"Thailand","TH"},
{"Tjeckien","CZ"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad och Tobago","TT"},
{"Tunisien","TN"},
{"Turkiet","TR"},
{"Turkmenistan","TM"},
{"Turks- och Caicos\366arna","TC"},
{"Tuvalu","TV"},
{"Tyskland","DE"},
{"Uganda","UG"},
{"Ukraina","UA"},
{"Ungern","HU"},
{"Uruguay","UY"},
{"USA","US"},
{"USA:s yttre \366ar","UM"},
{"Uzbekistan","UZ"},
{"Wallis- och Futuna\366arna","WF"},
{"Vanuatu","VU"},
{"Vatikanstaten","VA"},
{"Venezuela","VE"},
{"Vietnam","VN"},
{"Vitryssland","BY"},
{"V\344stsahara","EH"},
{"Zambia","ZM"},
{"Zimbabwe","ZW"},
{"\305land","AX"},
{"\326sterrike","AT"},
{"\326sttimor","TL"},
{"\326sttimor","TP"}