// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_es.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2017-06-07T17:29:36.74-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.46
// Resource file: regions.xml - v1.39
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "es" collation

{"Afganist\341n","AF"},
{"Albania","AL"},
{"Alemania","DE"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguila","AI"},
{"Ant\341rtida","AQ"},
{"Antigua y Barbuda","AG"},
{"Antillas Neerlandesas","AN"},
{"Arabia Saud\355","SA"},
{"Argelia","DZ"},
{"Argentina","AR"},
{"Armenia","AM"},
{"Aruba","AW"},
{"Australia","AU"},
{"Austria","AT"},
{"Azerbaiy\341n","AZ"},
{"Bahamas","BS"},
{"Bahr\351in","BH"},
{"Bangladesh","BD"},
{"Barbados","BB"},
{"B\351lgica","BE"},
{"Belice","BZ"},
{"Ben\355n","BJ"},
{"Bermudas","BM"},
{"Bielorrusia","BY"},
{"Bolivia","BO"},
{"Bosnia-Herzegovina","BA"},
{"Botsuana","BW"},
{"Brasil","BR"},
{"Brun\351i","BN"},
{"Bulgaria","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"But\341n","BT"},
{"Cabo Verde","CV"},
{"Camboya","KH"},
{"Camer\372n","CM"},
{"Canad\341","CA"},
{"Caribe neerland\351s","BQ"},
{"Chad","TD"},
{"Chile","CL"},
{"China","CN"},
{"Chipre","CY"},
{"Ciudad del Vaticano","VA"},
{"Colombia","CO"},
{"Comoras","KM"},
{"Congo - Brazzaville","CG"},
{"Corea del Norte","KP"},
{"Corea del Sur","KR"},
{"Costa de Marfil","CI"},
{"Costa Rica","CR"},
{"Croacia","HR"},
{"Cuba","CU"},
{"Curazao","CW"},
{"Dinamarca","DK"},
{"Dominica","DM"},
{"Ecuador","EC"},
{"Egipto","EG"},
{"El Salvador","SV"},
{"Emiratos \301rabes Unidos","AE"},
{"Eritrea","ER"},
{"Eslovaquia","SK"},
{"Eslovenia","SI"},
{"Espa\361a","ES"},
{"Estados Unidos","US"},
{"Estonia","EE"},
{"Etiop\355a","ET"},
{"Filipinas","PH"},
{"Finlandia","FI"},
{"Fiyi","FJ"},
{"Francia","FR"},
{"Gab\363n","GA"},
{"Gambia","GM"},
{"Georgia","GE"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Granada","GD"},
{"Grecia","GR"},
{"Groenlandia","GL"},
{"Guadalupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guayana Francesa","GF"},
{"Guernsey","GG"},
{"Guinea","GN"},
{"Guinea-Bissau","GW"},
{"Guinea Ecuatorial","GQ"},
{"Guyana","GY"},
{"Hait\355","HT"},
{"Honduras","HN"},
{"Hungr\355a","HU"},
{"India","IN"},
{"Indonesia","ID"},
{"Ir\341n","IR"},
{"Iraq","IQ"},
{"Irlanda","IE"},
{"Isla Bouvet","BV"},
{"Isla Christmas","CX"},
{"Isla de Man","IM"},
{"Islandia","IS"},
{"Isla Niue","NU"},
{"Isla Norfolk","NF"},
{"Islas \305land","AX"},
{"Islas Caim\341n","KY"},
{"Islas Cocos","CC"},
{"Islas Cook","CK"},
{"Islas Feroe","FO"},
{"Islas Georgia del Sur y Sandwich del Sur","GS"},
{"Islas Heard y McDonald","HM"},
{"Islas Malvinas","FK"},
{"Islas Marianas del Norte","MP"},
{"Islas Marshall","MH"},
{"Islas menores alejadas de los Estados Unidos","UM"},
{"Islas Pitcairn","PN"},
{"Islas Salom\363n","SB"},
{"Islas Turcas y Caicos","TC"},
{"Islas V\355rgenes Brit\341nicas","VG"},
{"Islas V\355rgenes de los Estados Unidos","VI"},
{"Israel","IL"},
{"Italia","IT"},
{"Jamaica","JM"},
{"Jap\363n","JP"},
{"Jersey","JE"},
{"Jordania","JO"},
{"Kazajist\341n","KZ"},
{"Kenia","KE"},
{"Kirguist\341n","KG"},
{"Kiribati","KI"},
{"Kuwait","KW"},
{"Laos","LA"},
{"Lesoto","LS"},
{"Letonia","LV"},
{"L\355bano","LB"},
{"Liberia","LR"},
{"Libia","LY"},
{"Liechtenstein","LI"},
{"Lituania","LT"},
{"Luxemburgo","LU"},
{"Macedonia","MK"},
{"Madagascar","MG"},
{"Malasia","MY"},
{"Malaui","MW"},
{"Maldivas","MV"},
{"Mali","ML"},
{"Malta","MT"},
{"Marruecos","MA"},
{"Martinica","MQ"},
{"Mauricio","MU"},
{"Mauritania","MR"},
{"Mayotte","YT"},
{"M\351xico","MX"},
{"Micronesia","FM"},
{"Moldavia","MD"},
{"M\363naco","MC"},
{"Mongolia","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Mozambique","MZ"},
{"Myanmar [Birmania]","MM"},
{"Namibia","NA"},
{"Nauru","NR"},
{"Nepal","NP"},
{"Nicaragua","NI"},
{"N\355ger","NE"},
{"Nigeria","NG"},
{"Noruega","NO"},
{"Nueva Caledonia","NC"},
{"Nueva Zelanda","NZ"},
{"Om\341n","OM"},
{"Pa\355ses Bajos","NL"},
{"Pakist\341n","PK"},
{"Palau","PW"},
{"Panam\341","PA"},
{"Pap\372a Nueva Guinea","PG"},
{"Paraguay","PY"},
{"Per\372","PE"},
{"Polinesia Francesa","PF"},
{"Polonia","PL"},
{"Portugal","PT"},
{"Puerto Rico","PR"},
{"Qatar","QA"},
{"Regi\363n Administrativa Especial de Hong Kong de la Rep\372blica Popular China","HK"},
{"Regi\363n Administrativa Especial de Macao de la Rep\372blica Popular China","MO"},
{"Reino Unido","GB"},
{"Rep\372blica Centroafricana","CF"},
{"Rep\372blica Checa","CZ"},
{"Rep\372blica Democr\341tica del Congo","CD"},
{"Rep\372blica Dominicana","DO"},
{"Reuni\363n","RE"},
{"Ruanda","RW"},
{"Ruman\355a","RO"},
{"Rusia","RU"},
{"S\341hara Occidental","EH"},
{"Samoa","WS"},
{"Samoa Americana","AS"},
{"San Bartolom\351","BL"},
{"San Crist\363bal y Nieves","KN"},
{"San Marino","SM"},
{"San Mart\355n","MF"},
{"San Pedro y Miquel\363n","PM"},
{"Santa Elena","SH"},
{"Santa Luc\355a","LC"},
{"Santo Tom\351 y Pr\355ncipe","ST"},
{"San Vicente y las Granadinas","VC"},
{"Senegal","SN"},
{"Serbia","RS"},
{"Seychelles","SC"},
{"Sierra Leona","SL"},
{"Singapur","SG"},
{"Sint Maarten","SX"},
{"Siria","SY"},
{"Somalia","SO"},
{"Sri Lanka","LK"},
{"Suazilandia","SZ"},
{"Sud\341frica","ZA"},
{"Sud\341n","SD"},
{"Sud\341n del Sur","SS"},
{"Suecia","SE"},
{"Suiza","CH"},
{"Surinam","SR"},
{"Svalbard y Jan Mayen","SJ"},
{"Tailandia","TH"},
{"Taiw\341n","TW"},
{"Tanzania","TZ"},
{"Tayikist\341n","TJ"},
{"Territorio Brit\341nico del Oc\351ano \315ndico","IO"},
{"Territorios Australes Franceses","TF"},
{"Territorios Palestinos","PS"},
{"Timor Oriental","TL"},
{"Timor Oriental","TP"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad y Tobago","TT"},
{"T\372nez","TN"},
{"Turkmenist\341n","TM"},
{"Turqu\355a","TR"},
{"Tuvalu","TV"},
{"Ucrania","UA"},
{"Uganda","UG"},
{"Uruguay","UY"},
{"Uzbekist\341n","UZ"},
{"Vanuatu","VU"},
{"Venezuela","VE"},
{"Vietnam","VN"},
{"Wallis y Futuna","WF"},
{"Yemen","YE"},
{"Yibuti","DJ"},
{"Yugoslavia","YU"},
{"Zambia","ZM"},
{"Zimbabue","ZW"}