// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_fr.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2017-06-07T17:29:36.74-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.46
// Resource file: regions.xml - v1.39
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "fr" collation

{"Afghanistan","AF"},
{"Afrique du Sud","ZA"},
{"\305land, \316les","AX"},
{"Albanie","AL"},
{"Alg\351rie","DZ"},
{"Allemagne","DE"},
{"Andorre","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarctique","AQ"},
{"Antigua-et-Barbuda","AG"},
{"Antilles n\351erlandaises","AN"},
{"Arabie saoudite","SA"},
{"Argentine","AR"},
{"Arm\351nie","AM"},
{"Aruba","AW"},
{"Australie","AU"},
{"Autriche","AT"},
{"Azerba\357djan","AZ"},
{"Bahamas","BS"},
{"Bahre\357n","BH"},
{"Bangladesh","BD"},
{"Barbade","BB"},
{"B\351larus","BY"},
{"Belgique","BE"},
{"Belize","BZ"},
{"B\351nin","BJ"},
{"Bermudes","BM"},
{"Bhoutan","BT"},
{"Bolivie","BO"},
{"Bonaire, Saint-Eustache et Saba","BQ"},
{"Bosnie-Herz\351govine","BA"},
{"Botswana","BW"},
{"Br\351sil","BR"},
{"Brun\351i Darussalam","BN"},
{"Bulgarie","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Cambodge","KH"},
{"Cameroun","CM"},
{"Canada","CA"},
{"Cap-Vert","CV"},
{"Centrafricaine, R\351publique","CF"},
{"Chili","CL"},
{"Chine","CN"},
{"Christmas, \316le","CX"},
{"Chypre","CY"},
{"Cocos (Keeling), \316les","CC"},
{"Colombie","CO"},
{"Comores","KM"},
{"Congo","CG"},
{"Congo, R\351publique D\351mocratique du","CD"},
{"Cook, \316les","CK"},
{"Cor\351e du Nord","KP"},
{"Cor\351e du Sud","KR"},
{"Costa Rica","CR"},
{"C\364te d\222Ivoire","CI"},
{"Croatie","HR"},
{"Cuba","CU"},
{"Cura\347ao","CW"},
{"Danemark","DK"},
{"Djibouti","DJ"},
{"Dominicaine, R\351publique","DO"},
{"Dominique","DM"},
{"\311gypte","EG"},
{"El Salvador","SV"},
{"\311mirats arabes unis","AE"},
{"\311quateur","EC"},
{"\311rythr\351e","ER"},
{"Espagne","ES"},
{"Estonie","EE"},
{"\311tats-Unis","US"},
{"\311thiopie","ET"},
{"Falkland, \316les (Malvinas)","FK"},
{"F\351ro\351, \316les","FO"},
{"Fidji","FJ"},
{"Finlande","FI"},
{"France","FR"},
{"Gabon","GA"},
{"Gambie","GM"},
{"G\351orgie","GE"},
{"G\351orgie du Sud-et-les \316les Sandwich du Sud","GS"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Gr\350ce","GR"},
{"Grenade","GD"},
{"Groenland","GL"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernesey","GG"},
{"Guin\351e","GN"},
{"Guin\351e-Bissau","GW"},
{"Guin\351e \311quatoriale","GQ"},
{"Guyana","GY"},
{"Guyane fran\347aise","GF"},
{"Ha\357ti","HT"},
{"Heard-et-\356les Macdonald, \316le","HM"},
{"Honduras","HN"},
{"Hongrie","HU"},
{"\316le Bouvet","BV"},
{"\316le de Man","IM"},
{"\316les Ca\357mans","KY"},
{"\316les Mineures \311loign\351es des \311tats-Unis","UM"},
{"\316les Vierges britanniques","VG"},
{"\316les Vierges des \311tats-Unis","VI"},
{"Inde","IN"},
{"Indon\351sie","ID"},
{"Irak","IQ"},
{"Iran","IR"},
{"Irlande","IE"},
{"Islande","IS"},
{"Isra\353l","IL"},
{"Italie","IT"},
{"Jama\357que","JM"},
{"Japon","JP"},
{"Jersey","JE"},
{"Jordanie","JO"},
{"Kazakhstan","KZ"},
{"Kenya","KE"},
{"Kirghizistan","KG"},
{"Kiribati","KI"},
{"Kowe\357t","KW"},
{"Laos","LA"},
{"Lesotho","LS"},
{"Lettonie","LV"},
{"Liban","LB"},
{"Lib\351ria","LR"},
{"Libye","LY"},
{"Liechtenstein","LI"},
{"Lituanie","LT"},
{"Luxembourg","LU"},
{"Mac\351doine","MK"},
{"Madagascar","MG"},
{"Malaisie","MY"},
{"Malawi","MW"},
{"Maldives","MV"},
{"Mali","ML"},
{"Malte","MT"},
{"Mariannes Du Nord, \316les","MP"},
{"Maroc","MA"},
{"Marshall, \316les","MH"},
{"Martinique","MQ"},
{"Maurice","MU"},
{"Mauritanie","MR"},
{"Mayotte","YT"},
{"Mexique","MX"},
{"Micron\351sie, \311tats F\351d\351r\351s de","FM"},
{"Moldavie","MD"},
{"Monaco","MC"},
{"Mongolie","MN"},
{"Mont\351n\351gro","ME"},
{"Montserrat","MS"},
{"Mozambique","MZ"},
{"Myanmar","MM"},
{"Namibie","NA"},
{"Nauru","NR"},
{"N\351pal","NP"},
{"Nicaragua","NI"},
{"Niger","NE"},
{"Nig\351ria","NG"},
{"Niue","NU"},
{"Norfolk, \316le","NF"},
{"Norv\350ge","NO"},
{"Nouvelle-Cal\351donie","NC"},
{"Nouvelle-Z\351lande","NZ"},
{"Oman","OM"},
{"Ouganda","UG"},
{"Ouzb\351kistan","UZ"},
{"Pakistan","PK"},
{"Palaos","PW"},
{"Panama","PA"},
{"Papouasie-Nouvelle-Guin\351e","PG"},
{"Paraguay","PY"},
{"Pays-Bas","NL"},
{"P\351rou","PE"},
{"Philippines","PH"},
{"Pitcairn","PN"},
{"Pologne","PL"},
{"Polyn\351sie fran\347aise","PF"},
{"Porto Rico","PR"},
{"Portugal","PT"},
{"Qatar","QA"},
{"R.A.S. chinoise de Hong Kong","HK"},
{"R.A.S. chinoise de Macao","MO"},
{"R\351union","RE"},
{"Roumanie","RO"},
{"Royaume-Uni","GB"},
{"Russie","RU"},
{"Rwanda","RW"},
{"Sahara Occidental","EH"},
{"Saint-Barth\351l\351my","BL"},
{"Sainte-H\351l\350ne","SH"},
{"Sainte-Lucie","LC"},
{"Saint-Kitts-et-Nevis","KN"},
{"Saint-Marin","SM"},
{"Saint-Martin (Partie Fran\347aise)","MF"},
{"Saint-Martin (Partie N\351erlandaise)","SX"},
{"Saint-Pierre-et-Miquelon","PM"},
{"Saint-Si\350ge (\311tat de la Cit\351 du Vatican)","VA"},
{"Saint-Vincent-et-les Grenadines","VC"},
{"Salomon, \316les","SB"},
{"Samoa","WS"},
{"Samoa am\351ricaines","AS"},
{"Sao Tom\351-et-Principe","ST"},
{"S\351n\351gal","SN"},
{"Serbie","RS"},
{"Seychelles","SC"},
{"Sierra Leone","SL"},
{"Singapour","SG"},
{"Slovaquie","SK"},
{"Slov\351nie","SI"},
{"Somalie","SO"},
{"Soudan","SD"},
{"Soudan du Sud","SS"},
{"Sri Lanka","LK"},
{"Su\350de","SE"},
{"Suisse","CH"},
{"Suriname","SR"},
{"Svalbard et \316le Jan Mayen","SJ"},
{"Swaziland","SZ"},
{"Syrie","SY"},
{"Tadjikistan","TJ"},
{"Ta\357wan","TW"},
{"Tanzanie","TZ"},
{"Tchad","TD"},
{"Tch\350que, R\351publique","CZ"},
{"Terres Australes Fran\347aises","TF"},
{"Territoire britannique de l'oc\351an Indien","IO"},
{"Territoire palestinien","PS"},
{"Tha\357lande","TH"},
{"Timor oriental","TL"},
{"Timor oriental","TP"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinit\351-et-Tobago","TT"},
{"Tunisie","TN"},
{"Turkm\351nistan","TM"},
{"Turks-et-Ca\357cos, \316les","TC"},
{"Turquie","TR"},
{"Tuvalu","TV"},
{"Ukraine","UA"},
{"Uruguay","UY"},
{"Vanuatu","VU"},
{"Venezuela","VE"},
{"Vi\352t Nam","VN"},
{"Wallis-et-Futuna","WF"},
{"Y\351men","YE"},
{"Yougoslavie","YU"},
{"Zambie","ZM"},
{"Zimbabwe","ZW"}