// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_hu.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "hu" collation

{"Afganiszt\341n","AF"},
{"\305land-szigetek","AX"},
{"Alb\341nia","AL"},
{"Alg\351ria","DZ"},
{"Amerikai Szamoa","AS"},
{"Amerikai Virgin-szigetek","VI"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarktisz","AQ"},
{"Antigua \351s Barbuda","AG"},
{"Argent\355na","AR"},
{"Aruba","AW"},
{"Ausztr\341lia","AU"},
{"Ausztria","AT"},
{"Azerbajdzs\341n","AZ"},
{"Az USA lakatlan k\374lbirtokai","UM"},
{"Bahama-szigetek","BS"},
{"Bahrein","BH"},
{"Banglades","BD"},
{"Barbados","BB"},
{"Belarusz","BY"},
{"Belgium","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermuda","BM"},
{"Bhut\341n","BT"},
{"Bissau-Guinea","GW"},
{"Bol\355via","BO"},
{"Bosznia-Hercegovina","BA"},
{"Botswana","BW"},
{"Bouvet-sziget","BV"},
{"Braz\355lia","BR"},
{"Brit Indiai-\363ce\341ni Ter\374let","IO"},
{"Brit Virgin-szigetek","VG"},
{"Brunei","BN"},
{"Bulg\341ria","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Chile","CL"},
{"Ciprus","CY"},
{"Comore-szigetek","KM"},
{"Cook-szigetek","CK"},
{"Costa Rica","CR"},
{"Cura\347ao","CW"},
{"Cs\341d","TD"},
{"Csehorsz\341g","CZ"},
{"D\341nia","DK"},
{"D\351l-afrikai K\366zt\341rsas\341g","ZA"},
{"D\351li-Georgia \351s D\351li-Sandwich-szigetek","GS"},
{"D\351l-Korea","KR"},
{"D\351l-Szud\341n","SS"},
{"Dominika","DM"},
{"Dominikai K\366zt\341rsas\341g","DO"},
{"Dzsibuti","DJ"},
{"Ecuador","EC"},
{"\020\105\147\171\145\156\154\303\255\164\305\221\151\55\107\165\151\156\145\141","GQ"},
{"Egyes\374lt \301llamok","US"},
{"Egyes\374lt Arab Em\355rs\351gek","AE"},
{"Egyes\374lt Kir\341lys\341g","GB"},
{"Egyiptom","EG"},
{"Elef\341ntcsontpart","CI"},
{"Eritrea","ER"},
{"\311szaki Mariana-szigetek","MP"},
{"\311szak-Korea","KP"},
{"\311szak-Maced\363nia","MK"},
{"\311sztorsz\341g","EE"},
{"Eti\363pia","ET"},
{"Falkland-szigetek","FK"},
{"Fer\366er szigetek","FO"},
{"Fidzsi","FJ"},
{"Finnorsz\341g","FI"},
{"Francia D\351li Ter\374letek","TF"},
{"Francia Guyana","GF"},
{"Franciaorsz\341g","FR"},
{"Francia Polin\351zia","PF"},
{"F\374l\366p-szigetek","PH"},
{"Gabon","GA"},
{"Gambia","GM"},
{"Gh\341na","GH"},
{"Gibralt\341r","GI"},
{"G\366r\366gorsz\341g","GR"},
{"Grenada","GD"},
{"Gr\366nland","GL"},
{"Gr\372zia","GE"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guinea","GN"},
{"Guyana","GY"},
{"Haiti","HT"},
{"Heard-sziget \351s McDonald-szigetek","HM"},
{"Holland Antill\341k","AN"},
{"Hollandia","NL"},
{"Holland Karib-t\351rs\351g","BQ"},
{"Honduras","HN"},
{"Hongkong KKT","HK"},
{"Horv\341torsz\341g","HR"},
{"India","IN"},
{"Indon\351zia","ID"},
{"Irak","IQ"},
{"Ir\341n","IR"},
{"\315rorsz\341g","IE"},
{"Izland","IS"},
{"Izrael","IL"},
{"Jamaica","JM"},
{"Jap\341n","JP"},
{"Jemen","YE"},
{"Jersey","JE"},
{"Jord\341nia","JO"},
{"Jugoszl\341via","YU"},
{"Kajm\341n-szigetek","KY"},
{"Kambodzsa","KH"},
{"Kamerun","CM"},
{"Kanada","CA"},
{"Kar\341csony-sziget","CX"},
{"Katar","QA"},
{"Kazahszt\341n","KZ"},
{"Kelet-Timor","TL"},
{"Kelet-Timor","TP"},
{"Kenya","KE"},
{"K\355na","CN"},
{"Kirgiziszt\341n","KG"},
{"Kiribati","KI"},
{"K\363kusz (Keeling)-szigetek","CC"},
{"Kolumbia","CO"},
{"Kong\363 - Brazzaville","CG"},
{"Kong\363 - Kinshasa","CD"},
{"K\366z\351p-afrikai K\366zt\341rsas\341g","CF"},
{"Kuba","CU"},
{"Kuvait","KW"},
{"Laosz","LA"},
{"Lengyelorsz\341g","PL"},
{"Lesotho","LS"},
{"Lettorsz\341g","LV"},
{"Libanon","LB"},
{"Lib\351ria","LR"},
{"L\355bia","LY"},
{"Liechtenstein","LI"},
{"Litv\341nia","LT"},
{"Luxemburg","LU"},
{"Madagaszk\341r","MG"},
{"Magyarorsz\341g","HU"},
{"Maka\363 KKT","MO"},
{"Malajzia","MY"},
{"Malawi","MW"},
{"Mald\355v-szigetek","MV"},
{"Mali","ML"},
{"M\341lta","MT"},
{"Man-sziget","IM"},
{"Marokk\363","MA"},
{"Marshall-szigetek","MH"},
{"Martinique","MQ"},
{"Maurit\341nia","MR"},
{"Mauritius","MU"},
{"Mayotte","YT"},
{"Mexik\363","MX"},
{"Mianmar (Burma)","MM"},
{"Mikron\351zia","FM"},
{"Moldova","MD"},
{"Monaco","MC"},
{"Mong\363lia","MN"},
{"Montenegr\363","ME"},
{"Montserrat","MS"},
{"Mozambik","MZ"},
{"Nam\355bia","NA"},
{"Nauru","NR"},
{"N\351metorsz\341g","DE"},
{"Nep\341l","NP"},
{"Nicaragua","NI"},
{"Niger","NE"},
{"Nig\351ria","NG"},
{"Niue","NU"},
{"Norfolk-sziget","NF"},
{"Norv\351gia","NO"},
{"Nyugat-Szahara","EH"},
{"Olaszorsz\341g","IT"},
{"Om\341n","OM"},
{"Oroszorsz\341g","RU"},
{"\326rm\351nyorsz\341g","AM"},
{"Pakiszt\341n","PK"},
{"Palau","PW"},
{"Palesztin Ter\374let","PS"},
{"Panama","PA"},
{"P\341pua \332j-Guinea","PG"},
{"Paraguay","PY"},
{"Peru","PE"},
{"Pitcairn-szigetek","PN"},
{"Portug\341lia","PT"},
{"Puerto Rico","PR"},
{"R\351union","RE"},
{"Rom\341nia","RO"},
{"Ruanda","RW"},
{"Saint-Barth\351lemy","BL"},
{"Saint Kitts \351s Nevis","KN"},
{"Saint Lucia","LC"},
{"Saint Martin","MF"},
{"Saint-Pierre \351s Miquelon","PM"},
{"Saint Vincent \351s a Grenadine-szigetek","VC"},
{"Salamon-szigetek","SB"},
{"Salvador","SV"},
{"San Marino","SM"},
{"S\343o Tom\351 \351s Pr\355ncipe","ST"},
{"Seychelle-szigetek","SC"},
{"Sierra Leone","SL"},
{"Sint Maarten","SX"},
{"Spanyolorsz\341g","ES"},
{"Sr\355 Lanka","LK"},
{"Suriname","SR"},
{"Sv\341jc","CH"},
{"Svalbard \351s Jan Mayen","SJ"},
{"Sv\351dorsz\341g","SE"},
{"Szamoa","WS"},
{"Sza\372d-Ar\341bia","SA"},
{"Szeneg\341l","SN"},
{"Szent Ilona","SH"},
{"Szerbia","RS"},
{"Szingap\372r","SG"},
{"Sz\355ria","SY"},
{"Szlov\341kia","SK"},
{"Szlov\351nia","SI"},
{"Szom\341lia","SO"},
{"Szud\341n","SD"},
{"Szv\341zif\366ld","SZ"},
{"T\341dzsikiszt\341n","TJ"},
{"Tajvan","TW"},
{"Tanz\341nia","TZ"},
{"Thaif\366ld","TH"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"T\366r\366korsz\341g","TR"},
{"Trinidad \351s Tobago","TT"},
{"Tun\351zia","TN"},
{"Turks- \351s Caicos-szigetek","TC"},
{"Tuvalu","TV"},
{"T\374rkmeniszt\341n","TM"},
{"Uganda","UG"},
{"\332j-Kaled\363nia","NC"},
{"\332j-Z\351land","NZ"},
{"Ukrajna","UA"},
{"Uruguay","UY"},
{"\334zbegiszt\341n","UZ"},
{"Vanuatu","VU"},
{"Vatik\341n","VA"},
{"Venezuela","VE"},
{"Vietn\341m","VN"},
{"Wallis \351s Futuna","WF"},
{"Zambia","ZM"},
{"Zimbabwe","ZW"},
{"Z\366ld-foki K\366zt\341rsas\341g","CV"}