// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_da.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "da" collation

{"Afghanistan","AF"},
{"Albanien","AL"},
{"Algeriet","DZ"},
{"Amerikanske overs\370iske \370er","UM"},
{"Amerikansk Samoa","AS"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarktis","AQ"},
{"Antigua og Barbuda","AG"},
{"Argentina","AR"},
{"Armenien","AM"},
{"Aruba","AW"},
{"Aserbajdsjan","AZ"},
{"Australien","AU"},
{"Bahamas","BS"},
{"Bahrain","BH"},
{"Bangladesh","BD"},
{"Barbados","BB"},
{"Belgien","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermuda","BM"},
{"Bhutan","BT"},
{"Bolivia","BO"},
{"Bosnien-Hercegovina","BA"},
{"Botswana","BW"},
{"Bouvet\370en","BV"},
{"Brasilien","BR"},
{"Brunei","BN"},
{"Bulgarien","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Cambodja","KH"},
{"Cameroun","CM"},
{"Canada","CA"},
{"Cayman\370erne","KY"},
{"Chile","CL"},
{"Cocos\370erne","CC"},
{"Colombia","CO"},
{"Comorerne","KM"},
{"Congo-Brazzaville","CG"},
{"Congo-Kinshasa","CD"},
{"Cook\370erne","CK"},
{"Costa Rica","CR"},
{"Cuba","CU"},
{"Cura\347ao","CW"},
{"Cypern","CY"},
{"Danmark","DK"},
{"De Amerikanske Jomfru\370er","VI"},
{"De Britiske Jomfru\370er","VG"},
{"De Forenede Arabiske Emirater","AE"},
{"De Franske Besiddelser i Det Sydlige Indiske Ocean","TF"},
{"Den Centralafrikanske Republik","CF"},
{"Den Dominikanske Republik","DO"},
{"De pal\346stinensiske omr\345der","PS"},
{"Det britiske territorium i Det Indiske Ocean","IO"},
{"De tidligere Nederlandske Antiller","BQ"},
{"Djibouti","DJ"},
{"Dominica","DM"},
{"Ecuador","EC"},
{"Egypten","EG"},
{"Elfenbenskysten","CI"},
{"El Salvador","SV"},
{"Eritrea","ER"},
{"Estland","EE"},
{"Eswatini","SZ"},
{"Etiopien","ET"},
{"Falklands\370erne","FK"},
{"Fiji","FJ"},
{"Filippinerne","PH"},
{"Finland","FI"},
{"Frankrig","FR"},
{"Fransk Guyana","GF"},
{"Fransk Polynesien","PF"},
{"F\346r\370erne","FO"},
{"Gabon","GA"},
{"Gambia","GM"},
{"Georgien","GE"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Grenada","GD"},
{"Gr\346kenland","GR"},
{"Gr\370nland","GL"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guinea","GN"},
{"Guinea-Bissau","GW"},
{"Guyana","GY"},
{"Haiti","HT"},
{"Heard Island og McDonald Islands","HM"},
{"Holland","NL"},
{"Hollandske Antiller","AN"},
{"Honduras","HN"},
{"Hviderusland","BY"},
{"Indien","IN"},
{"Indonesien","ID"},
{"Irak","IQ"},
{"Iran","IR"},
{"Irland","IE"},
{"Island","IS"},
{"Isle of Man","IM"},
{"Israel","IL"},
{"Italien","IT"},
{"Jamaica","JM"},
{"Japan","JP"},
{"Jersey","JE"},
{"Jordan","JO"},
{"Jugoslavien","YU"},
{"Jule\370en","CX"},
{"Kap Verde","CV"},
{"Kasakhstan","KZ"},
{"Kenya","KE"},
{"Kina","CN"},
{"Kirgisistan","KG"},
{"Kiribati","KI"},
{"Kroatien","HR"},
{"Kuwait","KW"},
{"Laos","LA"},
{"Lesotho","LS"},
{"Letland","LV"},
{"Libanon","LB"},
{"Liberia","LR"},
{"Libyen","LY"},
{"Liechtenstein","LI"},
{"Litauen","LT"},
{"Luxembourg","LU"},
{"Madagaskar","MG"},
{"Malawi","MW"},
{"Malaysia","MY"},
{"Maldiverne","MV"},
{"Mali","ML"},
{"Malta","MT"},
{"Marokko","MA"},
{"Marshall\370erne","MH"},
{"Martinique","MQ"},
{"Mauretanien","MR"},
{"Mauritius","MU"},
{"Mayotte","YT"},
{"Mexico","MX"},
{"Mikronesien","FM"},
{"Moldova","MD"},
{"Monaco","MC"},
{"Mongoliet","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Mozambique","MZ"},
{"Myanmar (Burma)","MM"},
{"Namibia","NA"},
{"Nauru","NR"},
{"Nepal","NP"},
{"New Zealand","NZ"},
{"Nicaragua","NI"},
{"Niger","NE"},
{"Nigeria","NG"},
{"Niue","NU"},
{"Nordkorea","KP"},
{"Nordmakedonien","MK"},
{"Nordmarianerne","MP"},
{"Norfolk Island","NF"},
{"Norge","NO"},
{"Ny Kaledonien","NC"},
{"Oman","OM"},
{"Pakistan","PK"},
{"Palau","PW"},
{"Panama","PA"},
{"Papua Ny Guinea","PG"},
{"Paraguay","PY"},
{"Peru","PE"},
{"Pitcairn","PN"},
{"Polen","PL"},
{"Portugal","PT"},
{"Puerto Rico","PR"},
{"Qatar","QA"},
{"R\351union","RE"},
{"Rum\346nien","RO"},
{"Rusland","RU"},
{"Rwanda","RW"},
{"Saint Barth\351lemy","BL"},
{"Saint Kitts og Nevis","KN"},
{"Saint Lucia","LC"},
{"Saint Martin","MF"},
{"Saint Pierre og Miquelon","PM"},
{"Saint Vincent og Grenadinerne","VC"},
{"Salomon\370erne","SB"},
{"Samoa","WS"},
{"San Marino","SM"},
{"S\343o Tom\351 og Pr\355ncipe","ST"},
{"SAR Hongkong","HK"},
{"SAR Macao","MO"},
{"Saudi-Arabien","SA"},
{"Schweiz","CH"},
{"Senegal","SN"},
{"Serbien","RS"},
{"Seychellerne","SC"},
{"Sierra Leone","SL"},
{"Singapore","SG"},
{"Sint Maarten","SX"},
{"Slovakiet","SK"},
{"Slovenien","SI"},
{"Somalia","SO"},
{"South Georgia og De Sydlige Sandwich\370er","GS"},
{"Spanien","ES"},
{"Sri Lanka","LK"},
{"St. Helena","SH"},
{"Storbritannien","GB"},
{"Sudan","SD"},
{"Surinam","SR"},
{"Svalbard og Jan Mayen","SJ"},
{"Sverige","SE"},
{"Sydafrika","ZA"},
{"Sydkorea","KR"},
{"Sydsudan","SS"},
{"Syrien","SY"},
{"Tadsjikistan","TJ"},
{"Taiwan","TW"},
{"Tanzania","TZ"},
{"Tchad","TD"},
{"Thailand","TH"},
{"Timor-Leste","TL"},
{"Timor-Leste","TP"},
{"Tjekkiet","CZ"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad og Tobago","TT"},
{"Tunesien","TN"},
{"Turkmenistan","TM"},
{"Turks- og Caicos\370erne","TC"},
{"Tuvalu","TV"},
{"Tyrkiet","TR"},
{"Tyskland","DE"},
{"Uganda","UG"},
{"Ukraine","UA"},
{"Ungarn","HU"},
{"Uruguay","UY"},
{"USA","US"},
{"Usbekistan","UZ"},
{"Vanuatu","VU"},
{"Vatikanstaten","VA"},
{"Venezuela","VE"},
{"Vestsahara","EH"},
{"Vietnam","VN"},
{"Wallis og Futuna","WF"},
{"Yemen","YE"},
{"Zambia","ZM"},
{"Zimbabwe","ZW"},
{"\306kvatorialguinea","GQ"},
{"\330strig","AT"},
{"\305land","AX"}