// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_friendly_name.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "en" collation

{"Afghanistan","AF"},
{"Aland Islands","AX"},
{"Albania","AL"},
{"Algeria","DZ"},
{"American Samoa","AS"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarctica","AQ"},
{"Antigua and Barbuda","AG"},
{"Argentina","AR"},
{"Armenia","AM"},
{"Aruba","AW"},
{"Australia","AU"},
{"Austria","AT"},
{"Azerbaijan","AZ"},
{"Bahamas","BS"},
{"Bahrain","BH"},
{"Bangladesh","BD"},
{"Barbados","BB"},
{"Belarus","BY"},
{"Belgium","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermuda","BM"},
{"Bhutan","BT"},
{"Bolivia","BO"},
{"Bonaire, Sint Eustatius and Saba","BQ"},
{"Bosnia and Herzegovina","BA"},
{"Botswana","BW"},
{"Bouvet Island","BV"},
{"Brazil","BR"},
{"British Indian Ocean Territory","IO"},
{"Brunei Darussalam","BN"},
{"Bulgaria","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Cambodia","KH"},
{"Cameroon","CM"},
{"Canada","CA"},
{"Cape Verde","CV"},
{"Cayman Islands","KY"},
{"Central African Republic","CF"},
{"Chad","TD"},
{"Chile","CL"},
{"China","CN"},
{"Christmas Island","CX"},
{"Cocos Islands","CC"},
{"Colombia","CO"},
{"Comoros","KM"},
{"Congo - Brazzaville","CG"},
{"Congo - Kinshasa","CD"},
{"Cook Islands","CK"},
{"Costa Rica","CR"},
{"Cote d'Ivoire","CI"},
{"Croatia","HR"},
{"Cuba","CU"},
{"Curacao","CW"},
{"Cyprus","CY"},
{"Czech Republic","CZ"},
{"Denmark","DK"},
{"Djibouti","DJ"},
{"Dominica","DM"},
{"Dominican Republic","DO"},
{"East Timor","TP"},
{"Ecuador","EC"},
{"Egypt","EG"},
{"El Salvador","SV"},
{"Equatorial Guinea","GQ"},
{"Eritrea","ER"},
{"Estonia","EE"},
{"Ethiopia","ET"},
{"Falkland Islands","FK"},
{"Faroe Islands","FO"},
{"Fiji","FJ"},
{"Finland","FI"},
{"France","FR"},
{"French Guiana","GF"},
{"French Polynesia","PF"},
{"French Southern Territories","TF"},
{"Gabon","GA"},
{"Gambia","GM"},
{"Georgia","GE"},
{"Germany","DE"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Greece","GR"},
{"Greenland","GL"},
{"Grenada","GD"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guinea","GN"},
{"Guinea-Bissau","GW"},
{"Guyana","GY"},
{"Haiti","HT"},
{"Heard Island and McDonald Islands","HM"},
{"Honduras","HN"},
{"Hong Kong","HK"},
{"Hungary","HU"},
{"Iceland","IS"},
{"India","IN"},
{"Indonesia","ID"},
{"Iran","IR"},
{"Iraq","IQ"},
{"Ireland","IE"},
{"Isle Of Man","IM"},
{"Israel","IL"},
{"Italy","IT"},
{"Jamaica","JM"},
{"Japan","JP"},
{"Jersey","JE"},
{"Jordan","JO"},
{"Kazakhstan","KZ"},
{"Kenya","KE"},
{"Kiribati","KI"},
{"Kuwait","KW"},
{"Kyrgyzstan","KG"},
{"Laos","LA"},
{"Latvia","LV"},
{"Lebanon","LB"},
{"Lesotho","LS"},
{"Liberia","LR"},
{"Libya","LY"},
{"Liechtenstein","LI"},
{"Lithuania","LT"},
{"Luxembourg","LU"},
{"Macao","MO"},
{"Madagascar","MG"},
{"Malawi","MW"},
{"Malaysia","MY"},
{"Maldives","MV"},
{"Mali","ML"},
{"Malta","MT"},
{"Marshall Islands","MH"},
{"Martinique","MQ"},
{"Mauritania","MR"},
{"Mauritius","MU"},
{"Mayotte","YT"},
{"Mexico","MX"},
{"Micronesia","FM"},
{"Moldova","MD"},
{"Monaco","MC"},
{"Mongolia","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Morocco","MA"},
{"Mozambique","MZ"},
{"Myanmar","MM"},
{"Namibia","NA"},
{"Nauru","NR"},
{"Nepal","NP"},
{"Netherlands","NL"},
{"Netherlands Antilles","AN"},
{"New Caledonia","NC"},
{"New Zealand","NZ"},
{"Nicaragua","NI"},
{"Niger","NE"},
{"Nigeria","NG"},
{"Niue","NU"},
{"Norfolk Island","NF"},
{"Northern Mariana Islands","MP"},
{"North Korea","KP"},
{"North Macedonia","MK"},
{"Norway","NO"},
{"Oman","OM"},
{"Pakistan","PK"},
{"Palau","PW"},
{"Palestinian Territories","PS"},
{"Panama","PA"},
{"Papua New Guinea","PG"},
{"Paraguay","PY"},
{"Peru","PE"},
{"Philippines","PH"},
{"Pitcairn","PN"},
{"Poland","PL"},
{"Portugal","PT"},
{"Puerto Rico","PR"},
{"Qatar","QA"},
{"Reunion","RE"},
{"Romania","RO"},
{"Russia","RU"},
{"Rwanda","RW"},
{"Saint Barthelemy","BL"},
{"Saint Helena","SH"},
{"Saint Kitts and Nevis","KN"},
{"Saint Lucia","LC"},
{"Saint Martin (French Part)","MF"},
{"Saint Pierre and Miquelon","PM"},
{"Saint Vincent and The Grenadines","VC"},
{"Samoa","WS"},
{"San Marino","SM"},
{"Sao Tome and Principe","ST"},
{"Saudi Arabia","SA"},
{"Senegal","SN"},
{"Serbia","RS"},
{"Seychelles","SC"},
{"Sierra Leone","SL"},
{"Singapore","SG"},
{"Sint Maarten (Dutch Part)","SX"},
{"Slovakia","SK"},
{"Slovenia","SI"},
{"Solomon Islands","SB"},
{"Somalia","SO"},
{"South Africa","ZA"},
{"South Georgia / South Sandwich Islands","GS"},
{"South Korea","KR"},
{"South Sudan","SS"},
{"Spain","ES"},
{"Sri Lanka","LK"},
{"Sudan","SD"},
{"Suriname","SR"},
{"Svalbard and Jan Mayen","SJ"},
{"Swaziland","SZ"},
{"Sweden","SE"},
{"Switzerland","CH"},
{"Syria","SY"},
{"Taiwan","TW"},
{"Tajikistan","TJ"},
{"Tanzania","TZ"},
{"Thailand","TH"},
{"Timor-Leste","TL"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad and Tobago","TT"},
{"Tunisia","TN"},
{"Turkey","TR"},
{"Turkmenistan","TM"},
{"Turks and Caicos Islands","TC"},
{"Tuvalu","TV"},
{"Uganda","UG"},
{"Ukraine","UA"},
{"United Arab Emirates","AE"},
{"United Kingdom","GB"},
{"United States","US"},
{"Uruguay","UY"},
{"US Minor Outlying Islands","UM"},
{"Uzbekistan","UZ"},
{"Vanuatu","VU"},
{"Vatican City","VA"},
{"Venezuela","VE"},
{"Vietnam","VN"},
{"Virgin Islands, British","VG"},
{"Virgin Islands, U.S.","VI"},
{"Wallis and Futuna","WF"},
{"Western Sahara","EH"},
{"Yemen","YE"},
{"Yugoslavia","YU"},
{"Zambia","ZM"},
{"Zimbabwe","ZW"}