// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_nl.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "nl" collation

{"Afghanistan","AF"},
{"\305land","AX"},
{"Albani\353","AL"},
{"Algerije","DZ"},
{"Amerikaanse Maagdeneilanden","VI"},
{"Amerikaans-Samoa","AS"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguilla","AI"},
{"Antarctica","AQ"},
{"Antigua en Barbuda","AG"},
{"Argentini\353","AR"},
{"Armeni\353","AM"},
{"Aruba","AW"},
{"Australi\353","AU"},
{"Azerbeidzjan","AZ"},
{"Bahama\222s","BS"},
{"Bahrein","BH"},
{"Bangladesh","BD"},
{"Barbados","BB"},
{"Belarus","BY"},
{"Belgi\353","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermuda","BM"},
{"Bhutan","BT"},
{"Bolivia","BO"},
{"Bosni\353 en Herzegovina","BA"},
{"Botswana","BW"},
{"Bouveteiland","BV"},
{"Brazili\353","BR"},
{"Britse Maagdeneilanden","VG"},
{"Brits Indische Oceaanterritorium","IO"},
{"Brunei","BN"},
{"Bulgarije","BG"},
{"Burkina Faso","BF"},
{"Burundi","BI"},
{"Cambodja","KH"},
{"Canada","CA"},
{"Caribisch Nederland","BQ"},
{"Centraal-Afrikaanse Republiek","CF"},
{"Chili","CL"},
{"China","CN"},
{"Christmaseiland","CX"},
{"Cocoseilanden","CC"},
{"Colombia","CO"},
{"Comoren","KM"},
{"Congo-Brazzaville","CG"},
{"Congo-Kinshasa","CD"},
{"Cookeilanden","CK"},
{"Costa Rica","CR"},
{"Cuba","CU"},
{"Cura\347ao","CW"},
{"Cyprus","CY"},
{"Denemarken","DK"},
{"Djibouti","DJ"},
{"Dominica","DM"},
{"Dominicaanse Republiek","DO"},
{"Duitsland","DE"},
{"Ecuador","EC"},
{"Egypte","EG"},
{"El Salvador","SV"},
{"Equatoriaal-Guinea","GQ"},
{"Eritrea","ER"},
{"Estland","EE"},
{"eSwatini","SZ"},
{"Ethiopi\353","ET"},
{"Faer\366er","FO"},
{"Falklandeilanden","FK"},
{"Fiji","FJ"},
{"Filipijnen","PH"},
{"Finland","FI"},
{"Frankrijk","FR"},
{"Franse Gebieden in de zuidelijke Indische Oceaan","TF"},
{"Frans-Guyana","GF"},
{"Frans-Polynesi\353","PF"},
{"Gabon","GA"},
{"Gambia","GM"},
{"Georgi\353","GE"},
{"Ghana","GH"},
{"Gibraltar","GI"},
{"Grenada","GD"},
{"Griekenland","GR"},
{"Groenland","GL"},
{"Guadeloupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guinee","GN"},
{"Guinee-Bissau","GW"},
{"Guyana","GY"},
{"Ha\357ti","HT"},
{"Heard en McDonaldeilanden","HM"},
{"Honduras","HN"},
{"Hongarije","HU"},
{"Hongkong SAR van China","HK"},
{"Ierland","IE"},
{"IJsland","IS"},
{"India","IN"},
{"Indonesi\353","ID"},
{"Irak","IQ"},
{"Iran","IR"},
{"Isle of Man","IM"},
{"Isra\353l","IL"},
{"Itali\353","IT"},
{"Ivoorkust","CI"},
{"Jamaica","JM"},
{"Japan","JP"},
{"Jemen","YE"},
{"Jersey","JE"},
{"Joegoslavi\353","YU"},
{"Jordani\353","JO"},
{"Kaaimaneilanden","KY"},
{"Kaapverdi\353","CV"},
{"Kameroen","CM"},
{"Kazachstan","KZ"},
{"Kenia","KE"},
{"Kirgizi\353","KG"},
{"Kiribati","KI"},
{"Kleine afgelegen eilanden van de Verenigde Staten","UM"},
{"Koeweit","KW"},
{"Kroati\353","HR"},
{"Laos","LA"},
{"Lesotho","LS"},
{"Letland","LV"},
{"Libanon","LB"},
{"Liberia","LR"},
{"Libi\353","LY"},
{"Liechtenstein","LI"},
{"Litouwen","LT"},
{"Luxemburg","LU"},
{"Macau SAR van China","MO"},
{"Madagaskar","MG"},
{"Malawi","MW"},
{"Maldiven","MV"},
{"Maleisi\353","MY"},
{"Mali","ML"},
{"Malta","MT"},
{"Marokko","MA"},
{"Marshalleilanden","MH"},
{"Martinique","MQ"},
{"Mauritani\353","MR"},
{"Mauritius","MU"},
{"Mayotte","YT"},
{"Mexico","MX"},
{"Micronesia","FM"},
{"Moldavi\353","MD"},
{"Monaco","MC"},
{"Mongoli\353","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Mozambique","MZ"},
{"Myanmar (Birma)","MM"},
{"Namibi\353","NA"},
{"Nauru","NR"},
{"Nederland","NL"},
{"Nederlandse Antillen","AN"},
{"Nepal","NP"},
{"Nicaragua","NI"},
{"Nieuw-Caledoni\353","NC"},
{"Nieuw-Zeeland","NZ"},
{"Niger","NE"},
{"Nigeria","NG"},
{"Niue","NU"},
{"Noordelijke Marianen","MP"},
{"Noord-Korea","KP"},
{"Noord-Macedoni\353","MK"},
{"Noorwegen","NO"},
{"Norfolk","NF"},
{"Oeganda","UG"},
{"Oekra\357ne","UA"},
{"Oezbekistan","UZ"},
{"Oman","OM"},
{"Oostenrijk","AT"},
{"Oost-Timor","TL"},
{"Oost-Timor","TP"},
{"Pakistan","PK"},
{"Palau","PW"},
{"Palestijnse gebieden","PS"},
{"Panama","PA"},
{"Papoea-Nieuw-Guinea","PG"},
{"Paraguay","PY"},
{"Peru","PE"},
{"Pitcairneilanden","PN"},
{"Polen","PL"},
{"Portugal","PT"},
{"Puerto Rico","PR"},
{"Qatar","QA"},
{"R\351union","RE"},
{"Roemeni\353","RO"},
{"Rusland","RU"},
{"Rwanda","RW"},
{"Saint-Barth\351lemy","BL"},
{"Saint Kitts en Nevis","KN"},
{"Saint Lucia","LC"},
{"Saint-Martin","MF"},
{"Saint-Pierre en Miquelon","PM"},
{"Saint Vincent en de Grenadines","VC"},
{"Salomonseilanden","SB"},
{"Samoa","WS"},
{"San Marino","SM"},
{"Saoedi-Arabi\353","SA"},
{"Sao Tom\351 en Principe","ST"},
{"Senegal","SN"},
{"Servi\353","RS"},
{"Seychellen","SC"},
{"Sierra Leone","SL"},
{"Singapore","SG"},
{"Sint-Helena","SH"},
{"Sint-Maarten","SX"},
{"Sloveni\353","SI"},
{"Slowakije","SK"},
{"Soedan","SD"},
{"Somali\353","SO"},
{"Spanje","ES"},
{"Spitsbergen en Jan Mayen","SJ"},
{"Sri Lanka","LK"},
{"Suriname","SR"},
{"Syri\353","SY"},
{"Tadzjikistan","TJ"},
{"Taiwan","TW"},
{"Tanzania","TZ"},
{"Thailand","TH"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad en Tobago","TT"},
{"Tsjaad","TD"},
{"Tsjechi\353","CZ"},
{"Tunesi\353","TN"},
{"Turkije","TR"},
{"Turkmenistan","TM"},
{"Turks- en Caicoseilanden","TC"},
{"Tuvalu","TV"},
{"Uruguay","UY"},
{"Vanuatu","VU"},
{"Vaticaanstad","VA"},
{"Venezuela","VE"},
{"Verenigde Arabische Emiraten","AE"},
{"Verenigde Staten","US"},
{"Verenigd Koninkrijk","GB"},
{"Vietnam","VN"},
{"Wallis en Futuna","WF"},
{"Westelijke Sahara","EH"},
{"Zambia","ZM"},
{"Zimbabwe","ZW"},
{"Zuid-Afrika","ZA"},
{"Zuid-Georgia en Zuidelijke Sandwicheilanden","GS"},
{"Zuid-Korea","KR"},
{"Zuid-Soedan","SS"},
{"Zweden","SE"},
{"Zwitserland","CH"}