// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "countries_pt.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-05-13T15:43:38-04:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.49
// Resource file: regions.xml - v1.42
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by name using "pt" collation

{"Afeganist\343o","AF"},
{"\301frica do Sul","ZA"},
{"Alb\342nia","AL"},
{"Alemanha","DE"},
{"Andorra","AD"},
{"Angola","AO"},
{"Anguila","AI"},
{"Ant\341rtida","AQ"},
{"Ant\355gua e Barbuda","AG"},
{"Antilhas Holandesas","AN"},
{"Ar\341bia Saudita","SA"},
{"Arg\351lia","DZ"},
{"Argentina","AR"},
{"Arm\352nia","AM"},
{"Aruba","AW"},
{"Austr\341lia","AU"},
{"\301ustria","AT"},
{"Azerbaij\343o","AZ"},
{"Bahamas","BS"},
{"Bahrein","BH"},
{"Bangladesh","BD"},
{"Barbados","BB"},
{"B\351lgica","BE"},
{"Belize","BZ"},
{"Benin","BJ"},
{"Bermudas","BM"},
{"Bielorr\372ssia","BY"},
{"Bol\355via","BO"},
{"B\363snia e Herzegovina","BA"},
{"Botsuana","BW"},
{"Brasil","BR"},
{"Brunei","BN"},
{"Bulg\341ria","BG"},
{"Burquina Faso","BF"},
{"Burundi","BI"},
{"But\343o","BT"},
{"Cabo Verde","CV"},
{"Camar\365es","CM"},
{"Camboja","KH"},
{"Canad\341","CA"},
{"Catar","QA"},
{"Cazaquist\343o","KZ"},
{"Chade","TD"},
{"Chile","CL"},
{"China","CN"},
{"Chipre","CY"},
{"Cidade do Vaticano","VA"},
{"Col\364mbia","CO"},
{"Comores","KM"},
{"Congo - Kinshasa","CD"},
{"Coreia do Norte","KP"},
{"Coreia do Sul","KR"},
{"Costa do Marfim","CI"},
{"Costa Rica","CR"},
{"Cro\341cia","HR"},
{"Cuba","CU"},
{"Cura\347ao","CW"},
{"Dinamarca","DK"},
{"Djibuti","DJ"},
{"Dominica","DM"},
{"Egito","EG"},
{"El Salvador","SV"},
{"Emirados \301rabes Unidos","AE"},
{"Equador","EC"},
{"Eritreia","ER"},
{"Eslov\341quia","SK"},
{"Eslov\352nia","SI"},
{"Espanha","ES"},
{"Estados Unidos","US"},
{"Est\364nia","EE"},
{"Eti\363pia","ET"},
{"Fiji","FJ"},
{"Filipinas","PH"},
{"Finl\342ndia","FI"},
{"Fran\347a","FR"},
{"Gab\343o","GA"},
{"G\342mbia","GM"},
{"Gana","GH"},
{"Ge\363rgia","GE"},
{"Gibraltar","GI"},
{"Granada","GD"},
{"Gr\351cia","GR"},
{"Groenl\342ndia","GL"},
{"Guadalupe","GP"},
{"Guam","GU"},
{"Guatemala","GT"},
{"Guernsey","GG"},
{"Guiana","GY"},
{"Guiana Francesa","GF"},
{"Guin\351","GN"},
{"Guin\351-Bissau","GW"},
{"Guin\351 Equatorial","GQ"},
{"Haiti","HT"},
{"Honduras","HN"},
{"Hong Kong, RAE da China","HK"},
{"Hungria","HU"},
{"I\352men","YE"},
{"Ilha Bouvet","BV"},
{"Ilha Christmas","CX"},
{"Ilha de Man","IM"},
{"Ilha Norfolk","NF"},
{"Ilhas Aland","AX"},
{"Ilhas Cayman","KY"},
{"Ilhas Cocos (Keeling)","CC"},
{"Ilhas Cook","CK"},
{"Ilhas Faroe","FO"},
{"Ilhas Ge\363rgia do Sul e Sandwich do Sul","GS"},
{"Ilhas Heard e McDonald","HM"},
{"Ilhas Malvinas","FK"},
{"Ilhas Marianas do Norte","MP"},
{"Ilhas Marshall","MH"},
{"Ilhas Menores Distantes dos EUA","UM"},
{"Ilhas Pitcairn","PN"},
{"Ilhas Salom\343o","SB"},
{"Ilhas Turcas e Caicos","TC"},
{"Ilhas Virgens Americanas","VI"},
{"Ilhas Virgens Brit\342nicas","VG"},
{"\315ndia","IN"},
{"Indon\351sia","ID"},
{"Ir\343","IR"},
{"Iraque","IQ"},
{"Irlanda","IE"},
{"Isl\342ndia","IS"},
{"Israel","IL"},
{"It\341lia","IT"},
{"Jamaica","JM"},
{"Jap\343o","JP"},
{"Jersey","JE"},
{"Jord\342nia","JO"},
{"Jugosl\341via","YU"},
{"Kuwait","KW"},
{"Laos","LA"},
{"Lesoto","LS"},
{"Let\364nia","LV"},
{"L\355bano","LB"},
{"Lib\351ria","LR"},
{"L\355bia","LY"},
{"Liechtenstein","LI"},
{"Litu\342nia","LT"},
{"Luxemburgo","LU"},
{"Macau, RAE da China","MO"},
{"Maced\364nia do Norte","MK"},
{"Madagascar","MG"},
{"Mal\341sia","MY"},
{"Malaui","MW"},
{"Maldivas","MV"},
{"Mali","ML"},
{"Malta","MT"},
{"Marrocos","MA"},
{"Martinica","MQ"},
{"Maur\355cio","MU"},
{"Maurit\342nia","MR"},
{"Mayotte","YT"},
{"M\351xico","MX"},
{"Mianmar (Birm\342nia)","MM"},
{"Micron\351sia","FM"},
{"Mo\347ambique","MZ"},
{"Moldova","MD"},
{"M\364naco","MC"},
{"Mong\363lia","MN"},
{"Montenegro","ME"},
{"Montserrat","MS"},
{"Nam\355bia","NA"},
{"Nauru","NR"},
{"Nepal","NP"},
{"Nicar\341gua","NI"},
{"N\355ger","NE"},
{"Nig\351ria","NG"},
{"Niue","NU"},
{"Noruega","NO"},
{"Nova Caled\364nia","NC"},
{"Nova Zel\342ndia","NZ"},
{"Om\343","OM"},
{"Pa\355ses Baixos","NL"},
{"Pa\355ses Baixos Caribenhos","BQ"},
{"Palau","PW"},
{"Panam\341","PA"},
{"Papua-Nova Guin\351","PG"},
{"Paquist\343o","PK"},
{"Paraguai","PY"},
{"Peru","PE"},
{"Polin\351sia Francesa","PF"},
{"Pol\364nia","PL"},
{"Porto Rico","PR"},
{"Portugal","PT"},
{"Qu\352nia","KE"},
{"Quirguist\343o","KG"},
{"Quiribati","KI"},
{"Reino Unido","GB"},
{"Rep\372blica Centro-Africana","CF"},
{"Rep\372blica do Congo","CG"},
{"Rep\372blica Dominicana","DO"},
{"Reuni\343o","RE"},
{"Rom\352nia","RO"},
{"Ruanda","RW"},
{"R\372ssia","RU"},
{"Saara Ocidental","EH"},
{"Samoa","WS"},
{"Samoa Americana","AS"},
{"San Marino","SM"},
{"Santa Helena","SH"},
{"Santa L\372cia","LC"},
{"S\343o Bartolomeu","BL"},
{"S\343o Crist\363v\343o e N\351vis","KN"},
{"S\343o Martinho","MF"},
{"S\343o Pedro e Miquel\343o","PM"},
{"S\343o Tom\351 e Pr\355ncipe","ST"},
{"S\343o Vicente e Granadinas","VC"},
{"Seicheles","SC"},
{"Senegal","SN"},
{"Serra Leoa","SL"},
{"S\351rvia","RS"},
{"Singapura","SG"},
{"Sint Maarten","SX"},
{"S\355ria","SY"},
{"Som\341lia","SO"},
{"Sri Lanka","LK"},
{"Suazil\342ndia","SZ"},
{"Sud\343o","SD"},
{"Sud\343o do Sul","SS"},
{"Su\351cia","SE"},
{"Su\355\347a","CH"},
{"Suriname","SR"},
{"Svalbard e Jan Mayen","SJ"},
{"Tadjiquist\343o","TJ"},
{"Tail\342ndia","TH"},
{"Taiwan","TW"},
{"Tanz\342nia","TZ"},
{"Tch\351quia","CZ"},
{"Territ\363rio Brit\342nico do Oceano \315ndico","IO"},
{"Territ\363rios Franceses do Sul","TF"},
{"Territ\363rios palestinos","PS"},
{"Timor-Leste","TL"},
{"Timor Leste","TP"},
{"Togo","TG"},
{"Tokelau","TK"},
{"Tonga","TO"},
{"Trinidad e Tobago","TT"},
{"Tun\355sia","TN"},
{"Turcomenist\343o","TM"},
{"Turquia","TR"},
{"Tuvalu","TV"},
{"Ucr\342nia","UA"},
{"Uganda","UG"},
{"Uruguai","UY"},
{"Uzbequist\343o","UZ"},
{"Vanuatu","VU"},
{"Venezuela","VE"},
{"Vietn\343","VN"},
{"Wallis e Futuna","WF"},
{"Z\342mbia","ZM"},
{"Zimb\341bue","ZW"}