// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "protocols/statesFR.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2016-11-18T09:53:53.916-05:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.46
// Resource file: regions.xml - v1.39
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by CountryCode and RegionName using "en"  collation
// Format: {RegionName, CountryCode, RegionCode}
{"Saint Barthelemy","BL","977"},
{"Ain","FR","01"},
{"Aisne","FR","02"},
{"Allier","FR","03"},
{"Alpes-de-Haute-Provence","FR","04"},
{"Alpes-Maritimes","FR","06"},
{"Ard\352che","FR","07"},
{"Ardennes","FR","08"},
{"Ariege","FR","09"},
{"Aube","FR","10"},
{"Aude","FR","11"},
{"Aveyron","FR","12"},
{"Bouches-du-Rh\364ne","FR","13"},
{"Calvados","FR","14"},
{"Cantal","FR","15"},
{"Charente","FR","16"},
{"Charente-Maritime","FR","17"},
{"Cher","FR","18"},
{"Clipperton Island","FR","989"},
{"Correze","FR","19"},
{"C\364te-d'Or","FR","21"},
{"C\364tes-d'Armor","FR","22"},
{"Creuse","FR","23"},
{"Deux-S\350vres","FR","79"},
{"Dordogne","FR","24"},
{"Doubs","FR","25"},
{"Drome","FR","26"},
{"Eastern Pyrenees","FR","66"},
{"Essonne","FR","91"},
{"Eure","FR","27"},
{"Eure-et-Loir","FR","28"},
{"Finist\350re","FR","29"},
{"French Guiana","FR","973"},
{"French Polynesia","FR","987"},
{"French Southern and Antarctic Territories","FR","984"},
{"Gard","FR","30"},
{"Gers","FR","32"},
{"Gironde","FR","33"},
{"Guadeloupe","FR","971"},
{"Haute-Loire","FR","43"},
{"Haute-Marne","FR","52"},
{"Hautes-Alpes","FR","05"},
{"Haute-Sa\364ne","FR","70"},
{"Hautes-Pyren\351es","FR","65"},
{"Haute-Vienne","FR","87"},
{"Hauts-de-Seine","FR","92"},
{"H\351rault","FR","34"},
{"Ille-et-Vilaine","FR","35"},
{"Indre","FR","36"},
{"Indre-et-Loire","FR","37"},
{"Is\350re","FR","38"},
{"Jura","FR","39"},
{"Landes","FR","40"},
{"Loire","FR","42"},
{"Loire-Atlantique","FR","44"},
{"Loiret","FR","45"},
{"Loir-et-Cher","FR","41"},
{"Lot","FR","46"},
{"Lot-et-Garonne","FR","47"},
{"Lower Rhine","FR","67"},
{"Loz\350re","FR","48"},
{"Maine-et-Loire","FR","49"},
{"Manche","FR","50"},
{"Marne","FR","51"},
{"Martinique","FR","972"},
{"Mayenne","FR","53"},
{"Mayotte","FR","976"},
{"Meurthe-et-Moselle","FR","54"},
{"Meuse","FR","55"},
{"Morbihan","FR","56"},
{"Moselle","FR","57"},
{"New Caledonia","FR","988"},
{"Nievre","FR","58"},
{"North","FR","59"},
{"Oise","FR","60"},
{"Orne","FR","61"},
{"Paris","FR","75"},
{"Pas-de-Calais","FR","62"},
{"Puy-de-D\364me","FR","63"},
{"Pyren\351es-Atlantiques","FR","64"},
{"Reunion","FR","974"},
{"Rh\364ne","FR","69"},
{"Saint Barthelemy","FR","977"},
{"Saint-Martin","FR","978"},
{"Saint Pierre and Miquelon","FR","975"},
{"Sa\364ne-et-Loire","FR","71"},
{"Sarthe","FR","72"},
{"Savoy","FR","73"},
{"Seine-et-Marne","FR","77"},
{"Seine-Maritime","FR","76"},
{"Seine-Saint-Denis","FR","93"},
{"Somme","FR","80"},
{"South Corsica","FR","2A"},
{"Tarn","FR","81"},
{"Tarn-et-Garonne","FR","82"},
{"Territoire de Belfort","FR","90"},
{"Upper Corsica","FR","2B"},
{"Upper Garonne","FR","31"},
{"Upper Rhine","FR","68"},
{"Upper Savoy","FR","74"},
{"Val-d'Oise","FR","95"},
{"Val-de-Marne","FR","94"},
{"Var","FR","83"},
{"Vaucluse","FR","84"},
{"Vend\351e","FR","85"},
{"Vienne","FR","86"},
{"V\364sges","FR","88"},
{"Wallis and Futuna","FR","986"},
{"Yonne","FR","89"},
{"Yvelines","FR","78"},
{"French Guiana","GF","973"},
{"Guadeloupe","GP","971"},
{"Saint-Martin","MF","978"},
{"Martinique","MQ","972"},
{"New Caledonia","NC","988"},
{"French Polynesia","PF","987"},
{"Saint Pierre and Miquelon","PM","975"},
{"Reunion","RE","974"},
{"French Southern and Antarctic Territories","TF","984"},
{"Wallis and Futuna","WF","986"},
{"Mayotte","YT","976"}