// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "protocols/statesFR_fr.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2016-11-18T09:53:53.916-05:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.46
// Resource file: regions.xml - v1.39
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by CountryCode and RegionName using "fr"  collation
// Format: {RegionName, CountryCode, RegionCode}
{"Saint-Barth\351lemy","BL","977"},
{"Ain","FR","01"},
{"Aisne","FR","02"},
{"Allier","FR","03"},
{"Alpes-de-Haute-Provence","FR","04"},
{"Alpes-Maritimes","FR","06"},
{"Ard\352che","FR","07"},
{"Ardennes","FR","08"},
{"Ariege","FR","09"},
{"Aube","FR","10"},
{"Aude","FR","11"},
{"Aveyron","FR","12"},
{"Bas-Rhin","FR","67"},
{"Bouches-du-Rh\364ne","FR","13"},
{"Calvados","FR","14"},
{"Cantal","FR","15"},
{"Charente","FR","16"},
{"Charente-Maritime","FR","17"},
{"Cher","FR","18"},
{"Correze","FR","19"},
{"Corse-du-Sud","FR","2A"},
{"C\364te-d'Or","FR","21"},
{"C\364tes-d'Armor","FR","22"},
{"Creuse","FR","23"},
{"Deux-S\350vres","FR","79"},
{"Dordogne","FR","24"},
{"Doubs","FR","25"},
{"Drome","FR","26"},
{"Essonne","FR","91"},
{"Eure","FR","27"},
{"Eure-et-Loir","FR","28"},
{"Finist\350re","FR","29"},
{"Gard","FR","30"},
{"Gers","FR","32"},
{"Gironde","FR","33"},
{"Guadeloupe","FR","971"},
{"Guyane","FR","973"},
{"Haute-Corse","FR","2B"},
{"Haute-Garonne","FR","31"},
{"Haute-Loire","FR","43"},
{"Haute-Marne","FR","52"},
{"Hautes-Alpes","FR","05"},
{"Haute-Sa\364ne","FR","70"},
{"Haute-Savoie","FR","74"},
{"Hautes-Pyren\351es","FR","65"},
{"Haute-Vienne","FR","87"},
{"Haut-Rhin","FR","68"},
{"Hauts-de-Seine","FR","92"},
{"H\351rault","FR","34"},
{"\316le de Clipperton","FR","989"},
{"Ille-et-Vilaine","FR","35"},
{"Indre","FR","36"},
{"Indre-et-Loire","FR","37"},
{"Is\350re","FR","38"},
{"Jura","FR","39"},
{"Landes","FR","40"},
{"La R\351union","FR","974"},
{"Loire","FR","42"},
{"Loire-Atlantique","FR","44"},
{"Loiret","FR","45"},
{"Loir-et-Cher","FR","41"},
{"Lot","FR","46"},
{"Lot-et-Garonne","FR","47"},
{"Loz\350re","FR","48"},
{"Maine-et-Loire","FR","49"},
{"Manche","FR","50"},
{"Marne","FR","51"},
{"Martinique","FR","972"},
{"Mayenne","FR","53"},
{"Mayotte","FR","976"},
{"Meurthe-et-Moselle","FR","54"},
{"Meuse","FR","55"},
{"Morbihan","FR","56"},
{"Moselle","FR","57"},
{"Nievre","FR","58"},
{"Nord","FR","59"},
{"Nouvelle-Cal\351donie","FR","988"},
{"Oise","FR","60"},
{"Orne","FR","61"},
{"Paris","FR","75"},
{"Pas-de-Calais","FR","62"},
{"Polyn\351sie fran\347aise","FR","987"},
{"Puy-de-D\364me","FR","63"},
{"Pyren\351es-Atlantiques","FR","64"},
{"Pyren\351es-Orientales","FR","66"},
{"Rh\364ne","FR","69"},
{"Saint-Barth\351lemy","FR","977"},
{"Saint-Martin","FR","978"},
{"Saint-Pierre-et-Miquelon","FR","975"},
{"Sa\364ne-et-Loire","FR","71"},
{"Sarthe","FR","72"},
{"Savoie","FR","73"},
{"Seine-et-Marne","FR","77"},
{"Seine-Maritime","FR","76"},
{"Seine-Saint-Denis","FR","93"},
{"Somme","FR","80"},
{"Tarn","FR","81"},
{"Tarn-et-Garonne","FR","82"},
{"Terres australes et antarctiques fran\347aises","FR","984"},
{"Territoire de Belfort","FR","90"},
{"Val-d'Oise","FR","95"},
{"Val-de-Marne","FR","94"},
{"Var","FR","83"},
{"Vaucluse","FR","84"},
{"Vend\351e","FR","85"},
{"Vienne","FR","86"},
{"V\364sges","FR","88"},
{"Wallis et Futuna","FR","986"},
{"Yonne","FR","89"},
{"Yvelines","FR","78"},
{"Guyane","GF","973"},
{"Guadeloupe","GP","971"},
{"Saint-Martin","MF","978"},
{"Martinique","MQ","972"},
{"Nouvelle-Cal\351donie","NC","988"},
{"Polyn\351sie fran\347aise","PF","987"},
{"Saint-Pierre-et-Miquelon","PM","975"},
{"La R\351union","RE","974"},
{"Terres australes et antarctiques fran\347aises","TF","984"},
{"Wallis et Futuna","WF","986"},
{"Mayotte","YT","976"}