// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "protocols/statesIT_it.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2016-11-18T09:53:53.916-05:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.46
// Resource file: regions.xml - v1.39
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by RegionName using "it"  collation
// Format: {RegionName, RegionCode}
{"Agrigento","AG"},
{"Alessandria","AL"},
{"Ancona","AN"},
{"Aosta","AO"},
{"Arezzo","AR"},
{"Ascoli Piceno","AP"},
{"Asti","AT"},
{"Avellino","AV"},
{"Bari","BA"},
{"Barletta-Andria-Trani","BT"},
{"Belluno","BL"},
{"Benevento","BN"},
{"Bergamo","BG"},
{"Biella","BI"},
{"Bologna","BO"},
{"Bolzano","BZ"},
{"Brescia","BS"},
{"Brindisi","BR"},
{"Cagliari","CA"},
{"Caltanissetta","CL"},
{"Campobasso","CB"},
{"Carbonia-Iglesias","CI"},
{"Caserta","CE"},
{"Catania","CT"},
{"Catanzaro","CZ"},
{"Chieti","CH"},
{"Como","CO"},
{"Cosenza","CS"},
{"Cremona","CR"},
{"Crotone","KR"},
{"Cuneo","CN"},
{"Enna","EN"},
{"Fermo","FM"},
{"Ferrara","FE"},
{"Firenze","FI"},
{"Foggia","FG"},
{"Forli-Cesena","FC"},
{"Frosinone","FR"},
{"Genova","GE"},
{"Gorizia","GO"},
{"Grosseto","GR"},
{"Imperia","IM"},
{"Isernia","IS"},
{"L'Aquila","AQ"},
{"La Spezia","SP"},
{"Latina","LT"},
{"Lecce","LE"},
{"Lecco","LC"},
{"Livorno","LI"},
{"Lodi","LO"},
{"Lucca","LU"},
{"Macerata","MC"},
{"Mantova","MN"},
{"Massa-Carrara","MS"},
{"Matera","MT"},
{"Medio-Campidano","VS"},
{"Messina","ME"},
{"Milano","MI"},
{"Modena","MO"},
{"Monza e Brianza","MB"},
{"Napoli","NA"},
{"Novara","NO"},
{"Nuoro","NU"},
{"Ogliastra","OG"},
{"Olbia-Tempio","OT"},
{"Oristano","OR"},
{"Padova","PD"},
{"Palermo","PA"},
{"Parma","PR"},
{"Pavia","PV"},
{"Perugia","PG"},
{"Pesaro e Urbino","PU"},
{"Pescara","PE"},
{"Piacenza","PC"},
{"Pisa","PI"},
{"Pistoia","PT"},
{"Pordenone","PN"},
{"Potenza","PZ"},
{"Prato","PO"},
{"Ragusa","RG"},
{"Ravenna","RA"},
{"Reggio Calabria","RC"},
{"Reggio Emilia","RE"},
{"Rieti","RI"},
{"Rimini","RN"},
{"Roma","RM"},
{"Rovigo","RO"},
{"Salerno","SA"},
{"Sassari","SS"},
{"Savona","SV"},
{"Siena","SI"},
{"Siracusa","SR"},
{"Sondrio","SO"},
{"Taranto","TA"},
{"Teramo","TE"},
{"Terni","TR"},
{"Torino","TO"},
{"Trapani","TP"},
{"Trento","TN"},
{"Treviso","TV"},
{"Trieste","TS"},
{"Udine","UD"},
{"Varese","VA"},
{"Venezia","VE"},
{"Verbano Cusio Ossola","VB"},
{"Vercelli","VC"},
{"Verona","VR"},
{"Vibo Valentia","VV"},
{"Vicenza","VI"},
{"Viterbo","VT"}