// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "protocols/states_admin.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-11-12T09:24:42-05:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.51
// Resource file: regions.xml - v1.43
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by CountryCode and RegionName using "en" collation
// Format: {RegionName, CountryCode, RegionCode}
{"Buenos Aires","AR","C"},
{"Buenos Aires Province","AR","B"},
{"Catamarca","AR","K"},
{"Chaco","AR","H"},
{"Chubut","AR","U"},
{"C\363rdoba","AR","X"},
{"Corrientes","AR","W"},
{"Entre R\355os","AR","E"},
{"Formosa","AR","P"},
{"Jujuy","AR","Y"},
{"La Pampa","AR","L"},
{"La Rioja","AR","F"},
{"Mendoza","AR","M"},
{"Misiones","AR","N"},
{"Neuqu\351n","AR","Q"},
{"R\355o Negro","AR","R"},
{"Salta","AR","A"},
{"San Juan","AR","J"},
{"San Luis","AR","D"},
{"Santa Cruz","AR","Z"},
{"Santa Fe","AR","S"},
{"Santiago del Estero","AR","G"},
{"Tierra del Fuego","AR","V"},
{"Tucum\341n","AR","T"},
{"Australian Capital Territory","AU","ACT"},
{"New South Wales","AU","NSW"},
{"Northern Territory","AU","NT"},
{"Queensland","AU","QLD"},
{"South Australia","AU","SA"},
{"Tasmania","AU","TAS"},
{"Victoria","AU","VIC"},
{"Western Australia","AU","WA"},
{"Antwerp","BE","VAN"},
{"Brussels-Capital Region","BE","BRU"},
{"East Flanders","BE","VOV"},
{"Flemish Brabant","BE","VBR"},
{"Hainaut","BE","WHT"},
{"Li\350ge","BE","WLG"},
{"Limburg","BE","VLI"},
{"Luxembourg","BE","WLX"},
{"Namur","BE","WNA"},
{"Walloon Brabant","BE","WBR"},
{"West Flanders","BE","VWV"},
{"Saint Barthelemy","BL","977"},
{"Acre","BR","AC"},
{"Alagoas","BR","AL"},
{"Amapa","BR","AP"},
{"Amazonas","BR","AM"},
{"Bahia","BR","BA"},
{"Ceara","BR","CE"},
{"Espirito Santo","BR","ES"},
{"Federal District","BR","DF"},
{"Goias","BR","GO"},
{"Maranhao","BR","MA"},
{"Mato Grosso","BR","MT"},
{"Mato Grosso do Sul","BR","MS"},
{"Minas Gerais","BR","MG"},
{"Para","BR","PA"},
{"Paraiba","BR","PB"},
{"Parana","BR","PR"},
{"Pernambuco","BR","PE"},
{"Piaui","BR","PI"},
{"Rio de Janeiro","BR","RJ"},
{"Rio Grande do Norte","BR","RN"},
{"Rio Grande do Sul","BR","RS"},
{"Rondonia","BR","RO"},
{"Roraima","BR","RR"},
{"Santa Catarina","BR","SC"},
{"Sao Paulo","BR","SP"},
{"Sergipe","BR","SE"},
{"Tocantins","BR","TO"},
{"Alberta","CA","AB"},
{"British Columbia","CA","BC"},
{"Manitoba","CA","MB"},
{"New Brunswick","CA","NB"},
{"Newfoundland and Labrador","CA","NL"},
{"Northwest Territories","CA","NT"},
{"Nova Scotia","CA","NS"},
{"Nunavut","CA","NU"},
{"Ontario","CA","ON"},
{"Prince Edward Island","CA","PE"},
{"Quebec","CA","QC"},
{"Saskatchewan","CA","SK"},
{"Yukon","CA","YT"},
{"Central Bohemian","CZ","ST"},
{"Highlands","CZ","VY"},
{"Hradec Kr\341lov\351","CZ","KR"},
{"Karlovy Vary","CZ","KA"},
{"Liberec","CZ","LI"},
{"Moravian-Silesian","CZ","MO"},
{"Olomouc","CZ","OL"},
{"Pardubice","CZ","PA"},
{"Plzen","CZ","PL"},
{"Prague","CZ","PR"},
{"South Bohemian","CZ","JC"},
{"South Moravian","CZ","JM"},
{"Usti nad Labem","CZ","US"},
{"Zlin","CZ","ZL"},
{"Baden-W\374rttemberg","DE","BW"},
{"Bavaria","DE","BY"},
{"Berlin","DE","BE"},
{"Brandenburg","DE","BB"},
{"Bremen","DE","HB"},
{"Hamburg","DE","HH"},
{"Hesse","DE","HE"},
{"Lower Saxony","DE","NI"},
{"Mecklenburg-Vorpommern","DE","MV"},
{"North Rhine-Westphalia","DE","NW"},
{"Rhineland-Palatinate","DE","RP"},
{"Saarland","DE","SL"},
{"Saxony","DE","SN"},
{"Saxony-Anhalt","DE","ST"},
{"Schleswig-Holstein","DE","SH"},
{"Thuringia","DE","TH"},
{"Ain","FR","01"},
{"Aisne","FR","02"},
{"Allier","FR","03"},
{"Alpes-de-Haute-Provence","FR","04"},
{"Alpes-Maritimes","FR","06"},
{"Ard\352che","FR","07"},
{"Ardennes","FR","08"},
{"Ariege","FR","09"},
{"Aube","FR","10"},
{"Aude","FR","11"},
{"Aveyron","FR","12"},
{"Bouches-du-Rh\364ne","FR","13"},
{"Calvados","FR","14"},
{"Cantal","FR","15"},
{"Charente","FR","16"},
{"Charente-Maritime","FR","17"},
{"Cher","FR","18"},
{"Clipperton Island","FR","989"},
{"Correze","FR","19"},
{"C\364te-d'Or","FR","21"},
{"C\364tes-d'Armor","FR","22"},
{"Creuse","FR","23"},
{"Deux-S\350vres","FR","79"},
{"Dordogne","FR","24"},
{"Doubs","FR","25"},
{"Drome","FR","26"},
{"Eastern Pyrenees","FR","66"},
{"Essonne","FR","91"},
{"Eure","FR","27"},
{"Eure-et-Loir","FR","28"},
{"Finist\350re","FR","29"},
{"French Guiana","FR","973"},
{"French Polynesia","FR","987"},
{"French Southern and Antarctic Territories","FR","984"},
{"Gard","FR","30"},
{"Gers","FR","32"},
{"Gironde","FR","33"},
{"Guadeloupe","FR","971"},
{"Haute-Loire","FR","43"},
{"Haute-Marne","FR","52"},
{"Hautes-Alpes","FR","05"},
{"Haute-Sa\364ne","FR","70"},
{"Hautes-Pyren\351es","FR","65"},
{"Haute-Vienne","FR","87"},
{"Hauts-de-Seine","FR","92"},
{"H\351rault","FR","34"},
{"Ille-et-Vilaine","FR","35"},
{"Indre","FR","36"},
{"Indre-et-Loire","FR","37"},
{"Is\350re","FR","38"},
{"Jura","FR","39"},
{"Landes","FR","40"},
{"Loire","FR","42"},
{"Loire-Atlantique","FR","44"},
{"Loiret","FR","45"},
{"Loir-et-Cher","FR","41"},
{"Lot","FR","46"},
{"Lot-et-Garonne","FR","47"},
{"Lower Rhine","FR","67"},
{"Loz\350re","FR","48"},
{"Maine-et-Loire","FR","49"},
{"Manche","FR","50"},
{"Marne","FR","51"},
{"Martinique","FR","972"},
{"Mayenne","FR","53"},
{"Mayotte","FR","976"},
{"Meurthe-et-Moselle","FR","54"},
{"Meuse","FR","55"},
{"Morbihan","FR","56"},
{"Moselle","FR","57"},
{"New Caledonia","FR","988"},
{"Nievre","FR","58"},
{"North","FR","59"},
{"Oise","FR","60"},
{"Orne","FR","61"},
{"Paris","FR","75"},
{"Pas-de-Calais","FR","62"},
{"Puy-de-D\364me","FR","63"},
{"Pyren\351es-Atlantiques","FR","64"},
{"Reunion","FR","974"},
{"Rh\364ne","FR","69"},
{"Saint Barthelemy","FR","977"},
{"Saint-Martin","FR","978"},
{"Saint Pierre and Miquelon","FR","975"},
{"Sa\364ne-et-Loire","FR","71"},
{"Sarthe","FR","72"},
{"Savoy","FR","73"},
{"Seine-et-Marne","FR","77"},
{"Seine-Maritime","FR","76"},
{"Seine-Saint-Denis","FR","93"},
{"Somme","FR","80"},
{"South Corsica","FR","2A"},
{"Tarn","FR","81"},
{"Tarn-et-Garonne","FR","82"},
{"Territoire de Belfort","FR","90"},
{"Upper Corsica","FR","2B"},
{"Upper Garonne","FR","31"},
{"Upper Rhine","FR","68"},
{"Upper Savoy","FR","74"},
{"Val-d'Oise","FR","95"},
{"Val-de-Marne","FR","94"},
{"Var","FR","83"},
{"Vaucluse","FR","84"},
{"Vend\351e","FR","85"},
{"Vienne","FR","86"},
{"V\364sges","FR","88"},
{"Wallis and Futuna","FR","986"},
{"Yonne","FR","89"},
{"Yvelines","FR","78"},
{"French Guiana","GF","973"},
{"Guadeloupe","GP","971"},
{"Attica","GR","I"},
{"Central Greece","GR","H"},
{"Central Macedonia","GR","B"},
{"Crete","GR","M"},
{"East Macedonia and Thrace","GR","A"},
{"Epirus","GR","D"},
{"Ionian Islands","GR","F"},
{"North Aegean","GR","K"},
{"Peloponnese","GR","J"},
{"South Aegean","GR","L"},
{"Thessaly ","GR","E"},
{"West Greece ","GR","G"},
{"West Macedonia","GR","C"},
{"Carlow","IE","CW"},
{"Cavan","IE","CN"},
{"Clare","IE","CE"},
{"Cork","IE","CK"},
{"Donegal","IE","DL"},
{"Dublin","IE","DN"},
{"Galway","IE","GY"},
{"Kerry","IE","KY"},
{"Kildare","IE","KE"},
{"Kilkenny","IE","KK"},
{"Laois","IE","LS"},
{"Leitrim","IE","LM"},
{"Limerick","IE","LK"},
{"Longford","IE","LD"},
{"Louth","IE","LH"},
{"Mayo","IE","MO"},
{"Meath","IE","MH"},
{"Monaghan","IE","MN"},
{"Offaly","IE","OY"},
{"Roscommon","IE","RN"},
{"Sligo","IE","SO"},
{"Tipperary","IE","TY"},
{"Waterford","IE","WD"},
{"Westmeath","IE","WH"},
{"Wexford","IE","WX"},
{"Wicklow","IE","WW"},
{"Andaman and Nicobar Islands","IN","AN"},
{"Andhra Pradesh","IN","AP"},
{"Arunachal Pradesh","IN","AR"},
{"Assam","IN","AS"},
{"Bihar","IN","BR"},
{"Chandigarh","IN","CH"},
{"Chhattisgarh","IN","CR"},
{"Dadra and Nagar Haveli","IN","DN"},
{"Daman and Diu","IN","DD"},
{"Delhi","IN","DL"},
{"Goa","IN","GA"},
{"Gujarat","IN","GJ"},
{"Haryana","IN","HR"},
{"Himachal Pradesh","IN","HP"},
{"Jammu and Kashmir","IN","JK"},
{"Jharkhand","IN","JH"},
{"Karnataka","IN","KA"},
{"Kerala","IN","KL"},
{"Lakshadweep","IN","LD"},
{"Madhya Pradesh","IN","MP"},
{"Maharashtra","IN","MH"},
{"Manipur","IN","MN"},
{"Meghalaya","IN","ML"},
{"Mizoram","IN","MZ"},
{"Nagaland","IN","NL"},
{"Odisha","IN","OR"},
{"Puducherry","IN","PY"},
{"Punjab","IN","PB"},
{"Rajasthan","IN","RJ"},
{"Sikkim","IN","SK"},
{"Tamil Nadu","IN","TN"},
{"Telangana","IN","TG"},
{"Tripura","IN","TR"},
{"Uttarakhand","IN","UT"},
{"Uttar Pradesh","IN","UP"},
{"West Bengal","IN","WB"},
{"Agrigento","IT","AG"},
{"Alessandria","IT","AL"},
{"Ancona","IT","AN"},
{"Aosta","IT","AO"},
{"Arezzo","IT","AR"},
{"Ascoli Piceno","IT","AP"},
{"Asti","IT","AT"},
{"Avellino","IT","AV"},
{"Bari","IT","BA"},
{"Barletta-Andria-Trani","IT","BT"},
{"Belluno","IT","BL"},
{"Benevento","IT","BN"},
{"Bergamo","IT","BG"},
{"Biella","IT","BI"},
{"Bologna","IT","BO"},
{"Bolzano","IT","BZ"},
{"Brescia","IT","BS"},
{"Brindisi","IT","BR"},
{"Cagliari","IT","CA"},
{"Caltanissetta","IT","CL"},
{"Campobasso","IT","CB"},
{"Carbonia-Iglesias","IT","CI"},
{"Caserta","IT","CE"},
{"Catania","IT","CT"},
{"Catanzaro","IT","CZ"},
{"Chieti","IT","CH"},
{"Como","IT","CO"},
{"Cosenza","IT","CS"},
{"Cremona","IT","CR"},
{"Crotone","IT","KR"},
{"Cuneo","IT","CN"},
{"Enna","IT","EN"},
{"Fermo","IT","FM"},
{"Ferrara","IT","FE"},
{"Florence","IT","FI"},
{"Foggia","IT","FG"},
{"Forli-Cesena","IT","FC"},
{"Frosinone","IT","FR"},
{"Genoa","IT","GE"},
{"Gorizia","IT","GO"},
{"Grosseto","IT","GR"},
{"Imperia","IT","IM"},
{"Isernia","IT","IS"},
{"L'Aquila","IT","AQ"},
{"La Spezia","IT","SP"},
{"Latina","IT","LT"},
{"Lecce","IT","LE"},
{"Lecco","IT","LC"},
{"Livorno","IT","LI"},
{"Lodi","IT","LO"},
{"Lucca","IT","LU"},
{"Macerata","IT","MC"},
{"Mantua","IT","MN"},
{"Massa-Carrara","IT","MS"},
{"Matera","IT","MT"},
{"Medio-Campidano","IT","VS"},
{"Messina","IT","ME"},
{"Milan","IT","MI"},
{"Modena","IT","MO"},
{"Monza and Brianza","IT","MB"},
{"Naples","IT","NA"},
{"Novara","IT","NO"},
{"Nuoro","IT","NU"},
{"Ogliastra","IT","OG"},
{"Olbia-Tempio","IT","OT"},
{"Oristano","IT","OR"},
{"Padua","IT","PD"},
{"Palermo","IT","PA"},
{"Parma","IT","PR"},
{"Pavia","IT","PV"},
{"Perugia","IT","PG"},
{"Pesaro and Urbino","IT","PU"},
{"Pescara","IT","PE"},
{"Piacenza","IT","PC"},
{"Pisa","IT","PI"},
{"Pistoia","IT","PT"},
{"Pordenone","IT","PN"},
{"Potenza","IT","PZ"},
{"Prato","IT","PO"},
{"Ragusa","IT","RG"},
{"Ravenna","IT","RA"},
{"Reggio Calabria","IT","RC"},
{"Reggio Emilia","IT","RE"},
{"Rieti","IT","RI"},
{"Rimini","IT","RN"},
{"Rome","IT","RM"},
{"Rovigo","IT","RO"},
{"Salerno","IT","SA"},
{"Sassari","IT","SS"},
{"Savona","IT","SV"},
{"Siena","IT","SI"},
{"Sondrio","IT","SO"},
{"Syracuse","IT","SR"},
{"Taranto","IT","TA"},
{"Teramo","IT","TE"},
{"Terni","IT","TR"},
{"Trapani","IT","TP"},
{"Trento","IT","TN"},
{"Treviso","IT","TV"},
{"Trieste","IT","TS"},
{"Turin","IT","TO"},
{"Udine","IT","UD"},
{"Varese","IT","VA"},
{"Venice","IT","VE"},
{"Verbano Cusio Ossola","IT","VB"},
{"Vercelli","IT","VC"},
{"Verona","IT","VR"},
{"Vibo Valentia","IT","VV"},
{"Vicenza","IT","VI"},
{"Viterbo","IT","VT"},
{"Saint-Martin","MF","978"},
{"Martinique","MQ","972"},
{"New Caledonia","NC","988"},
{"French Polynesia","PF","987"},
{"Saint Pierre and Miquelon","PM","975"},
{"Aveiro","PT","01"},
{"Azores","PT","20"},
{"Beja","PT","02"},
{"Braga","PT","03"},
{"Braganza","PT","04"},
{"Castelo Branco","PT","05"},
{"Coimbra","PT","06"},
{"\311vora","PT","07"},
{"Faro","PT","08"},
{"Guarda","PT","09"},
{"Leiria","PT","10"},
{"Lisbon","PT","11"},
{"Madeira","PT","30"},
{"Portalegre","PT","12"},
{"Porto","PT","13"},
{"Santar\351m","PT","14"},
{"Set\372bal","PT","15"},
{"Viana do Castelo","PT","16"},
{"Vila Real","PT","17"},
{"Viseu","PT","18"},
{"Reunion","RE","974"},
{"Adygeya, Respublika","RU","AD"},
{"Altay, Respublika","RU","AL"},
{"Altayskiy kray","RU","ALT"},
{"Amurskaya oblast'","RU","AMU"},
{"Arkhangel'skaya oblast'","RU","ARK"},
{"Astrakhanskaya oblast'","RU","AST"},
{"Bashkortostan, Respublika","RU","BA"},
{"Belgorodskaya oblast'","RU","BEL"},
{"Bryanskaya oblast'","RU","BRY"},
{"Buryatiya, Respublika","RU","BU"},
{"Chechenskaya Respublika","RU","CE"},
{"Chelyabinskaya oblast'","RU","CHE"},
{"Chukotskiy avtonomnyy okrug","RU","CHU"},
{"Chuvashskaya Respublika","RU","CU"},
{"Dagestan, Respublika","RU","DA"},
{"Ingushetiya, Respublika","RU","IN"},
{"Irkutskaya oblast'","RU","IRK"},
{"Ivanovskaya oblast'","RU","IVA"},
{"Kabardino-Balkarskaya Respublika","RU","KB"},
{"Kaliningradskaya oblast'","RU","KGD"},
{"Kalmykiya, Respublika","RU","KL"},
{"Kaluzhskaya oblast'","RU","KLU"},
{"Kamchatskiy kray","RU","KAM"},
{"Karachayevo-Cherkesskaya Respublika","RU","KC"},
{"Kareliya, Respublika","RU","KR"},
{"Kemerovskaya oblast'","RU","KEM"},
{"Khabarovskiy kray","RU","KHA"},
{"Khakasiya, Respublika","RU","KK"},
{"Khanty-Mansiyskiy avtonomnyy okrug","RU","KHM"},
{"Kirovskaya oblast'","RU","KIR"},
{"Komi, Respublika","RU","KO"},
{"Kostromskaya oblast'","RU","KOS"},
{"Krasnodarskiy kray","RU","KDA"},
{"Krasnoyarskiy kray","RU","KYA"},
{"Krym, Respublika","RU","KRM"},
{"Kurganskaya oblast'","RU","KGN"},
{"Kurskaya oblast'","RU","KRS"},
{"Leningradskaya oblast'","RU","LEN"},
{"Lipetskaya oblast'","RU","LIP"},
{"Magadanskaya oblast'","RU","MAG"},
{"Mariy El, Respublika","RU","ME"},
{"Mordoviya, Respublika","RU","MO"},
{"Moskovskaya oblast'","RU","MOS"},
{"Moskva","RU","MOW"},
{"Murmanskaya oblast'","RU","MUR"},
{"Nenetskiy avtonomnyy okrug","RU","NEN"},
{"Nizhegorodskaya oblast'","RU","NIZ"},
{"Novgorodskaya oblast'","RU","NGR"},
{"Novosibirskaya oblast'","RU","NVS"},
{"Omskaya oblast'","RU","OMS"},
{"Orenburgskaya oblast'","RU","ORE"},
{"Orlovskaya oblast'","RU","ORL"},
{"Penzenskaya oblast'","RU","PNZ"},
{"Permskiy kray","RU","PER"},
{"Primorskiy kray","RU","PRI"},
{"Pskovskaya oblast'","RU","PSK"},
{"Rostovskaya oblast'","RU","ROS"},
{"Ryazanskaya oblast'","RU","RYA"},
{"Sakha, Respublika","RU","SA"},
{"Sakhalinskaya oblast'","RU","SAK"},
{"Samarskaya oblast'","RU","SAM"},
{"Sankt-Peterburg","RU","SPE"},
{"Saratovskaya oblast'","RU","SAR"},
{"Severnaya Osetiya, Respublika","RU","SE"},
{"Smolenskaya oblast'","RU","SMO"},
{"Stavropol'skiy kray","RU","STA"},
{"Sverdlovskaya oblast'","RU","SVE"},
{"Tambovskaya oblast'","RU","TAM"},
{"Tatarstan, Respublika","RU","TA"},
{"Tomskaya oblast'","RU","TOM"},
{"Tul'skaya oblast'","RU","TUL"},
{"Tverskaya oblast'","RU","TVE"},
{"Tyumenskaya oblast'","RU","TYU"},
{"Tyva, Respublika","RU","TY"},
{"Udmurtskaya Respublika","RU","UD"},
{"Ul'yanovskaya oblast'","RU","ULY"},
{"Vladimirskaya oblast'","RU","VLA"},
{"Volgogradskaya oblast'","RU","VGG"},
{"Vologodskaya oblast'","RU","VLG"},
{"Voronezhskaya oblast'","RU","VOR"},
{"Yamalo-Nenetskiy avtonomnyy okrug","RU","YAN"},
{"Yaroslavskaya oblast'","RU","YAR"},
{"Yevreyskaya avtonomnaya oblast'","RU","YEV"},
{"Zabaykal'skiy kray","RU","ZAB"},
{"French Southern and Antarctic Territories","TF","984"},
{"Avtonomna Respublika Krym","UA","43"},
{"Cherkaska oblast","UA","71"},
{"Chernihivska oblast","UA","74"},
{"Chernivetska oblast","UA","77"},
{"Dnipropetrovska oblast","UA","12"},
{"Donetska oblast","UA","14"},
{"Ivano-Frankivska oblast","UA","26"},
{"Kharkivska oblast","UA","63"},
{"Khersonska oblast","UA","65"},
{"Khmelnytska oblast","UA","68"},
{"Kirovohradska oblast","UA","35"},
{"Kyiv","UA","30"},
{"Kyivska oblast","UA","32"},
{"Luhanska oblast","UA","09"},
{"Lvivska oblast","UA","46"},
{"Mykolaivska oblast","UA","48"},
{"Odeska oblast","UA","51"},
{"Poltavska oblast","UA","53"},
{"Rivnenska oblast","UA","56"},
{"Sevastopol","UA","40"},
{"Sumska oblast","UA","59"},
{"Ternopilska oblast","UA","61"},
{"Vinnytska oblast","UA","05"},
{"Volynska oblast","UA","07"},
{"Zakarpatska oblast","UA","21"},
{"Zaporizka oblast","UA","23"},
{"Zhytomyrska oblast","UA","18"},
{"Alabama","US","AL"},
{"Alaska","US","AK"},
{"Arizona","US","AZ"},
{"Arkansas","US","AR"},
{"Armed Forces AA","US","AA"},
{"Armed Forces AE","US","AE"},
{"Armed Forces AP","US","AP"},
{"California","US","CA"},
{"Colorado","US","CO"},
{"Connecticut","US","CT"},
{"Delaware","US","DE"},
{"District Of Columbia","US","DC"},
{"Florida","US","FL"},
{"Georgia","US","GA"},
{"Hawaii","US","HI"},
{"Idaho","US","ID"},
{"Illinois","US","IL"},
{"Indiana","US","IN"},
{"Iowa","US","IA"},
{"Kansas","US","KS"},
{"Kentucky","US","KY"},
{"Louisiana","US","LA"},
{"Maine","US","ME"},
{"Maryland","US","MD"},
{"Massachusetts","US","MA"},
{"Michigan","US","MI"},
{"Minnesota","US","MN"},
{"Mississippi","US","MS"},
{"Missouri","US","MO"},
{"Montana","US","MT"},
{"Nebraska","US","NE"},
{"Nevada","US","NV"},
{"New Hampshire","US","NH"},
{"New Jersey","US","NJ"},
{"New Mexico","US","NM"},
{"New York","US","NY"},
{"North Carolina","US","NC"},
{"North Dakota","US","ND"},
{"Ohio","US","OH"},
{"Oklahoma","US","OK"},
{"Oregon","US","OR"},
{"Pennsylvania","US","PA"},
{"Rhode Island","US","RI"},
{"South Carolina","US","SC"},
{"South Dakota","US","SD"},
{"Tennessee","US","TN"},
{"Texas","US","TX"},
{"Utah","US","UT"},
{"Vermont","US","VT"},
{"Virginia","US","VA"},
{"Washington","US","WA"},
{"West Virginia","US","WV"},
{"Wisconsin","US","WI"},
{"Wyoming","US","WY"},
{"Wallis and Futuna","WF","986"},
{"Mayotte","YT","976"}