// -----------------------------------------------------------------------
// Do not modify manually! The file has been created by an automated tool.
// Date created: 2011-10-04T13:19:23.155-04:00
// Automation tool: CVS module i18n/regions (file regions.xsl) - v1.27
// Resource file: regions.xml - v1.21
// File encoding: windows-1252
// -----------------------------------------------------------------------
// Entries are ordered by RegionName using 'en' collation
// Format: {RegionName, RegionCode}
{"Agrigento","AG"},
{"Alessandria","AL"},
{"Ancona","AN"},
{"Aosta","AO"},
{"Arezzo","AR"},
{"Ascoli Piceno","AP"},
{"Asti","AT"},
{"Avellino","AV"},
{"Bari","BA"},
{"Barletta-Andria-Trani","BT"},
{"Belluno","BL"},
{"Benevento","BN"},
{"Bergamo","BG"},
{"Biella","BI"},
{"Bologna","BO"},
{"Bolzano","BZ"},
{"Brescia","BS"},
{"Brindisi","BR"},
{"Cagliari","CA"},
{"Caltanissetta","CL"},
{"Campobasso","CB"},
{"Carbonia-Iglesias","CI"},
{"Caserta","CE"},
{"Catania","CT"},
{"Catanzaro","CZ"},
{"Chieti","CH"},
{"Como","CO"},
{"Cosenza","CS"},
{"Cremona","CR"},
{"Crotone","KR"},
{"Cuneo","CN"},
{"Enna","EN"},
{"Fermo","FM"},
{"Ferrara","FE"},
{"Fiume","FM"},
{"Florence","FI"},
{"Foggia","FG"},
{"Forlì","FO"},
{"Forli-Cesena","FC"},
{"Frosinone","FR"},
{"Genoa","GE"},
{"Gorizia","GO"},
{"Grosseto","GR"},
{"Imperia","IM"},
{"Isernia","IS"},
{"L'Aquila","AQ"},
{"La Spezia","SP"},
{"Latina","LT"},
{"Lecce","LE"},
{"Lecco","LC"},
{"Livorno","LI"},
{"Lodi","LO"},
{"Lucca","LU"},
{"Macerata","MC"},
{"Mantua","MN"},
{"Massa-Carrara","MS"},
{"Matera","MT"},
{"Medio-Campidano","VS"},
{"Messina","ME"},
{"Milan","MI"},
{"Modena","MO"},
{"Monza and Brianza","MB"},
{"Naples","NA"},
{"Novara","NO"},
{"Nuoro","NU"},
{"Ogliastra","OG"},
{"Olbia-Tempio","OT"},
{"Oristano","OR"},
{"Padua","PD"},
{"Palermo","PA"},
{"Parma","PR"},
{"Pavia","PV"},
{"Perugia","PG"},
{"Pesaro","PS"},
{"Pesaro and Urbino","PU"},
{"Pescara","PE"},
{"Piacenza","PC"},
{"Pisa","PI"},
{"Pistoia","PT"},
{"Pola","PL"},
{"Pordenone","PN"},
{"Potenza","PZ"},
{"Prato","PO"},
{"Ragusa","RG"},
{"Ravenna","RA"},
{"Reggio Calabria","RC"},
{"Reggio Emilia","RE"},
{"Rieti","RI"},
{"Rimini","RN"},
{"Rome","RM"},
{"Rovigo","RO"},
{"Salerno","SA"},
{"Sassari","SS"},
{"Savona","SV"},
{"Siena","SI"},
{"Sondrio","SO"},
{"Syracuse","SR"},
{"Taranto","TA"},
{"Teramo","TE"},
{"Terni","TR"},
{"Trapani","TP"},
{"Trento","TN"},
{"Treviso","TV"},
{"Trieste","TS"},
{"Turin","TO"},
{"Udine","UD"},
{"Varese","VA"},
{"Venice","VE"},
{"Verbano Cusio Ossola","VB"},
{"Vercelli","VC"},
{"Verona","VR"},
{"Vibo Valentia","VV"},
{"Vicenza","VI"},
{"Viterbo","VT"},
{"Zara","ZA"}