// -------------------------------------------------------------------------------------
// The file has been created by an automated tool.
// It is being maintained in GIT repository "SER/Protocols" as "protocols/statesRU.c".
// Changes to the contents or location of this file in GIT should be communicated
// to its recent maintainer(s) as shown in repository change history.
//
// Date created: 2019-11-12T09:24:42-05:00
// Automation tool: GIT repository ADMIN/i18n (file regions.xsl) - v1.51
// Resource file: regions.xml - v1.43
// This file encoding: windows-1252
// -------------------------------------------------------------------------------------
// Entries are ordered by RegionName using "en"  collation
// Format: {RegionName, RegionCode}
{"Adygeya, Respublika","AD"},
{"Altay, Respublika","AL"},
{"Altayskiy kray","ALT"},
{"Amurskaya oblast'","AMU"},
{"Arkhangel'skaya oblast'","ARK"},
{"Astrakhanskaya oblast'","AST"},
{"Bashkortostan, Respublika","BA"},
{"Belgorodskaya oblast'","BEL"},
{"Bryanskaya oblast'","BRY"},
{"Buryatiya, Respublika","BU"},
{"Chechenskaya Respublika","CE"},
{"Chelyabinskaya oblast'","CHE"},
{"Chukotskiy avtonomnyy okrug","CHU"},
{"Chuvashskaya Respublika","CU"},
{"Dagestan, Respublika","DA"},
{"Ingushetiya, Respublika","IN"},
{"Irkutskaya oblast'","IRK"},
{"Ivanovskaya oblast'","IVA"},
{"Kabardino-Balkarskaya Respublika","KB"},
{"Kaliningradskaya oblast'","KGD"},
{"Kalmykiya, Respublika","KL"},
{"Kaluzhskaya oblast'","KLU"},
{"Kamchatskiy kray","KAM"},
{"Karachayevo-Cherkesskaya Respublika","KC"},
{"Kareliya, Respublika","KR"},
{"Kemerovskaya oblast'","KEM"},
{"Khabarovskiy kray","KHA"},
{"Khakasiya, Respublika","KK"},
{"Khanty-Mansiyskiy avtonomnyy okrug","KHM"},
{"Kirovskaya oblast'","KIR"},
{"Komi, Respublika","KO"},
{"Kostromskaya oblast'","KOS"},
{"Krasnodarskiy kray","KDA"},
{"Krasnoyarskiy kray","KYA"},
{"Krym, Respublika","KRM"},
{"Kurganskaya oblast'","KGN"},
{"Kurskaya oblast'","KRS"},
{"Leningradskaya oblast'","LEN"},
{"Lipetskaya oblast'","LIP"},
{"Magadanskaya oblast'","MAG"},
{"Mariy El, Respublika","ME"},
{"Mordoviya, Respublika","MO"},
{"Moskovskaya oblast'","MOS"},
{"Moskva","MOW"},
{"Murmanskaya oblast'","MUR"},
{"Nenetskiy avtonomnyy okrug","NEN"},
{"Nizhegorodskaya oblast'","NIZ"},
{"Novgorodskaya oblast'","NGR"},
{"Novosibirskaya oblast'","NVS"},
{"Omskaya oblast'","OMS"},
{"Orenburgskaya oblast'","ORE"},
{"Orlovskaya oblast'","ORL"},
{"Penzenskaya oblast'","PNZ"},
{"Permskiy kray","PER"},
{"Primorskiy kray","PRI"},
{"Pskovskaya oblast'","PSK"},
{"Rostovskaya oblast'","ROS"},
{"Ryazanskaya oblast'","RYA"},
{"Sakha, Respublika","SA"},
{"Sakhalinskaya oblast'","SAK"},
{"Samarskaya oblast'","SAM"},
{"Sankt-Peterburg","SPE"},
{"Saratovskaya oblast'","SAR"},
{"Severnaya Osetiya, Respublika","SE"},
{"Smolenskaya oblast'","SMO"},
{"Stavropol'skiy kray","STA"},
{"Sverdlovskaya oblast'","SVE"},
{"Tambovskaya oblast'","TAM"},
{"Tatarstan, Respublika","TA"},
{"Tomskaya oblast'","TOM"},
{"Tul'skaya oblast'","TUL"},
{"Tverskaya oblast'","TVE"},
{"Tyumenskaya oblast'","TYU"},
{"Tyva, Respublika","TY"},
{"Udmurtskaya Respublika","UD"},
{"Ul'yanovskaya oblast'","ULY"},
{"Vladimirskaya oblast'","VLA"},
{"Volgogradskaya oblast'","VGG"},
{"Vologodskaya oblast'","VLG"},
{"Voronezhskaya oblast'","VOR"},
{"Yamalo-Nenetskiy avtonomnyy okrug","YAN"},
{"Yaroslavskaya oblast'","YAR"},
{"Yevreyskaya avtonomnaya oblast'","YEV"},
{"Zabaykal'skiy kray","ZAB"}