// protocols/tracemarkers.h
#ifndef protocols_tracemarkers_h_included
#define protocols_tracemarkers_h_included

// the initial content was MOVED to this dedicated file after BUILD1021

// LOG MARKERS: check log for "{_MARKER_" for incoming and ">_MARKER_" for outgoing messages
#define LOG_TRACE_CLIENT				"C"
#define LOG_TRACE_CLIENT_UNAUTH			"CU"
#define LOG_TRACE_CLIENT_DOCS			"Cd"
#define LOG_TRACE_CLIENT_GEOIP			"GEOIP"
#define LOG_TRACE_CORE					"COR"
#define LOG_TRACE_ADMIN					"A"
#define LOG_TRACE_ADMIN_WEBTOKEN		"AWT"
#define LOG_TRACE_ADMIN_WEBTOKEN_NULL   "AWTN"
#define LOG_TRACE_AUTOMATION			"AM"
#define LOG_TRACE_WEB_CLIENT			"WC"
#define LOG_TRACE_WEB_ACCOUNT_SERVICE	"WAS"	// PYR-32120
#define LOG_TRACE_RATIONAL_WEB_SERVICES	"RWS"	// PYR-33416
#define LOG_TRACE_PULL_WEB_NOTIFICATIONS "PL" // PYR-37887
#define LOG_TRACE_PUSH_WEB_NOTIFICATIONS "PH" // PYR-37887
#define LOG_TRACE_REGULATOR_FTP_MIGRATE  "FTPM" // PYR-40997
#define LOG_TRACE_WEB_CHECK_STATUS		"WCS"	// PYR-37900
#define LOG_TRACE_CLIENT_OR_CIPWA_WEB	"CLCW"  // PYR-45659
#define LOG_TRACE_CLIENT_EXTERN_OP		"CExO"	//	PYR-52518
#define LOG_TRACE_CLIENT_EXTERN_OP_WEB	"CExOW"	//	PYR-65464
#define LOG_TRACE_CLIENT_EXTERN_OP_TOKEN_WEB "CExOTW"	//	PYR-65464
#define LOG_TRACE_CLIENT_EXTERN_OP_SWISS "CExOSws"		//	PYR-89580

#define LOG_TRACE_BAN_PROXY				"Bp"
#define LOG_TRACE_BANS					"B"
#define LOG_TRACE_RO_BANS				"B2"
#define LOG_TRACE_CASHIER				"CA"
#define LOG_TRACE_CRYPTO				"CR"
#define LOG_TRACE_CDMS					"CD"
#define LOG_TRACE_CDMSRO				"CD2"
#define LOG_TRACE_CDMS_SERVER			"CDs"
#define LOG_TRACE_CRM					"CRM"
#define LOG_TRACE_CRM2					"CRM2"
#define LOG_TRACE_CRMDBM				"CDB"
#define LOG_TRACE_CRMDBM2				"CDB2"
#define LOG_TRACE_CRMDBMFPPBUNDLESRO	"CFR"
#define LOG_TRACE_CRMDBMFPPBUNDLESRW	"CFW"
#define LOG_TRACE_COMPLIANCE_DBM       	"CmpD"
#define LOG_TRACE_COMPLIANCE_DBM2       "CmpD2"
#define LOG_TRACE_COMPLIANCE_PG_DBM		"CmpPgD"
#define LOG_TRACE_COMPLIANCE_PG_DBM2	"CmpPgD2"
#define LOG_TRACE_DRC					"DR"
#define LOG_TRACE_DRC2					"DR2"
#define LOG_TRACE_WEBTOKENSRV			"WT"
#define LOG_TRACE_DBM					"D"
#define LOG_TRACE_DBM2					"D2"
#define LOG_TRACE_GCDBM					"GD"
#define LOG_TRACE_OLAP					"OP"
#define LOG_TRACE_OLAP_USER_DETAILS		"OPD"
#define LOG_TRACE_OLAP_HANDS_DATA		"OHD"
#define LOG_TRACE_OLAP_ARCH_HANDS_DATA	"OAD"
#define LOG_TRACE_OLAP_SLOWREQUESTS     "OSR" // PYR-52669
#define LOG_TRACE_ARJEL_DATAFEED		"ADF"
#define LOG_TRACE_LOBBY					"L"
#define LOG_TRACE_LOBBYETC				"LE"
#define LOG_TRACE_LDBM					"LD"
#define LOG_TRACE_LDBM_RO				"LD2"
#define LOG_TRACE_IMAGE_DBM				"IM"
#define LOG_TRACE_AUTH					"AU"
#define LOG_TRACE_TEMPLATES				"TS"
#define LOG_TRACE_VIP					"VP"
#define LOG_TRACE_REGULATOR				"r"
#define LOG_TRACE_EMAIL					"EM"
#define LOG_TRACE_EMAIL2				"E2"
#define LOG_TRACE_COLLUSION				"CLU"
#define	LOG_TRACE_GEOCOMPLY_GTW			"Geo"
#define LOG_TRACE_ARIST_AGE				"ARg"
#define LOG_TRACE_AMSDBM				"AmsD"
#define LOG_TRACE_CAPSCAN				"CS"
#define LOG_TRACE_WEB_SERVICES			"WSs"
#define LOG_TRACE_URU_AGE				"UR"
#define LOG_TRACE_WEB_SERVICES_UNAUTH	"WSu"

#define LOG_TRACE_ARJEL_BLACKLIST		"ABl"
#define LOG_TRACE_ESTONIA_GATEWAY		"EG"	
#define LOG_TRACE_AAMS_GATEWAY			"IT"
#define LOG_TRACE_EPIS_GATEWAY			"BE"
#define LOG_TRACE_BENG_GATEWAY			"BENG"
#define LOG_TRACE_SPAIN_GATEWAY			"ES"
#define LOG_TRACE_SPAIN_REPLICATOR		"ESR"
#define LOG_TRACE_ASIA_REPLICATOR		"ASR"
#define LOG_TRACE_DANISH_GATEWAY		"DK"
#define LOG_TRACE_DANISH_REPLICATOR		"DKR"
#define LOG_TRACE_DANISH_UTILPOSTGRES	"DKPg" // PYR-124995
#define LOG_TRACE_DAEMON				"DMN"
#define LOG_TRACE_TEMPLATE_CACHE		"TC"
#define LOG_TRACE_FULLTILT_GATEWAY		"FT"
#define LOG_TRACE_AMS_CLIENT			"AmsC"
#define LOG_TRACE_JOBS_CONTROLLER       "JC"
#define LOG_TRACE_SRIJ_GATEWAY          "SR"  // PYR-37383
#define LOG_TRACE_UA_GATEWAY			"UA"  // PYR-42193
#define LOG_TRACE_SV_GATEWAY			"SV"  // PYR-49972
#define LOG_TRACE_SEBANKID_GATEWAY      "SE" // PYR-78110

#define LOG_TRACE_TIMER					"TM"
#define LOG_TRACE_SERVER_STATUS			"St"	// PYR-26980

#define LOG_TRACE_ICE_SERVER_PROXY		"ISX"
#define LOG_TRACE_ICE_CLIENT_PROXY		"ICX"
#define LOG_TRACE_ICE_LOBBY				"IL"
#define LOG_TRACE_ICE_DBM				"IDB"
#define LOG_TRACE_ICE_DBM2				"IDB2"
#define LOG_TRACE_ICE_DBM2S				"IDB2S"
#define LOG_TRACE_ICE_LEADERBOARD		"ILB"
#define LOG_TRACE_ICE_LEADERBOARD_WEB	"ILBW"

#define LOG_TRACE_XC_CASINO				"XC"
#define LOG_TRACE_GCAUTOIMPORT			"AI"

#define LOG_TRACE_APPFACTORY			"AF"
#define LOG_TRACE_SEAT_FINDER			"Sfn"
#define LOG_TRACE_CVL_CONTROL			"Cvl" // PYR-50736
#define LOG_TRACE_SAGSTARTER			"SaG"
#define LOG_TRACE_SNGSTARTER			"SnG"
#define LOG_TRACE_STORMLOBBY			"SLb"
#define LOG_TRACE_PPPSTARTER			"PPP"
#define LOG_TRACE_PPPDBM				"PPPD"
#define LOG_TRACE_TGM					"TGM"
#define LOG_TRACE_INTELLIPOKER			"IntP"
#define LOG_TRACE_JUMIOGATEWAY			"Jum"
#define LOG_TRACE_VOICELOBBY			"VL"
#define LOG_TRACE_MONET					"Mnt"
#define LOG_TRACE_DALI					"Dali" // PYR-47523
#define LOG_TRACE_SHADOW				"Sh"
#define LOG_TRACE_NEWS					"Nw"
#define LOG_TRACE_CAPTCHA				"Cha"
#define LOG_TRACE_TABLE					"Tbl"
#define LOG_TRACE_MTLOBBY				"MTL"
#define LOG_TRACE_BLITZLOBBY			"BL"
#define LOG_TRACE_CHAT					"Ch"
#define LOG_TRACE_CHATMONITOR			"ChM"
#define LOG_TRACE_HOMEGAME				"HG"
#define LOG_TRACE_REPLYTABLE			"RT"
#define LOG_TRACE_GAMECONTROL			"GC"
#define LOG_TRACE_BLOBDBM				"BD"
#define LOG_TRACE_CESAR					"Cs"
#define LOG_TRACE_ACM					"ACM"
#define LOG_TRACE_IDCGATEWAY			"IDC"
#define LOG_TRACE_RO_STAT_DBM           "SO"

#define LOG_TRACE_SPORTSBOOK			"SP"  // PYR-33233
#define LOG_TRACE_SPORTSBOOKDBM			"SB"  // PYR-35011
#define LOG_TRACE_DFSUS					"DfsU" // PYR-36465, PYR-48971
#define LOG_TRACE_DFSINTL				"DfsI" // PYR-36465, PYR-48971
#define LOG_TRACE_POOLBETTING			"PB"  // PYR-42410
#define LOG_TRACE_PREDICTOR				"PR"  // PYR-63110

// PYR-32351
#define LOG_TRACE_TABLEDBM_GT			"Z"
#define LOG_TRACE_SPORTSBOOK_GT			"ZS"
#define LOG_TRACE_DFSINTL_GT			"ZD" // PYR-40346, PYR-48971
#define LOG_TRACE_POOLBETTING_GT		"ZP" // PYR-42410

#define LOG_TRACE_ENTROPY				"EN"
#define LOG_TRACE_FPP_BUNDLES			"F" // PYR-32027

// PYR-36002
#define LOG_TRACE_ARJEL 				"Aj"
#define LOG_TRACE_MARKETDBM				"Md"

// PYR-36169
#define LOG_TRACE_AUX_HANDHISTORY		"AHH"

#define LOG_TRACE_DESHGW 				"Dgw"
#define LOG_TRACE_PTGW 					"PTgw"
#define LOG_TRACE_BGGW 					"BGgw"
#define LOG_TRACE_CZECH_GATEWAY         "CZgw" // financial gateway
#define LOG_TRACE_AG_GATEWAY			"AGgw"

#define LOG_TRACE_FR_REPLICATOR		    "FRR"

#define LOG_TRACE_APAL_SERVER			"RIO" // PYR-37587
#define LOG_TRACE_MLV_SERVER			"MLV" // PYR-43027
// PYR-38585
#define LOG_TRACE_LOGINDBM				"G"
#define LOG_TRACE_DBM_AUTOMATION		"a" // Automation connection to dbm to distinguish from connection to Cashier
#define LOG_TRACE_AUTOMATIONSTAR		"sc" // Automation Star Code instance
// PYR-39368
#define LOG_TRACE_DBM_AUTH				"Q"
#define LOG_TRACE_DBM_GAMEINTEGRITY				"N"
#define LOG_TRACE_LIMITCONTROLLER		"l"

#define LOG_TRACE_TABLE_DBM             "TD"

// PYR-41278
#define LOG_TRACE_USERPROPERTY          "UP"

// PYR-38484
#define LOG_TRACE_IP2COUNTRY			"IP2C"

// PYR-41099
#define LOG_TRACE_SECSERVER				"SEC"
#define LOG_TRACE_RAM_CONTROL_SERVER	"RCS"

// PYR-40428
#define LOG_TRACE_MGLOBBY					"MG"

// PYR-46309
#define LOG_TRACE_WAGERMEAS_SERVER			"WGM"

// PYR-31663
#define LOG_TRACE_PLAYRECORDER_SERVER		"PRS"

// PYR-49256
#define LOG_TRACE_ETC_DBM				"EDB"
#define LOG_TRACE_ETC_DBM2				"EDB2"

#define LOG_TRACE_OLTP_GT				"GT" // request to RW OLTP over guaranteed transaction connection
#define LOG_TRACE_STATUS_REPORTER		"SRp" // PYR-51381

// PYR-52524
#define LOG_TRACE_GLOBALPUBLISHER			"GP"

// PYR-56207
// Not frequent usage
#define LOG_TRACE_OPTS_MADE_BY_USER		"OptsMadeByUser"

// PYR-60134
#define LOG_TRACE_CONVERTER				"CNV"

// PYR-64085
#define LOG_TRACE_ASIACDD				"ACDD"


// PYR-50999
#define LOG_TRACE_GAMSTOPUKGATEWAY		"GSTP"

// PYR-61693 (PYR-66899)
#define LOG_TRACE_PSERVER				"PS"

// PYR-72484
#define LOG_TRACE_IHHR					"IHHR"

// PYR-75625
#define LOG_TRACE_ASIAPORTALPROXY		"APP"
#define LOG_TRACE_ASIAPORTALDBM			"APD"
#define LOG_TRACE_AUXDBMRO				"ADO"

// PYR-82385
#define LOG_TRACE_SWEDISHBANCHECKGATEWAY "SEBL"

// PYR-81917
#define LOG_TRACE_COLOSSUS_CDH			"CDH"
#define LOG_TRACE_COLOSSUS_UTL			"CUTL"

// PYR-92626
#define LOG_TRACE_COLOSSUS_CCDA			"CCDA"

// PYR-80164
#define LOG_TRACE_WORKER_LDBM_RW		"WLDBM"
#define LOG_TRACE_WORKER_LDBM_RO		"WLDBMRO"
#define LOG_TRACE_ARCH_MANAGER			"ARCHMAN"
#define LOG_TRACE_ARCHDBM_RW			"ARCHDBM"
#define LOG_TRACE_ARCHDBM_RO			"ARCHDBMRO"
#define LOG_TRACE_GDPRARCHDBM_RW		"ARCHDBMGd"
#define LOG_TRACE_GDPRARCHDBM_RO		"ARCHDBMROGd"

// PYR-83394
#define LOG_TRACE_CSI					"CSI"

// PYR-80333
#define LOG_TRACE_ADMIN_BROKER			"ABADM"

// PYR-85611
#define LOG_TRACE_DBD                   "DBD"

// PYR-77583
#define LOG_TRACE_SOCIALCASINO			"SOC"
#define LOG_TRACE_SOCIALCASINODBM		"SOCDBM"

// PYR-84866
#define LOG_TRACE_DEGASAGGREGATOR		"DGA"

// PYR-81644
#define LOG_TRACE_STARSSTORE_GT			"SGt"
#define LOG_TRACE_STARSSTORE			"Ss"

//	PYR-89580, PYR-90603
#define LOG_TRACE_SWISS_GATEWAY			"SwsGw"

#define LOG_TRACE_UTIL_CRMDBM			"UCrm" // PYR-96224

// PYR-91513
#define LOG_TRACE_CZGW					"CZcgw" // coregateway

#define LOG_TRACE_STARS_CRM				"SCRM" // PYR-101245
// PYR-108724
#define LOG_TRACE_TWITCH_GATEWAY		"TWG"

#define LOG_TRACE_GAME_INT				"GI"	// GPSI-74

#define LOG_TRACE_HUBFEED				"HF"	// PYR-124676
#define LOG_TRACE_HUBFEED_DBM			"HFDB"	// PYR-124676
#define LOG_TRACE_HUBFEED_RODBM			"HFDB2"	// PYR-124676

#define LOG_TRACE_REPA					"REPA" // PYR-123767

#define LOG_TRACE_POKER_DOJO			"PkDj"		//	PYR-126838

// PYR-51017
#define CONN_READABLE_NAME_ARJEL			"Arjel"
#define CONN_READABLE_NAME_AUTH             "Auth"
#define CONN_READABLE_NAME_BLOBDBM          "BlobDBM"
#define CONN_READABLE_NAME_COMPLIANCEDBM	"ComplianceDBM"
#define CONN_READABLE_NAME_COMPLIANCEDBM2	"ComplianceDBMRO"
#define CONN_READABLE_NAME_COMPLIANCEPGDBM	"CompliancePgDBM"
#define CONN_READABLE_NAME_COMPLIANCEPGDBM2	"CompliancePgDBMRO"
#define CONN_READABLE_NAME_CRYPTO			"Crypto"
#define CONN_READABLE_NAME_CRM				"CRM"
#define CONN_READABLE_NAME_CRMDBM			"CRMDBM"
#define CONN_READABLE_NAME_DANISHGATEWAY	"DanishGateway"
#define CONN_READABLE_NAME_DBM				"OLTP"
#define CONN_READABLE_NAME_DBM2				"OLTPRO"
#define CONN_READABLE_NAME_DESHGATEWAY		"DeshGateway"
#define CONN_READABLE_NAME_DRC              "DRC"
#define CONN_READABLE_NAME_DRC2             "DRC2"
#define CONN_READABLE_NAME_EMAIL			"Email"
#define CONN_READABLE_NAME_ENTROPY			"Entropy"
#define CONN_READABLE_NAME_GCDBM			"GcDBM"
#define CONN_READABLE_NAME_GLOBALPUBLISHER	"GlobalPublisher"
#define CONN_READABLE_NAME_ITACCTGATEWAY	"ItAcctGateway"
#define CONN_READABLE_NAME_LOBBY            "Lobby"
#define CONN_READABLE_NAME_LOBBYETC         "LobbyETC"
#define CONN_READABLE_NAME_LOGINDBM			"LoginDBM"
#define CONN_READABLE_NAME_MARKETDBM		"MarketDBM"
#define CONN_READABLE_NAME_MGLOBBY          "MGLobby"
#define CONN_READABLE_NAME_OLAP				"OLAP"
#define CONN_READABLE_NAME_SPAINGATEWAY		"SpainGateway"
#define CONN_READABLE_NAME_SPORTSBOOK       "SportsBook"
#define CONN_READABLE_NAME_SPORTSBOOKOLAP	"SportsbookOLAP"
#define CONN_READABLE_NAME_STATDBM			"StatDBMRW"
#define CONN_READABLE_NAME_STATDBM2			"StatDBMRO"
#define CONN_READABLE_NAME_TABLEDBM         "TableDBM"
#define CONN_READABLE_NAME_TEMPLATES		"TemplateServer"
#define CONN_READABLE_NAME_UPSERVER         "UPServer"
#define CONN_READABLE_NAME_WEBTOKENSERVER   "WebTokenServer"
#define CONN_READABLE_NAME_STATUSREPORTER   "StatusReporter"
#define CONN_READABLE_NAME_CONVERTER		"Converter" // PYR-60134
#define CONN_READABLE_NAME_STATSBLOBDBM		"StatsBlobDBMRW"
#define CONN_READABLE_NAME_STATSBLOBDBM2	"StatsBlobDBMRO"
#define CONN_READABLE_NAME_ASIAPORTALDBM	"AsiaPortalDBM" // PYR-75625
#define CONN_READABLE_NAME_AUXDBMRO			"AuxDBMRO"      // PYR-75625
#define CONN_READABLE_NAME_DEGASAGGREGATOR	"DegasAggregator" // PYR-84866
#define CONN_READABLE_NAME_SWISSGATEWAY		"SwissGateway" // PYR-88255

#endif // protocols_tracemarkers_h_included
