/**
 * converter_atf.h
 *
 * This file was auto-generated from converter_atf.txt by ATF protocol generator. 
 * Do not edit this file directly!
 *
 * Generator used the following keys: converter_atf.txt
 */

#ifndef ATF_PROTOCOL_DEFFILE_CONVERTER_ATF_H
#define ATF_PROTOCOL_DEFFILE_CONVERTER_ATF_H

#include "converter.h"
#include "pyrtime.h"


#include "UserDefStructs.h"

namespace converter
{
	class ProtocolFactory
	{
	public:
		static Atf::MessageProtocol* createMessageProtocolObject(const char *_nameSpace, UINT32 _msgId);
		static bool validateProtocolMessageFromJSONString(const char *_nameSpace, UINT32 _msgId, const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsNotParseEnded);
		static bool validateProtocolMessage(const char *_nameSpace, UINT32 _msgId, CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsNotParseEnded);
	};


	struct CountryCurrency
	{
		// M(ss) - M(countryCode,localCurrencyIsoCode)
		PString countryCode;
		PString localCurrencyIsoCode;

		CountryCurrency();
		void clear();
		bool equals(const CountryCurrency&) const;
		const char *toTraceString(PString& _str) const;
		const char *toXmlString(const char *_element, PString& _str) const;
		bool fromXmlString(const PString& _str);
		void composeMsg(CommMsgBody& _msg, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const;
		void parseMsg(CommMsgParser& _parser);
		const char *toJSONString(PString& _str) const;
		void fromJSONString(const PString& _str);
		static void validateJSONString(const PString& _str, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);

		// @Override
		CountryCurrency(PString code, PString isoCode);
	};

	struct CurrencyConvertRate
	{
		// M(s4) - M(currency,rate)
		PString currency;
		INT32 rate;

		CurrencyConvertRate();
		void clear();
		bool equals(const CurrencyConvertRate&) const;
		const char *toTraceString(PString& _str) const;
		const char *toXmlString(const char *_element, PString& _str) const;
		bool fromXmlString(const PString& _str);
		void composeMsg(CommMsgBody& _msg, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const;
		void parseMsg(CommMsgParser& _parser);
		const char *toJSONString(PString& _str) const;
		void fromJSONString(const PString& _str);
		static void validateJSONString(const PString& _str, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
	};

	struct Protocol_MSG_CONVERTER_GET_ALL_RATES : public Atf::MessageProtocol	//101
	{
		// t - time
		SrvTime time;

		Protocol_MSG_CONVERTER_GET_ALL_RATES();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_GET_ALL_RATES&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_GET_ALL_RATES; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_GET_ALL_RATES"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};

	struct Protocol_MSG_CONVERTER_GET_ALL_RATES_REPLY : public Atf::MessageProtocol	//102
	{
		// 2[s|4<M(s4)>] - errCode[errorDescription|numRates<M(currency,rate)>]
		INT16 errCode;

		PString errorDescription;

		Atf::LAtfVector< CurrencyConvertRate, 4 > rates;

		Protocol_MSG_CONVERTER_GET_ALL_RATES_REPLY();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_GET_ALL_RATES_REPLY&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_GET_ALL_RATES_REPLY; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_GET_ALL_RATES_REPLY"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};

	struct Protocol_MSG_CONVERTER_GET_RATE : public Atf::MessageProtocol	//103
	{
		// ts - time,currency
		SrvTime time;
		PString currency;

		Protocol_MSG_CONVERTER_GET_RATE();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_GET_RATE&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_GET_RATE; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_GET_RATE"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};
	struct Protocol_MSG_CONVERTER_GET_RATE_REPLY : public Atf::MessageProtocol	//104
	{
		// 2[s|4] - errCode[errorDescription|rate]
		INT16 errCode;

		PString errorDescription;

		INT32 rate;

		Protocol_MSG_CONVERTER_GET_RATE_REPLY();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_GET_RATE_REPLY&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_GET_RATE_REPLY; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_GET_RATE_REPLY"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};

	struct Protocol_MSG_CONVERTER_CONVERT_AMOUNT : public Atf::MessageProtocol	//105
	{
		// t8ssbb - time,srcCurrencyAmount,srcCurrencyType,destCurrencyType,applyRounding,roundUp
		SrvTime time;
		INT64 srcCurrencyAmount;
		PString srcCurrencyType;
		PString destCurrencyType;
		bool applyRounding;
		bool roundUp;

		Protocol_MSG_CONVERTER_CONVERT_AMOUNT();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_CONVERT_AMOUNT&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_CONVERT_AMOUNT; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_CONVERT_AMOUNT"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};
	struct Protocol_MSG_CONVERTER_CONVERT_AMOUNT_REPLY : public Atf::MessageProtocol	//106
	{
		// 2[s|88] - errCode[errorDescription|destAmount,rate]
		INT16 errCode;

		PString errorDescription;

		INT64 destAmount;
		INT64 rate;

		Protocol_MSG_CONVERTER_CONVERT_AMOUNT_REPLY();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_CONVERT_AMOUNT_REPLY&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_CONVERT_AMOUNT_REPLY; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_CONVERT_AMOUNT_REPLY"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};

	struct CurrencyConvertBatchRequest
	{
		// M(8ss) - M(srcCurrencyAmount,srcCurrencyType,destCurrencyType)
		INT64 srcCurrencyAmount;
		PString srcCurrencyType;
		PString destCurrencyType;

		CurrencyConvertBatchRequest();
		void clear();
		bool equals(const CurrencyConvertBatchRequest&) const;
		const char *toTraceString(PString& _str) const;
		const char *toXmlString(const char *_element, PString& _str) const;
		bool fromXmlString(const PString& _str);
		void composeMsg(CommMsgBody& _msg, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const;
		void parseMsg(CommMsgParser& _parser);
		const char *toJSONString(PString& _str) const;
		void fromJSONString(const PString& _str);
		static void validateJSONString(const PString& _str, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
	};

	struct Protocol_MSG_CONVERTER_CONVERT_BATCH_AMOUNTS : public Atf::MessageProtocol	//107
	{
		// tbb4<M(8ss)> - time,applyRounding,roundUp,numConvertRequests<M(srcCurrencyAmount,srcCurrencyType,destCurrencyType)>
		SrvTime time;
		bool applyRounding;
		bool roundUp;
		Atf::LAtfVector< CurrencyConvertBatchRequest, 4 > convertRequests;

		Protocol_MSG_CONVERTER_CONVERT_BATCH_AMOUNTS();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_CONVERT_BATCH_AMOUNTS&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_CONVERT_BATCH_AMOUNTS; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_CONVERT_BATCH_AMOUNTS"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};

	struct CurrencyConvertBatchReply
	{
		// M(2[s|88]) - M(errCode[errorDescription|destAmount,rate])
		INT16 errCode;

		PString errorDescription;

		INT64 destAmount;
		INT64 rate;

		CurrencyConvertBatchReply();
		void clear();
		bool equals(const CurrencyConvertBatchReply&) const;
		const char *toTraceString(PString& _str) const;
		const char *toXmlString(const char *_element, PString& _str) const;
		bool fromXmlString(const PString& _str);
		void composeMsg(CommMsgBody& _msg, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const;
		void parseMsg(CommMsgParser& _parser);
		const char *toJSONString(PString& _str) const;
		void fromJSONString(const PString& _str);
		static void validateJSONString(const PString& _str, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
	};

	struct Protocol_MSG_CONVERTER_CONVERT_BATCH_AMOUNTS_REPLY : public Atf::MessageProtocol	//108
	{
		// 2[s|4<M(2[s|88])>] - errCode[errorDescription|numConversionResults<M(errCode[errorDescription|destAmount,rate])>]
		INT16 errCode;

		PString errorDescription;

		Atf::LAtfVector< CurrencyConvertBatchReply, 4 > conversionResults;

		Protocol_MSG_CONVERTER_CONVERT_BATCH_AMOUNTS_REPLY();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_CONVERT_BATCH_AMOUNTS_REPLY&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_CONVERT_BATCH_AMOUNTS_REPLY; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_CONVERT_BATCH_AMOUNTS_REPLY"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};

	struct Protocol_MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS : public Atf::MessageProtocol	//109
	{
		// t - time
		SrvTime time;

		Protocol_MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};

	struct CurrencyConvertData
	{
		// M(84<8>4<M(s4)>) - M(roundingFactorsCommonRatio,numRoundingFactors<roundingFactors>,numRates<M(currency,rate)>)
		INT64 roundingFactorsCommonRatio;
		Atf::LAtfVector< INT64, 4 > roundingFactors;
		Atf::LAtfVector< CurrencyConvertRate, 4 > rates;

		CurrencyConvertData();
		void clear();
		bool equals(const CurrencyConvertData&) const;
		const char *toTraceString(PString& _str) const;
		const char *toXmlString(const char *_element, PString& _str) const;
		bool fromXmlString(const PString& _str);
		void composeMsg(CommMsgBody& _msg, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const;
		void parseMsg(CommMsgParser& _parser);
		const char *toJSONString(PString& _str) const;
		void fromJSONString(const PString& _str);
		static void validateJSONString(const PString& _str, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
	};

	struct Protocol_MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS_REPLY : public Atf::MessageProtocol	//110
	{
		// 2[s|M(84<8>4<M(s4)>)] - errCode[errorDescription|M(roundingFactorsCommonRatio,numRoundingFactors<roundingFactors>,numRates<M(currency,rate)>)]
		INT16 errCode;

		PString errorDescription;

		CurrencyConvertData payload;

		Protocol_MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS_REPLY();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS_REPLY&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS_REPLY; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_GET_DATA_FOR_CLIENT_CONVERSIONS_REPLY"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};

	struct Protocol_MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE : public Atf::MessageProtocol	//111
	{
		// t8ssbb - time,srcCurrencyAmount,srcCurrencyType,destCountryCode,applyRounding,roundUp
		SrvTime time;
		INT64 srcCurrencyAmount;
		PString srcCurrencyType;
		PString destCountryCode;
		bool applyRounding;
		bool roundUp;

		Protocol_MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};
	struct Protocol_MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE_REPLY : public Atf::MessageProtocol	//112
	{
		// 2[s|8s8] - errCode[errorDescription|destAmount,destCurrencyType,rate]
		INT16 errCode;

		PString errorDescription;

		INT64 destAmount;
		PString destCurrencyType;
		INT64 rate;

		Protocol_MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE_REPLY();
		void clear() override;
		bool equals(const Protocol_MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE_REPLY&) const;
		bool equals(Atf::MessageProtocol* _other) const override;
		const char *asXmlString(PString& _buf, bool _logTimeStamp) const override;
		const char *asXmlString(PString& _buf, UINT64 _timestampTicks, UINT32 _msgTime) const override;
		bool loadFromXmlString(const PString& _xmlString) override;
		const char *asTraceString(PString& _buf) const override;
		void parseMsg(CommMsgParser& _parser) override;
		void composeMsg(CommMsgBody& _body, bool _ignoreJSON = COMPOSEMSG_IGNORE_JSON_DEFAULT) const override;
		UINT32 getMsgId() const override { return MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE_REPLY; }
		const char *getMsgIdString() const override { return "MSG_CONVERTER_CONVERT_AMOUNT_BY_COUNTRY_CODE_REPLY"; }
		const char *asJSONString(PString& _buf) const override;
		void loadFromJSONString(const PString& _jsonString) override;
		static void validateJSONString(const PString& _jsonString, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);
	};
};

#endif
