/**
 * personalization_atf_thin.cpp
 *
 * This file was auto-generated from personalization_atf.txt by ATF protocol generator. 
 * Do not edit this file directly!
 *
 * Generator used the following keys: -genMoveConstructor -thin personalization_atf.txt
 */
 
#include "personalization_atf_thin.h"

//=================================================================
//                    TournTicketInfo
//=================================================================

PersonalizationATF::cli::TournTicketInfo::TournTicketInfo()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::TournTicketInfo::TournTicketInfo(TournTicketInfo&& _o)
	: ticketId(std::move(_o.ticketId))
	, ticketName(std::move(_o.ticketName))
	, multiTourn(std::move(_o.multiTourn))
	, price(std::move(_o.price))
	, currency(std::move(_o.currency))
	, issued(std::move(_o.issued))
	, expireAt(std::move(_o.expireAt))
	, tournNumber(std::move(_o.tournNumber))
{
}

PersonalizationATF::cli::TournTicketInfo& PersonalizationATF::cli::TournTicketInfo::operator=(TournTicketInfo&& _o)
{
	if(this != &_o)
	{
		ticketId = std::move(_o.ticketId);
		ticketName = std::move(_o.ticketName);
		multiTourn = std::move(_o.multiTourn);
		price = std::move(_o.price);
		currency = std::move(_o.currency);
		issued = std::move(_o.issued);
		expireAt = std::move(_o.expireAt);
		tournNumber = std::move(_o.tournNumber);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::TournTicketInfo::clear()
{
	ticketId = 0;
	ticketName.clear();
	multiTourn = false;
	price = 0;
	currency.clear();
	issued.setNull();
	expireAt.setNull();
	tournNumber = 0;
}

bool PersonalizationATF::cli::TournTicketInfo::equals(const TournTicketInfo& _o) const
{
	return ticketId == _o.ticketId &&
		ticketName.equals(_o.ticketName) &&
		multiTourn == _o.multiTourn &&
		price == _o.price &&
		currency.equals(_o.currency) &&
		issued.equals(_o.issued) &&
		expireAt.equals(_o.expireAt) &&
		tournNumber == _o.tournNumber;
}

const char *PersonalizationATF::cli::TournTicketInfo::toTraceString(PString& _buf) const
{
	_buf.append('{');
	_buf.append("ticketId=");
	_buf.appendUint(ticketId);
	_buf.append(',');
	_buf.append("ticketName=");
	_buf.append(ticketName);
	_buf.append(',');
	_buf.append("multiTourn=");
	_buf.appendUint(multiTourn);
	_buf.append(',');
	_buf.append("price=");
	_buf.appendUint(price);
	_buf.append(',');
	_buf.append("currency=");
	_buf.append(currency);
	_buf.append(',');
	_buf.append("issued=");
	ThinAtf::AtfTempl<SrvTime>::ToTraceString(_buf, issued);
	_buf.append(',');
	_buf.append("expireAt=");
	ThinAtf::AtfTempl<SrvTime>::ToTraceString(_buf, expireAt);
	_buf.append(',');
	_buf.append("tournNumber=");
	_buf.appendInt(tournNumber);
	_buf.append('}');
	return _buf.c_str();
}

void PersonalizationATF::cli::TournTicketInfo::composeMsg(CommMsgBody& _msg) const
{
	CommMsgBody _body;
	//if (!equals(TournTicketInfo())) // not empty
	{
		_body.composeUINT32(ticketId);
		_body.composeString(ticketName);
		_body.composeBOOL(multiTourn);
		_body.composeUINT32(price);
		_body.composeString(currency);
		_body.composeSrvTime(issued);
		_body.composeSrvTime(expireAt);
		_body.composeINT32(tournNumber);
	}

	_msg.composeMsgBody(_body);
}

void PersonalizationATF::cli::TournTicketInfo::parseMsg(CommMsgParser& _parser)
{
	CommMsgBody _body;
	_parser.parseMsgBody(_body);

	CommMsgParser _parser0(_body);
	_parser0.parseUINT32(ticketId);
	_parser0.parseStringP(ticketName);
	_parser0.parseBOOL(multiTourn);
	_parser0.parseUINT32(price);
	_parser0.parseStringP(currency);
	_parser0.parseSrvTime(issued);
	_parser0.parseSrvTime(expireAt);
	_parser0.parseINT32(tournNumber);
}

/*static*/ void PersonalizationATF::cli::TournTicketInfo::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent)
{
	AtfMsgBodyParserView _parser0(_parser);
	_parser.skipMsgBody();
	const char *_dummy = "";
	UINT32 ticketId; _parser0.parseUINT32(ticketId);
	AtfValidator::validateInt(_descr, "ticketId", ticketId, _checker, __FILE__, __LINE__);
	_parser0.parseStringN(_dummy, 0, "ticketName"); size_t szTicketName = strlen(_dummy);
	AtfValidator::validateInt(_descr, "ticketName", szTicketName, _checker, __FILE__, __LINE__);
	bool multiTourn; _parser0.parseBOOL(multiTourn);
	AtfValidator::validateInt(_descr, "multiTourn", multiTourn, _checker, __FILE__, __LINE__);
	UINT32 price; _parser0.parseUINT32(price);
	AtfValidator::validateInt(_descr, "price", price, _checker, __FILE__, __LINE__);
	_parser0.parseStringN(_dummy, 0, "currency"); size_t szCurrency = strlen(_dummy);
	AtfValidator::validateInt(_descr, "currency", szCurrency, _checker, __FILE__, __LINE__);
	SrvTime issued; _parser0.parseSrvTime(issued);
	AtfValidator::validateSrvDateTime(_descr, "issued", issued, _checker, __FILE__, __LINE__);
	SrvTime expireAt; _parser0.parseSrvTime(expireAt);
	AtfValidator::validateSrvDateTime(_descr, "expireAt", expireAt, _checker, __FILE__, __LINE__);
	INT32 tournNumber; _parser0.parseINT32(tournNumber);
	AtfValidator::validateInt(_descr, "tournNumber", tournNumber, _checker, __FILE__, __LINE__);
	AtfValidator::validateEmbeddedMsgbodyParser(_descr, _parser0, _parser._shift(), __FILE__, __LINE__);
	if(!_parser0.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser0);
}

//=================================================================
//                    TournCountFilter
//=================================================================

PersonalizationATF::cli::TournCountFilter::TournCountFilter()
{
	clear();
}

void PersonalizationATF::cli::TournCountFilter::clear()
{
	gameMask = (2*(UINT64)NGGameTypes::NGGame_Last-1);
}

bool PersonalizationATF::cli::TournCountFilter::equals(const TournCountFilter& _o) const
{
	return gameMask == _o.gameMask;
}

const char *PersonalizationATF::cli::TournCountFilter::toTraceString(PString& _buf) const
{
	_buf.append('{');
	_buf.append("gameMask=");
	_buf.appendUint64(gameMask);
	_buf.append('}');
	return _buf.c_str();
}

void PersonalizationATF::cli::TournCountFilter::composeMsg(CommMsgBody& _msg) const
{
	CommMsgBody _body;
	//if (!equals(TournCountFilter())) // not empty
	{
		_body.composeUINT64(gameMask);
	}

	_msg.composeMsgBody(_body);
}

void PersonalizationATF::cli::TournCountFilter::parseMsg(CommMsgParser& _parser)
{
	CommMsgBody _body;
	_parser.parseMsgBody(_body);

	CommMsgParser _parser0(_body);
	_parser0.parseUINT64(gameMask);
}

/*static*/ void PersonalizationATF::cli::TournCountFilter::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent)
{
	AtfMsgBodyParserView _parser0(_parser);
	_parser.skipMsgBody();
	UINT64 gameMask; _parser0.parseUINT64(gameMask);
	AtfValidator::validateUintMax(_descr, "gameMask", gameMask, (2*(UINT64)NGGameTypes::NGGame_Last-1), _checker, __FILE__, __LINE__);
	AtfValidator::validateEmbeddedMsgbodyParser(_descr, _parser0, _parser._shift(), __FILE__, __LINE__);
	if(!_parser0.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser0);
}

//=================================================================
//                Protocol_PS_Q_GET_RECENT_GAME_LIST
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_GET_RECENT_GAME_LIST::Protocol_PS_Q_GET_RECENT_GAME_LIST()
{
	clear();
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_RECENT_GAME_LIST::clear()
{
	gameTypes = 0;
	isPM = false;
}

bool PersonalizationATF::cli::Protocol_PS_Q_GET_RECENT_GAME_LIST::equals(const Protocol_PS_Q_GET_RECENT_GAME_LIST& _o) const
{
	return gameTypes == _o.gameTypes &&
		isPM == _o.isPM;
}

const char *PersonalizationATF::cli::Protocol_PS_Q_GET_RECENT_GAME_LIST::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_GET_RECENT_GAME_LIST).append(")");
	_buf.append(',');
	_buf.append("gameTypes=");
	_buf.appendUint(gameTypes);
	_buf.append(',');
	_buf.append("isPM=");
	_buf.appendUint(isPM);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_RECENT_GAME_LIST::composeMsg(CommMsgBody& _msg) const
{
	_msg.composeUINT32(gameTypes);
	_msg.composeBOOL(isPM);
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_RECENT_GAME_LIST::parseMsg(CommMsgParser& _parser)
{
	_parser.parseUINT32(gameTypes);
	_parser.parseBOOL(isPM);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_GET_RECENT_GAME_LIST::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_GET_RECENT_GAME_LIST";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	UINT32 gameTypes; _parser.parseUINT32(gameTypes);
	AtfValidator::validateIntMax(_descr, "gameTypes", gameTypes, (2*GameCategory_Last-1), _checker, __FILE__, __LINE__);
	bool isPM; _parser.parseBOOL(isPM);
	AtfValidator::validateInt(_descr, "isPM", isPM, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_GET_RECENT_GAME_LIST
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST::Protocol_PS_A_GET_RECENT_GAME_LIST()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST::Protocol_PS_A_GET_RECENT_GAME_LIST(Protocol_PS_A_GET_RECENT_GAME_LIST&& _o)
	: tourns(std::move(_o.tourns))
	, tableTypes(std::move(_o.tableTypes))
	, sngTypes(std::move(_o.sngTypes))
	, sagTypes(std::move(_o.sagTypes))
	, zoomTypes(std::move(_o.zoomTypes))
	, seatFinders(std::move(_o.seatFinders))
	, gameOrder(std::move(_o.gameOrder))
	, pppTypes(std::move(_o.pppTypes))
{
}

PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST& PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST::operator=(Protocol_PS_A_GET_RECENT_GAME_LIST&& _o)
{
	if(this != &_o)
	{
		tourns = std::move(_o.tourns);
		tableTypes = std::move(_o.tableTypes);
		sngTypes = std::move(_o.sngTypes);
		sagTypes = std::move(_o.sagTypes);
		zoomTypes = std::move(_o.zoomTypes);
		seatFinders = std::move(_o.seatFinders);
		gameOrder = std::move(_o.gameOrder);
		pppTypes = std::move(_o.pppTypes);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST::clear()
{
	tourns.clear();
	tableTypes.clear();
	sngTypes.clear();
	sagTypes.clear();
	zoomTypes.clear();
	seatFinders.clear();
	gameOrder.clear();
	pppTypes.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST::equals(const Protocol_PS_A_GET_RECENT_GAME_LIST& _o) const
{
	return tourns.equals(_o.tourns) &&
		tableTypes.equals(_o.tableTypes) &&
		sngTypes.equals(_o.sngTypes) &&
		sagTypes.equals(_o.sagTypes) &&
		zoomTypes.equals(_o.zoomTypes) &&
		seatFinders.equals(_o.seatFinders) &&
		gameOrder.equals(_o.gameOrder) &&
		pppTypes.equals(_o.pppTypes);
}

const char *PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_GET_RECENT_GAME_LIST).append(")");
	_buf.append(',');
	_buf.append("tourns=");
	tourns.toTraceString(_buf);
	_buf.append(',');
	_buf.append("tableTypes=");
	tableTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("sngTypes=");
	sngTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("sagTypes=");
	sagTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("zoomTypes=");
	zoomTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("seatFinders=");
	seatFinders.toTraceString(_buf);
	_buf.append(',');
	_buf.append("gameOrder=");
	gameOrder.toTraceString(_buf);
	_buf.append(',');
	_buf.append("pppTypes=");
	pppTypes.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST::composeMsg(CommMsgBody& _msg) const
{
	tourns.composeMsg(_msg);
	tableTypes.composeMsg(_msg);
	sngTypes.composeMsg(_msg);
	sagTypes.composeMsg(_msg);
	zoomTypes.composeMsg(_msg);
	seatFinders.composeMsg(_msg);
	gameOrder.composeMsg(_msg);
	pppTypes.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST::parseMsg(CommMsgParser& _parser)
{
	tourns.parseMsg(_parser);
	tableTypes.parseMsg(_parser);
	sngTypes.parseMsg(_parser);
	sagTypes.parseMsg(_parser);
	zoomTypes.parseMsg(_parser);
	seatFinders.parseMsg(_parser);
	gameOrder.parseMsg(_parser);
	if(_parser.parseEnded()) return;
	pppTypes.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_GET_RECENT_GAME_LIST::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_GET_RECENT_GAME_LIST";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	int szTourns = ThinAtf::LAtfVector< MLobbyNG::cli::TournDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tourns"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tourns", szTourns, _checker, __FILE__, __LINE__);
	int szTableTypes = ThinAtf::LAtfVector< MLobbyNG::cli::TableDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tableTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tableTypes", szTableTypes, _checker, __FILE__, __LINE__);
	int szSngTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SngDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sngTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "sngTypes", szSngTypes, _checker, __FILE__, __LINE__);
	int szSagTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SagDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sagTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "sagTypes", szSagTypes, _checker, __FILE__, __LINE__);
	int szZoomTypes = ThinAtf::LAtfVector< MLobbyNG::cli::ZoomDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("zoomTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "zoomTypes", szZoomTypes, _checker, __FILE__, __LINE__);
	int szSeatFinders = ThinAtf::LAtfVector< MLobbyNG::cli::SeatFinderDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("seatFinders"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "seatFinders", szSeatFinders, _checker, __FILE__, __LINE__);
	int szGameOrder = ThinAtf::LAtfVector< UINT32, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("gameOrder"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "gameOrder", szGameOrder, _checker, __FILE__, __LINE__);
	if(_parser.parseEnded()) return;
	int szPppTypes = ThinAtf::LAtfVector< MLobbyNG::cli::PPPDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("pppTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "pppTypes", szPppTypes, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST(Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST&& _o)
	: gameTypes(std::move(_o.gameTypes))
	, userIntId(std::move(_o.userIntId))
	, filter(std::move(_o.filter))
{
}

PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST& PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::operator=(Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST&& _o)
{
	if(this != &_o)
	{
		gameTypes = std::move(_o.gameTypes);
		userIntId = std::move(_o.userIntId);
		filter = std::move(_o.filter);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::clear()
{
	gameTypes = 0;
	userIntId = 0;
	filter.clear();
}

bool PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::equals(const Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST& _o) const
{
	return gameTypes == _o.gameTypes &&
		userIntId == _o.userIntId &&
		filter.equals(_o.filter);
}

const char *PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_ADMIN_GET_RECENT_GAME_LIST).append(")");
	_buf.append(',');
	_buf.append("gameTypes=");
	_buf.appendUint(gameTypes);
	_buf.append(',');
	_buf.append("userIntId=");
	_buf.appendUint(userIntId);
	_buf.append(',');
	_buf.append("filter=");
	filter.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::composeMsg(CommMsgBody& _msg) const
{
	_msg.composeUINT32(gameTypes);
	_msg.composeUINT32(userIntId);
	filter.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::parseMsg(CommMsgParser& _parser)
{
	_parser.parseUINT32(gameTypes);
	_parser.parseUINT32(userIntId);
	filter.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_ADMIN_GET_RECENT_GAME_LIST";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	UINT32 gameTypes; _parser.parseUINT32(gameTypes);
	AtfValidator::validateInt(_descr, "gameTypes", gameTypes, _checker, __FILE__, __LINE__);
	UINT32 userIntId; _parser.parseUINT32(userIntId);
	AtfValidator::validateInt(_descr, "userIntId", userIntId, _checker, __FILE__, __LINE__);
	PString _descbuf;
	MLobbyNG::cli::GameListFilter::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("filter"), _fieldsWithUnparsedContent);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST(Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST&& _o)
	: errCode(std::move(_o.errCode))
	, errMsg(std::move(_o.errMsg))
	, tourns(std::move(_o.tourns))
	, tableTypes(std::move(_o.tableTypes))
	, sngTypes(std::move(_o.sngTypes))
	, sagTypes(std::move(_o.sagTypes))
	, zoomTypes(std::move(_o.zoomTypes))
	, seatFinders(std::move(_o.seatFinders))
	, gameOrder(std::move(_o.gameOrder))
	, pppTypes(std::move(_o.pppTypes))
{
}

PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST& PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::operator=(Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST&& _o)
{
	if(this != &_o)
	{
		errCode = std::move(_o.errCode);
		errMsg = std::move(_o.errMsg);
		tourns = std::move(_o.tourns);
		tableTypes = std::move(_o.tableTypes);
		sngTypes = std::move(_o.sngTypes);
		sagTypes = std::move(_o.sagTypes);
		zoomTypes = std::move(_o.zoomTypes);
		seatFinders = std::move(_o.seatFinders);
		gameOrder = std::move(_o.gameOrder);
		pppTypes = std::move(_o.pppTypes);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::clear()
{
	errCode = 0;
	errMsg.clear();
	tourns.clear();
	tableTypes.clear();
	sngTypes.clear();
	sagTypes.clear();
	zoomTypes.clear();
	seatFinders.clear();
	gameOrder.clear();
	pppTypes.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::equals(const Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST& _o) const
{
	return errCode == _o.errCode &&
		errMsg.equals(_o.errMsg) &&
		tourns.equals(_o.tourns) &&
		tableTypes.equals(_o.tableTypes) &&
		sngTypes.equals(_o.sngTypes) &&
		sagTypes.equals(_o.sagTypes) &&
		zoomTypes.equals(_o.zoomTypes) &&
		seatFinders.equals(_o.seatFinders) &&
		gameOrder.equals(_o.gameOrder) &&
		pppTypes.equals(_o.pppTypes);
}

const char *PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_ADMIN_GET_RECENT_GAME_LIST).append(")");
	_buf.append(',');
	_buf.append("errCode=");
	_buf.appendInt(errCode);
	if( errCode )
	{
		_buf.append(',');
		_buf.append("errMsg=");
		_buf.append(errMsg);
	}
	else
	{
		_buf.append(',');
		_buf.append("tourns=");
		tourns.toTraceString(_buf);
		_buf.append(',');
		_buf.append("tableTypes=");
		tableTypes.toTraceString(_buf);
		_buf.append(',');
		_buf.append("sngTypes=");
		sngTypes.toTraceString(_buf);
		_buf.append(',');
		_buf.append("sagTypes=");
		sagTypes.toTraceString(_buf);
		_buf.append(',');
		_buf.append("zoomTypes=");
		zoomTypes.toTraceString(_buf);
		_buf.append(',');
		_buf.append("seatFinders=");
		seatFinders.toTraceString(_buf);
		_buf.append(',');
		_buf.append("gameOrder=");
		gameOrder.toTraceString(_buf);
		_buf.append(',');
		_buf.append("pppTypes=");
		pppTypes.toTraceString(_buf);
	}
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::composeMsg(CommMsgBody& _msg) const
{
	_msg.composeINT16(errCode);
	if( errCode )
	{
		_msg.composeString(errMsg);
	}
	else
	{
		tourns.composeMsg(_msg);
		tableTypes.composeMsg(_msg);
		sngTypes.composeMsg(_msg);
		sagTypes.composeMsg(_msg);
		zoomTypes.composeMsg(_msg);
		seatFinders.composeMsg(_msg);
		gameOrder.composeMsg(_msg);
		pppTypes.composeMsg(_msg);
	}
}

void PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::parseMsg(CommMsgParser& _parser)
{
	_parser.parseINT16(errCode);
	if( errCode )
	{
		_parser.parseStringP(errMsg);
	}
	else
	{
		tourns.parseMsg(_parser);
		tableTypes.parseMsg(_parser);
		sngTypes.parseMsg(_parser);
		sagTypes.parseMsg(_parser);
		zoomTypes.parseMsg(_parser);
		seatFinders.parseMsg(_parser);
		gameOrder.parseMsg(_parser);
		if(_parser.parseEnded()) return;
		pppTypes.parseMsg(_parser);
	}
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_ADMIN_GET_RECENT_GAME_LIST";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	const char *_dummy = "";
	INT16 errCode = 0;
	_parser.parseINT16(errCode);
	AtfValidator::validateInt(_descr, "errCode", errCode, _checker, __FILE__, __LINE__);
	if( errCode )
	{
		_parser.parseStringN(_dummy, 0, "errMsg"); size_t szErrMsg = strlen(_dummy);
		AtfValidator::validateInt(_descr, "errMsg", szErrMsg, _checker, __FILE__, __LINE__);
	}
	else
	{
		PString _descbuf;
		int szTourns = ThinAtf::LAtfVector< MLobbyNG::cli::TournDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tourns"), _fieldsWithUnparsedContent);
		AtfValidator::validateInt(_descr, "tourns", szTourns, _checker, __FILE__, __LINE__);
		int szTableTypes = ThinAtf::LAtfVector< MLobbyNG::cli::TableDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tableTypes"), _fieldsWithUnparsedContent);
		AtfValidator::validateInt(_descr, "tableTypes", szTableTypes, _checker, __FILE__, __LINE__);
		int szSngTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SngDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sngTypes"), _fieldsWithUnparsedContent);
		AtfValidator::validateInt(_descr, "sngTypes", szSngTypes, _checker, __FILE__, __LINE__);
		int szSagTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SagDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sagTypes"), _fieldsWithUnparsedContent);
		AtfValidator::validateInt(_descr, "sagTypes", szSagTypes, _checker, __FILE__, __LINE__);
		int szZoomTypes = ThinAtf::LAtfVector< MLobbyNG::cli::ZoomDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("zoomTypes"), _fieldsWithUnparsedContent);
		AtfValidator::validateInt(_descr, "zoomTypes", szZoomTypes, _checker, __FILE__, __LINE__);
		int szSeatFinders = ThinAtf::LAtfVector< MLobbyNG::cli::SeatFinderDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("seatFinders"), _fieldsWithUnparsedContent);
		AtfValidator::validateInt(_descr, "seatFinders", szSeatFinders, _checker, __FILE__, __LINE__);
		int szGameOrder = ThinAtf::LAtfVector< UINT32, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("gameOrder"), _fieldsWithUnparsedContent);
		AtfValidator::validateInt(_descr, "gameOrder", szGameOrder, _checker, __FILE__, __LINE__);
		if(_parser.parseEnded()) return;
		int szPppTypes = ThinAtf::LAtfVector< MLobbyNG::cli::PPPDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("pppTypes"), _fieldsWithUnparsedContent);
		AtfValidator::validateInt(_descr, "pppTypes", szPppTypes, _checker, __FILE__, __LINE__);
	}
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_U_GET_CURRENTLY_SEATED_AT
//=================================================================

PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::Protocol_PS_U_GET_CURRENTLY_SEATED_AT()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::Protocol_PS_U_GET_CURRENTLY_SEATED_AT(Protocol_PS_U_GET_CURRENTLY_SEATED_AT&& _o)
	: joined(std::move(_o.joined))
	, tourns(std::move(_o.tourns))
	, tables(std::move(_o.tables))
	, zoomTypes(std::move(_o.zoomTypes))
{
}

PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT& PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::operator=(Protocol_PS_U_GET_CURRENTLY_SEATED_AT&& _o)
{
	if(this != &_o)
	{
		joined = std::move(_o.joined);
		tourns = std::move(_o.tourns);
		tables = std::move(_o.tables);
		zoomTypes = std::move(_o.zoomTypes);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::clear()
{
	joined = false;
	tourns.clear();
	tables.clear();
	zoomTypes.clear();
}

bool PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::equals(const Protocol_PS_U_GET_CURRENTLY_SEATED_AT& _o) const
{
	return joined == _o.joined &&
		tourns.equals(_o.tourns) &&
		tables.equals(_o.tables) &&
		zoomTypes.equals(_o.zoomTypes);
}

const char *PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_U_GET_CURRENTLY_SEATED_AT).append(")");
	_buf.append(',');
	_buf.append("joined=");
	_buf.appendUint(joined);
	_buf.append(',');
	_buf.append("tourns=");
	tourns.toTraceString(_buf);
	_buf.append(',');
	_buf.append("tables=");
	tables.toTraceString(_buf);
	_buf.append(',');
	_buf.append("zoomTypes=");
	zoomTypes.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::composeMsg(CommMsgBody& _msg) const
{
	_msg.composeBOOL(joined);
	tourns.composeMsg(_msg);
	tables.composeMsg(_msg);
	zoomTypes.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::parseMsg(CommMsgParser& _parser)
{
	_parser.parseBOOL(joined);
	tourns.parseMsg(_parser);
	tables.parseMsg(_parser);
	zoomTypes.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_U_GET_CURRENTLY_SEATED_AT";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	bool joined; _parser.parseBOOL(joined);
	AtfValidator::validateInt(_descr, "joined", joined, _checker, __FILE__, __LINE__);
	PString _descbuf;
	int szTourns = ThinAtf::LAtfVector< MLobbyNG::cli::TournDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tourns"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tourns", szTourns, _checker, __FILE__, __LINE__);
	int szTables = ThinAtf::LAtfVector< MLobbyNG::cli::TableData, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tables"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tables", szTables, _checker, __FILE__, __LINE__);
	int szZoomTypes = ThinAtf::LAtfVector< MLobbyNG::cli::ZoomDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("zoomTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "zoomTypes", szZoomTypes, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_Q_GET_TICKET_TOURNS
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS::Protocol_PS_Q_GET_TICKET_TOURNS()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS::Protocol_PS_Q_GET_TICKET_TOURNS(Protocol_PS_Q_GET_TICKET_TOURNS&& _o)
	: ticketNames(std::move(_o.ticketNames))
	, gameCategoryMask(std::move(_o.gameCategoryMask))
	, ticketTournRequestMask(std::move(_o.ticketTournRequestMask))
	, isPM(std::move(_o.isPM))
{
}

PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS& PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS::operator=(Protocol_PS_Q_GET_TICKET_TOURNS&& _o)
{
	if(this != &_o)
	{
		ticketNames = std::move(_o.ticketNames);
		gameCategoryMask = std::move(_o.gameCategoryMask);
		ticketTournRequestMask = std::move(_o.ticketTournRequestMask);
		isPM = std::move(_o.isPM);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS::clear()
{
	ticketNames.clear();
	gameCategoryMask = 0;
	ticketTournRequestMask = 0;
	isPM = false;
}

bool PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS::equals(const Protocol_PS_Q_GET_TICKET_TOURNS& _o) const
{
	return ticketNames.equals(_o.ticketNames) &&
		gameCategoryMask == _o.gameCategoryMask &&
		ticketTournRequestMask == _o.ticketTournRequestMask &&
		isPM == _o.isPM;
}

const char *PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_GET_TICKET_TOURNS).append(")");
	_buf.append(',');
	_buf.append("ticketNames=");
	ticketNames.toTraceString(_buf);
	_buf.append(',');
	_buf.append("gameCategoryMask=");
	_buf.appendUint(gameCategoryMask);
	_buf.append(',');
	_buf.append("ticketTournRequestMask=");
	_buf.appendUint(ticketTournRequestMask);
	_buf.append(',');
	_buf.append("isPM=");
	_buf.appendUint(isPM);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS::composeMsg(CommMsgBody& _msg) const
{
	ticketNames.composeMsg(_msg);
	_msg.composeUINT32(gameCategoryMask);
	_msg.composeUINT32(ticketTournRequestMask);
	_msg.composeBOOL(isPM);
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS::parseMsg(CommMsgParser& _parser)
{
	ticketNames.parseMsg(_parser);
	_parser.parseUINT32(gameCategoryMask);
	_parser.parseUINT32(ticketTournRequestMask);
	_parser.parseBOOL(isPM);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_TOURNS::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_GET_TICKET_TOURNS";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	int szTicketNames = ThinAtf::LAtfVector< PString, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("ticketNames"), _fieldsWithUnparsedContent);
	AtfValidator::validateIntMax(_descr, "ticketNames", szTicketNames, 100, _checker, __FILE__, __LINE__);
	UINT32 gameCategoryMask; _parser.parseUINT32(gameCategoryMask);
	AtfValidator::validateIntMax(_descr, "gameCategoryMask", gameCategoryMask, (2*GameCategory_Last-1), _checker, __FILE__, __LINE__);
	UINT32 ticketTournRequestMask; _parser.parseUINT32(ticketTournRequestMask);
	AtfValidator::validateIntMax(_descr, "ticketTournRequestMask", ticketTournRequestMask, (2*TicketTournRequest_Last-1), _checker, __FILE__, __LINE__);
	bool isPM; _parser.parseBOOL(isPM);
	AtfValidator::validateInt(_descr, "isPM", isPM, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_GET_TICKET_TOURNS
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS::Protocol_PS_A_GET_TICKET_TOURNS()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS::Protocol_PS_A_GET_TICKET_TOURNS(Protocol_PS_A_GET_TICKET_TOURNS&& _o)
	: ticketInfos(std::move(_o.ticketInfos))
{
}

PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS& PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS::operator=(Protocol_PS_A_GET_TICKET_TOURNS&& _o)
{
	if(this != &_o)
	{
		ticketInfos = std::move(_o.ticketInfos);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS::clear()
{
	ticketInfos.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS::equals(const Protocol_PS_A_GET_TICKET_TOURNS& _o) const
{
	return ticketInfos.equals(_o.ticketInfos);
}

const char *PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_GET_TICKET_TOURNS).append(")");
	_buf.append(',');
	_buf.append("ticketInfos=");
	ticketInfos.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS::composeMsg(CommMsgBody& _msg) const
{
	ticketInfos.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS::parseMsg(CommMsgParser& _parser)
{
	ticketInfos.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_TOURNS::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_GET_TICKET_TOURNS";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	int szTicketInfos = ThinAtf::LAtfVector< MLobbyNG::cli::OrderedTicketTournInfo, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("ticketInfos"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "ticketInfos", szTicketInfos, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_Q_FILTER_GAMES
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES::Protocol_PS_Q_FILTER_GAMES()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES::Protocol_PS_Q_FILTER_GAMES(Protocol_PS_Q_FILTER_GAMES&& _o)
	: filter(std::move(_o.filter))
	, criteria(std::move(_o.criteria))
	, clientMarkers(std::move(_o.clientMarkers))
{
}

PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES& PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES::operator=(Protocol_PS_Q_FILTER_GAMES&& _o)
{
	if(this != &_o)
	{
		filter = std::move(_o.filter);
		criteria = std::move(_o.criteria);
		clientMarkers = std::move(_o.clientMarkers);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES::clear()
{
	filter.clear();
	criteria.clear();
	clientMarkers.clear();
}

bool PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES::equals(const Protocol_PS_Q_FILTER_GAMES& _o) const
{
	return filter.equals(_o.filter) &&
		criteria.equals(_o.criteria) &&
		clientMarkers.equals(_o.clientMarkers);
}

const char *PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_FILTER_GAMES).append(")");
	_buf.append(',');
	_buf.append("filter=");
	filter.toTraceString(_buf);
	_buf.append(',');
	_buf.append("criteria=");
	criteria.toTraceString(_buf);
	_buf.append(',');
	_buf.append("clientMarkers=");
	clientMarkers.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES::composeMsg(CommMsgBody& _msg) const
{
	filter.composeMsg(_msg);
	criteria.composeMsg(_msg);
	clientMarkers.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES::parseMsg(CommMsgParser& _parser)
{
	filter.parseMsg(_parser);
	criteria.parseMsg(_parser);
	clientMarkers.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_FILTER_GAMES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_FILTER_GAMES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	MLobbyNG::cli::FilterGamesSelectionFilter::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("filter"), _fieldsWithUnparsedContent);
	MLobbyNG::cli::FilterGamesResultCriteria::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("criteria"), _fieldsWithUnparsedContent);
	MLobbyNG::cli::ClientMarkers::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("clientMarkers"), _fieldsWithUnparsedContent);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_FILTER_GAMES
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES::Protocol_PS_A_FILTER_GAMES()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES::Protocol_PS_A_FILTER_GAMES(Protocol_PS_A_FILTER_GAMES&& _o)
	: tourns(std::move(_o.tourns))
	, tableTypes(std::move(_o.tableTypes))
	, sngTypes(std::move(_o.sngTypes))
	, sagTypes(std::move(_o.sagTypes))
	, zoomTypes(std::move(_o.zoomTypes))
	, seatFinders(std::move(_o.seatFinders))
	, gameOrder(std::move(_o.gameOrder))
	, totalItems(std::move(_o.totalItems))
	, minBuyIn(std::move(_o.minBuyIn))
	, maxBuyIn(std::move(_o.maxBuyIn))
	, resultRanges(std::move(_o.resultRanges))
{
}

PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES& PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES::operator=(Protocol_PS_A_FILTER_GAMES&& _o)
{
	if(this != &_o)
	{
		tourns = std::move(_o.tourns);
		tableTypes = std::move(_o.tableTypes);
		sngTypes = std::move(_o.sngTypes);
		sagTypes = std::move(_o.sagTypes);
		zoomTypes = std::move(_o.zoomTypes);
		seatFinders = std::move(_o.seatFinders);
		gameOrder = std::move(_o.gameOrder);
		totalItems = std::move(_o.totalItems);
		minBuyIn = std::move(_o.minBuyIn);
		maxBuyIn = std::move(_o.maxBuyIn);
		resultRanges = std::move(_o.resultRanges);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES::clear()
{
	tourns.clear();
	tableTypes.clear();
	sngTypes.clear();
	sagTypes.clear();
	zoomTypes.clear();
	seatFinders.clear();
	gameOrder.clear();
	totalItems = 0;
	minBuyIn = 0;
	maxBuyIn = 0;
	resultRanges.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES::equals(const Protocol_PS_A_FILTER_GAMES& _o) const
{
	return tourns.equals(_o.tourns) &&
		tableTypes.equals(_o.tableTypes) &&
		sngTypes.equals(_o.sngTypes) &&
		sagTypes.equals(_o.sagTypes) &&
		zoomTypes.equals(_o.zoomTypes) &&
		seatFinders.equals(_o.seatFinders) &&
		gameOrder.equals(_o.gameOrder) &&
		totalItems == _o.totalItems &&
		minBuyIn == _o.minBuyIn &&
		maxBuyIn == _o.maxBuyIn &&
		resultRanges.equals(_o.resultRanges);
}

const char *PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_FILTER_GAMES).append(")");
	_buf.append(',');
	_buf.append("tourns=");
	tourns.toTraceString(_buf);
	_buf.append(',');
	_buf.append("tableTypes=");
	tableTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("sngTypes=");
	sngTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("sagTypes=");
	sagTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("zoomTypes=");
	zoomTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("seatFinders=");
	seatFinders.toTraceString(_buf);
	_buf.append(',');
	_buf.append("gameOrder=");
	gameOrder.toTraceString(_buf);
	_buf.append(',');
	_buf.append("totalItems=");
	_buf.appendInt(totalItems);
	_buf.append(',');
	_buf.append("minBuyIn=");
	_buf.appendInt64(minBuyIn);
	_buf.append(',');
	_buf.append("maxBuyIn=");
	_buf.appendInt64(maxBuyIn);
	_buf.append(',');
	_buf.append("resultRanges=");
	resultRanges.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES::composeMsg(CommMsgBody& _msg) const
{
	tourns.composeMsg(_msg);
	tableTypes.composeMsg(_msg);
	sngTypes.composeMsg(_msg);
	sagTypes.composeMsg(_msg);
	zoomTypes.composeMsg(_msg);
	seatFinders.composeMsg(_msg);
	gameOrder.composeMsg(_msg);
	_msg.composeINT32(totalItems);
	_msg.composeINT64(minBuyIn);
	_msg.composeINT64(maxBuyIn);
	resultRanges.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES::parseMsg(CommMsgParser& _parser)
{
	tourns.parseMsg(_parser);
	tableTypes.parseMsg(_parser);
	sngTypes.parseMsg(_parser);
	sagTypes.parseMsg(_parser);
	zoomTypes.parseMsg(_parser);
	seatFinders.parseMsg(_parser);
	gameOrder.parseMsg(_parser);
	_parser.parseINT32(totalItems);
	_parser.parseINT64(minBuyIn);
	_parser.parseINT64(maxBuyIn);
	resultRanges.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_FILTER_GAMES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_FILTER_GAMES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	int szTourns = ThinAtf::LAtfVector< MLobbyNG::cli::TournDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tourns"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tourns", szTourns, _checker, __FILE__, __LINE__);
	int szTableTypes = ThinAtf::LAtfVector< MLobbyNG::cli::TableDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tableTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tableTypes", szTableTypes, _checker, __FILE__, __LINE__);
	int szSngTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SngDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sngTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "sngTypes", szSngTypes, _checker, __FILE__, __LINE__);
	int szSagTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SagDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sagTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "sagTypes", szSagTypes, _checker, __FILE__, __LINE__);
	int szZoomTypes = ThinAtf::LAtfVector< MLobbyNG::cli::ZoomDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("zoomTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "zoomTypes", szZoomTypes, _checker, __FILE__, __LINE__);
	int szSeatFinders = ThinAtf::LAtfVector< MLobbyNG::cli::SeatFinderDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("seatFinders"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "seatFinders", szSeatFinders, _checker, __FILE__, __LINE__);
	int szGameOrder = ThinAtf::LAtfVector< UINT32, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("gameOrder"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "gameOrder", szGameOrder, _checker, __FILE__, __LINE__);
	INT32 totalItems; _parser.parseINT32(totalItems);
	AtfValidator::validateInt(_descr, "totalItems", totalItems, _checker, __FILE__, __LINE__);
	INT64 minBuyIn; _parser.parseINT64(minBuyIn);
	AtfValidator::validateInt(_descr, "minBuyIn", minBuyIn, _checker, __FILE__, __LINE__);
	INT64 maxBuyIn; _parser.parseINT64(maxBuyIn);
	AtfValidator::validateInt(_descr, "maxBuyIn", maxBuyIn, _checker, __FILE__, __LINE__);
	MLobbyNG::cli::ResultRanges::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("resultRanges"), _fieldsWithUnparsedContent);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_Q_GET_BRANDED_LOBBIES
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::Protocol_PS_Q_GET_BRANDED_LOBBIES()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::Protocol_PS_Q_GET_BRANDED_LOBBIES(Protocol_PS_Q_GET_BRANDED_LOBBIES&& _o)
	: currencyMask(std::move(_o.currencyMask))
	, country(std::move(_o.country))
	, isPM(std::move(_o.isPM))
{
}

PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES& PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::operator=(Protocol_PS_Q_GET_BRANDED_LOBBIES&& _o)
{
	if(this != &_o)
	{
		currencyMask = std::move(_o.currencyMask);
		country = std::move(_o.country);
		isPM = std::move(_o.isPM);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::clear()
{
	currencyMask = 0;
	country.clear();
	isPM = false;
}

bool PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::equals(const Protocol_PS_Q_GET_BRANDED_LOBBIES& _o) const
{
	return currencyMask == _o.currencyMask &&
		country.equals(_o.country) &&
		isPM == _o.isPM;
}

const char *PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_GET_BRANDED_LOBBIES).append(")");
	_buf.append(',');
	_buf.append("currencyMask=");
	_buf.appendUint(currencyMask);
	_buf.append(',');
	_buf.append("country=");
	_buf.append(country);
	_buf.append(',');
	_buf.append("isPM=");
	_buf.appendUint(isPM);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::composeMsg(CommMsgBody& _msg) const
{
	_msg.composeUINT32(currencyMask);
	_msg.composeString(country);
	_msg.composeBOOL(isPM);
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::parseMsg(CommMsgParser& _parser)
{
	if(_parser.parseEnded()) return;
	_parser.parseUINT32(currencyMask);
	if(_parser.parseEnded()) return;
	_parser.parseStringP(country);
	if(_parser.parseEnded()) return;
	_parser.parseBOOL(isPM);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_GET_BRANDED_LOBBIES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	const char *_dummy = "";
	if(_parser.parseEnded()) return;
	UINT32 currencyMask; _parser.parseUINT32(currencyMask);
	AtfValidator::validateInt(_descr, "currencyMask", currencyMask, _checker, __FILE__, __LINE__);
	if(_parser.parseEnded()) return;
	_parser.parseStringN(_dummy, 0, "country"); size_t szCountry = strlen(_dummy);
	AtfValidator::validateInt(_descr, "country", szCountry, _checker, __FILE__, __LINE__);
	if(_parser.parseEnded()) return;
	bool isPM; _parser.parseBOOL(isPM);
	AtfValidator::validateInt(_descr, "isPM", isPM, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_GET_BRANDED_LOBBIES
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES::Protocol_PS_A_GET_BRANDED_LOBBIES()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES::Protocol_PS_A_GET_BRANDED_LOBBIES(Protocol_PS_A_GET_BRANDED_LOBBIES&& _o)
	: lobbies(std::move(_o.lobbies))
{
}

PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES& PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES::operator=(Protocol_PS_A_GET_BRANDED_LOBBIES&& _o)
{
	if(this != &_o)
	{
		lobbies = std::move(_o.lobbies);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES::clear()
{
	lobbies.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES::equals(const Protocol_PS_A_GET_BRANDED_LOBBIES& _o) const
{
	return lobbies.equals(_o.lobbies);
}

const char *PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_GET_BRANDED_LOBBIES).append(")");
	_buf.append(',');
	_buf.append("lobbies=");
	lobbies.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES::composeMsg(CommMsgBody& _msg) const
{
	lobbies.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES::parseMsg(CommMsgParser& _parser)
{
	lobbies.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_GET_BRANDED_LOBBIES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_GET_BRANDED_LOBBIES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	int szLobbies = ThinAtf::LAtfVector< MLobbyNG::cli::BrandedLobbyInfo, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("lobbies"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "lobbies", szLobbies, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_Q_INIT_BRANDED_LOBBIES
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_INIT_BRANDED_LOBBIES::Protocol_PS_Q_INIT_BRANDED_LOBBIES()
{
	clear();
}

void PersonalizationATF::cli::Protocol_PS_Q_INIT_BRANDED_LOBBIES::clear()
{
}

bool PersonalizationATF::cli::Protocol_PS_Q_INIT_BRANDED_LOBBIES::equals(const Protocol_PS_Q_INIT_BRANDED_LOBBIES& _o) const
{
	return true;
}

const char *PersonalizationATF::cli::Protocol_PS_Q_INIT_BRANDED_LOBBIES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_INIT_BRANDED_LOBBIES).append(")");
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_INIT_BRANDED_LOBBIES::composeMsg(CommMsgBody& _msg) const
{
}

void PersonalizationATF::cli::Protocol_PS_Q_INIT_BRANDED_LOBBIES::parseMsg(CommMsgParser& _parser)
{
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_INIT_BRANDED_LOBBIES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_INIT_BRANDED_LOBBIES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_INIT_BRANDED_LOBBIES
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::Protocol_PS_A_INIT_BRANDED_LOBBIES()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::Protocol_PS_A_INIT_BRANDED_LOBBIES(Protocol_PS_A_INIT_BRANDED_LOBBIES&& _o)
	: lobbies(std::move(_o.lobbies))
{
}

PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES& PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::operator=(Protocol_PS_A_INIT_BRANDED_LOBBIES&& _o)
{
	if(this != &_o)
	{
		lobbies = std::move(_o.lobbies);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::clear()
{
	lobbies.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::equals(const Protocol_PS_A_INIT_BRANDED_LOBBIES& _o) const
{
	return lobbies.equals(_o.lobbies);
}

const char *PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_INIT_BRANDED_LOBBIES).append(")");
	_buf.append(',');
	_buf.append("lobbies=");
	lobbies.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::composeMsg(CommMsgBody& _msg) const
{
	lobbies.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::parseMsg(CommMsgParser& _parser)
{
	lobbies.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_INIT_BRANDED_LOBBIES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	int szLobbies = ThinAtf::LAtfVector< MLobbyNG::cli::FullBrandedLobbyInfo, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("lobbies"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "lobbies", szLobbies, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_Q_ADMIN_UPDATE_LOBBIES
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_ADMIN_UPDATE_LOBBIES::Protocol_PS_Q_ADMIN_UPDATE_LOBBIES()
{
	clear();
}

void PersonalizationATF::cli::Protocol_PS_Q_ADMIN_UPDATE_LOBBIES::clear()
{
}

bool PersonalizationATF::cli::Protocol_PS_Q_ADMIN_UPDATE_LOBBIES::equals(const Protocol_PS_Q_ADMIN_UPDATE_LOBBIES& _o) const
{
	return true;
}

const char *PersonalizationATF::cli::Protocol_PS_Q_ADMIN_UPDATE_LOBBIES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_ADMIN_UPDATE_LOBBIES).append(")");
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_ADMIN_UPDATE_LOBBIES::composeMsg(CommMsgBody& _msg) const
{
}

void PersonalizationATF::cli::Protocol_PS_Q_ADMIN_UPDATE_LOBBIES::parseMsg(CommMsgParser& _parser)
{
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_ADMIN_UPDATE_LOBBIES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_ADMIN_UPDATE_LOBBIES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_ADMIN_UPDATE_LOBBIES
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::Protocol_PS_A_ADMIN_UPDATE_LOBBIES()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::Protocol_PS_A_ADMIN_UPDATE_LOBBIES(Protocol_PS_A_ADMIN_UPDATE_LOBBIES&& _o)
	: errCode(std::move(_o.errCode))
	, errMsg(std::move(_o.errMsg))
{
}

PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES& PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::operator=(Protocol_PS_A_ADMIN_UPDATE_LOBBIES&& _o)
{
	if(this != &_o)
	{
		errCode = std::move(_o.errCode);
		errMsg = std::move(_o.errMsg);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::clear()
{
	errCode = 0;
	errMsg.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::equals(const Protocol_PS_A_ADMIN_UPDATE_LOBBIES& _o) const
{
	return errCode == _o.errCode &&
		errMsg.equals(_o.errMsg);
}

const char *PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_ADMIN_UPDATE_LOBBIES).append(")");
	_buf.append(',');
	_buf.append("errCode=");
	_buf.appendInt(errCode);
	if( errCode )
	{
		_buf.append(',');
		_buf.append("errMsg=");
		_buf.append(errMsg);
	}
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::composeMsg(CommMsgBody& _msg) const
{
	_msg.composeINT16(errCode);
	if( errCode )
	{
		_msg.composeString(errMsg);
	}
}

void PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::parseMsg(CommMsgParser& _parser)
{
	_parser.parseINT16(errCode);
	if( errCode )
	{
		_parser.parseStringP(errMsg);
	}
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_ADMIN_UPDATE_LOBBIES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	const char *_dummy = "";
	INT16 errCode = 0;
	_parser.parseINT16(errCode);
	AtfValidator::validateInt(_descr, "errCode", errCode, _checker, __FILE__, __LINE__);
	if( errCode )
	{
		_parser.parseStringN(_dummy, 0, "errMsg"); size_t szErrMsg = strlen(_dummy);
		AtfValidator::validateInt(_descr, "errMsg", szErrMsg, _checker, __FILE__, __LINE__);
	}
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_Q_GET_SUGGESTED_GAMES
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::Protocol_PS_Q_GET_SUGGESTED_GAMES()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::Protocol_PS_Q_GET_SUGGESTED_GAMES(Protocol_PS_Q_GET_SUGGESTED_GAMES&& _o)
	: filter(std::move(_o.filter))
	, clientMarkers(std::move(_o.clientMarkers))
{
}

PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES& PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::operator=(Protocol_PS_Q_GET_SUGGESTED_GAMES&& _o)
{
	if(this != &_o)
	{
		filter = std::move(_o.filter);
		clientMarkers = std::move(_o.clientMarkers);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::clear()
{
	filter.clear();
	clientMarkers.clear();
}

bool PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::equals(const Protocol_PS_Q_GET_SUGGESTED_GAMES& _o) const
{
	return filter.equals(_o.filter) &&
		clientMarkers.equals(_o.clientMarkers);
}

const char *PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_GET_SUGGESTED_GAMES).append(")");
	_buf.append(',');
	_buf.append("filter=");
	filter.toTraceString(_buf);
	_buf.append(',');
	_buf.append("clientMarkers=");
	clientMarkers.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::composeMsg(CommMsgBody& _msg) const
{
	filter.composeMsg(_msg);
	clientMarkers.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::parseMsg(CommMsgParser& _parser)
{
	filter.parseMsg(_parser);
	clientMarkers.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_GET_SUGGESTED_GAMES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	MLobbyNG::cli::SuggestedGames2SelectionFilter::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("filter"), _fieldsWithUnparsedContent);
	MLobbyNG::cli::ClientMarkers::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("clientMarkers"), _fieldsWithUnparsedContent);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_GET_SUGGESTED_GAMES
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES::Protocol_PS_A_GET_SUGGESTED_GAMES()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES::Protocol_PS_A_GET_SUGGESTED_GAMES(Protocol_PS_A_GET_SUGGESTED_GAMES&& _o)
	: tourns(std::move(_o.tourns))
	, tableTypes(std::move(_o.tableTypes))
	, sngTypes(std::move(_o.sngTypes))
	, sagTypes(std::move(_o.sagTypes))
	, zoomTypes(std::move(_o.zoomTypes))
	, seatFinders(std::move(_o.seatFinders))
	, gameOrder(std::move(_o.gameOrder))
{
}

PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES& PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES::operator=(Protocol_PS_A_GET_SUGGESTED_GAMES&& _o)
{
	if(this != &_o)
	{
		tourns = std::move(_o.tourns);
		tableTypes = std::move(_o.tableTypes);
		sngTypes = std::move(_o.sngTypes);
		sagTypes = std::move(_o.sagTypes);
		zoomTypes = std::move(_o.zoomTypes);
		seatFinders = std::move(_o.seatFinders);
		gameOrder = std::move(_o.gameOrder);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES::clear()
{
	tourns.clear();
	tableTypes.clear();
	sngTypes.clear();
	sagTypes.clear();
	zoomTypes.clear();
	seatFinders.clear();
	gameOrder.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES::equals(const Protocol_PS_A_GET_SUGGESTED_GAMES& _o) const
{
	return tourns.equals(_o.tourns) &&
		tableTypes.equals(_o.tableTypes) &&
		sngTypes.equals(_o.sngTypes) &&
		sagTypes.equals(_o.sagTypes) &&
		zoomTypes.equals(_o.zoomTypes) &&
		seatFinders.equals(_o.seatFinders) &&
		gameOrder.equals(_o.gameOrder);
}

const char *PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_GET_SUGGESTED_GAMES).append(")");
	_buf.append(',');
	_buf.append("tourns=");
	tourns.toTraceString(_buf);
	_buf.append(',');
	_buf.append("tableTypes=");
	tableTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("sngTypes=");
	sngTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("sagTypes=");
	sagTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("zoomTypes=");
	zoomTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("seatFinders=");
	seatFinders.toTraceString(_buf);
	_buf.append(',');
	_buf.append("gameOrder=");
	gameOrder.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES::composeMsg(CommMsgBody& _msg) const
{
	tourns.composeMsg(_msg);
	tableTypes.composeMsg(_msg);
	sngTypes.composeMsg(_msg);
	sagTypes.composeMsg(_msg);
	zoomTypes.composeMsg(_msg);
	seatFinders.composeMsg(_msg);
	gameOrder.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES::parseMsg(CommMsgParser& _parser)
{
	tourns.parseMsg(_parser);
	tableTypes.parseMsg(_parser);
	sngTypes.parseMsg(_parser);
	sagTypes.parseMsg(_parser);
	zoomTypes.parseMsg(_parser);
	seatFinders.parseMsg(_parser);
	gameOrder.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_GET_SUGGESTED_GAMES::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_GET_SUGGESTED_GAMES";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	int szTourns = ThinAtf::LAtfVector< MLobbyNG::cli::TournDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tourns"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tourns", szTourns, _checker, __FILE__, __LINE__);
	int szTableTypes = ThinAtf::LAtfVector< MLobbyNG::cli::TableDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tableTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tableTypes", szTableTypes, _checker, __FILE__, __LINE__);
	int szSngTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SngDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sngTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "sngTypes", szSngTypes, _checker, __FILE__, __LINE__);
	int szSagTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SagDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sagTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "sagTypes", szSagTypes, _checker, __FILE__, __LINE__);
	int szZoomTypes = ThinAtf::LAtfVector< MLobbyNG::cli::ZoomDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("zoomTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "zoomTypes", szZoomTypes, _checker, __FILE__, __LINE__);
	int szSeatFinders = ThinAtf::LAtfVector< MLobbyNG::cli::SeatFinderDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("seatFinders"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "seatFinders", szSeatFinders, _checker, __FILE__, __LINE__);
	int szGameOrder = ThinAtf::LAtfVector< UINT32, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("gameOrder"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "gameOrder", szGameOrder, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_Q_SEARCH_BY_NAME
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME::Protocol_PS_Q_SEARCH_BY_NAME()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME::Protocol_PS_Q_SEARCH_BY_NAME(Protocol_PS_Q_SEARCH_BY_NAME&& _o)
	: filter(std::move(_o.filter))
	, criteria(std::move(_o.criteria))
	, clientMarkers(std::move(_o.clientMarkers))
{
}

PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME& PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME::operator=(Protocol_PS_Q_SEARCH_BY_NAME&& _o)
{
	if(this != &_o)
	{
		filter = std::move(_o.filter);
		criteria = std::move(_o.criteria);
		clientMarkers = std::move(_o.clientMarkers);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME::clear()
{
	filter.clear();
	criteria.clear();
	clientMarkers.clear();
}

bool PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME::equals(const Protocol_PS_Q_SEARCH_BY_NAME& _o) const
{
	return filter.equals(_o.filter) &&
		criteria.equals(_o.criteria) &&
		clientMarkers.equals(_o.clientMarkers);
}

const char *PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_SEARCH_BY_NAME).append(")");
	_buf.append(',');
	_buf.append("filter=");
	filter.toTraceString(_buf);
	_buf.append(',');
	_buf.append("criteria=");
	criteria.toTraceString(_buf);
	_buf.append(',');
	_buf.append("clientMarkers=");
	clientMarkers.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME::composeMsg(CommMsgBody& _msg) const
{
	filter.composeMsg(_msg);
	criteria.composeMsg(_msg);
	clientMarkers.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME::parseMsg(CommMsgParser& _parser)
{
	filter.parseMsg(_parser);
	criteria.parseMsg(_parser);
	clientMarkers.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_SEARCH_BY_NAME::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_SEARCH_BY_NAME";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	MLobbyNG::cli::NameSearchSelectionFilter::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("filter"), _fieldsWithUnparsedContent);
	MLobbyNG::cli::FilterGamesResultCriteria::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("criteria"), _fieldsWithUnparsedContent);
	MLobbyNG::cli::ClientMarkers::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("clientMarkers"), _fieldsWithUnparsedContent);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_SEARCH_BY_NAME
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME::Protocol_PS_A_SEARCH_BY_NAME()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME::Protocol_PS_A_SEARCH_BY_NAME(Protocol_PS_A_SEARCH_BY_NAME&& _o)
	: tourns(std::move(_o.tourns))
	, tableTypes(std::move(_o.tableTypes))
	, sngTypes(std::move(_o.sngTypes))
	, sagTypes(std::move(_o.sagTypes))
	, zoomTypes(std::move(_o.zoomTypes))
	, seatFinders(std::move(_o.seatFinders))
	, gameOrder(std::move(_o.gameOrder))
{
}

PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME& PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME::operator=(Protocol_PS_A_SEARCH_BY_NAME&& _o)
{
	if(this != &_o)
	{
		tourns = std::move(_o.tourns);
		tableTypes = std::move(_o.tableTypes);
		sngTypes = std::move(_o.sngTypes);
		sagTypes = std::move(_o.sagTypes);
		zoomTypes = std::move(_o.zoomTypes);
		seatFinders = std::move(_o.seatFinders);
		gameOrder = std::move(_o.gameOrder);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME::clear()
{
	tourns.clear();
	tableTypes.clear();
	sngTypes.clear();
	sagTypes.clear();
	zoomTypes.clear();
	seatFinders.clear();
	gameOrder.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME::equals(const Protocol_PS_A_SEARCH_BY_NAME& _o) const
{
	return tourns.equals(_o.tourns) &&
		tableTypes.equals(_o.tableTypes) &&
		sngTypes.equals(_o.sngTypes) &&
		sagTypes.equals(_o.sagTypes) &&
		zoomTypes.equals(_o.zoomTypes) &&
		seatFinders.equals(_o.seatFinders) &&
		gameOrder.equals(_o.gameOrder);
}

const char *PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_SEARCH_BY_NAME).append(")");
	_buf.append(',');
	_buf.append("tourns=");
	tourns.toTraceString(_buf);
	_buf.append(',');
	_buf.append("tableTypes=");
	tableTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("sngTypes=");
	sngTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("sagTypes=");
	sagTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("zoomTypes=");
	zoomTypes.toTraceString(_buf);
	_buf.append(',');
	_buf.append("seatFinders=");
	seatFinders.toTraceString(_buf);
	_buf.append(',');
	_buf.append("gameOrder=");
	gameOrder.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME::composeMsg(CommMsgBody& _msg) const
{
	tourns.composeMsg(_msg);
	tableTypes.composeMsg(_msg);
	sngTypes.composeMsg(_msg);
	sagTypes.composeMsg(_msg);
	zoomTypes.composeMsg(_msg);
	seatFinders.composeMsg(_msg);
	gameOrder.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME::parseMsg(CommMsgParser& _parser)
{
	tourns.parseMsg(_parser);
	tableTypes.parseMsg(_parser);
	sngTypes.parseMsg(_parser);
	sagTypes.parseMsg(_parser);
	zoomTypes.parseMsg(_parser);
	seatFinders.parseMsg(_parser);
	gameOrder.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_SEARCH_BY_NAME::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_SEARCH_BY_NAME";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	int szTourns = ThinAtf::LAtfVector< MLobbyNG::cli::TournDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tourns"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tourns", szTourns, _checker, __FILE__, __LINE__);
	int szTableTypes = ThinAtf::LAtfVector< MLobbyNG::cli::TableDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tableTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tableTypes", szTableTypes, _checker, __FILE__, __LINE__);
	int szSngTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SngDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sngTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "sngTypes", szSngTypes, _checker, __FILE__, __LINE__);
	int szSagTypes = ThinAtf::LAtfVector< MLobbyNG::cli::SagDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("sagTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "sagTypes", szSagTypes, _checker, __FILE__, __LINE__);
	int szZoomTypes = ThinAtf::LAtfVector< MLobbyNG::cli::ZoomDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("zoomTypes"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "zoomTypes", szZoomTypes, _checker, __FILE__, __LINE__);
	int szSeatFinders = ThinAtf::LAtfVector< MLobbyNG::cli::SeatFinderDataStruct, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("seatFinders"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "seatFinders", szSeatFinders, _checker, __FILE__, __LINE__);
	int szGameOrder = ThinAtf::LAtfVector< UINT32, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("gameOrder"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "gameOrder", szGameOrder, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_Q_GET_TICKET_COUNTS
//=================================================================

PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_COUNTS::Protocol_PS_Q_GET_TICKET_COUNTS()
{
	clear();
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_COUNTS::clear()
{
	filter.clear();
}

bool PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_COUNTS::equals(const Protocol_PS_Q_GET_TICKET_COUNTS& _o) const
{
	return filter.equals(_o.filter);
}

const char *PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_COUNTS::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_Q_GET_TICKET_COUNTS).append(")");
	_buf.append(',');
	_buf.append("filter=");
	filter.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_COUNTS::composeMsg(CommMsgBody& _msg) const
{
	filter.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_COUNTS::parseMsg(CommMsgParser& _parser)
{
	if(_parser.parseEnded()) return;
	filter.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_Q_GET_TICKET_COUNTS::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_Q_GET_TICKET_COUNTS";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	if(_parser.parseEnded()) return;
	PString _descbuf;
	TournCountFilter::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("filter"), _fieldsWithUnparsedContent);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                Protocol_PS_A_GET_TICKET_COUNTS
//=================================================================

PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS::Protocol_PS_A_GET_TICKET_COUNTS()
{
	clear();
}

#ifdef MOVE_CONSTRUCTOR_SUPPORTED

PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS::Protocol_PS_A_GET_TICKET_COUNTS(Protocol_PS_A_GET_TICKET_COUNTS&& _o)
	: tickets(std::move(_o.tickets))
{
}

PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS& PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS::operator=(Protocol_PS_A_GET_TICKET_COUNTS&& _o)
{
	if(this != &_o)
	{
		tickets = std::move(_o.tickets);
	}
	return *this;
}

#endif

void PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS::clear()
{
	tickets.clear();
}

bool PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS::equals(const Protocol_PS_A_GET_TICKET_COUNTS& _o) const
{
	return tickets.equals(_o.tickets);
}

const char *PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS::asTraceString(PString& _buf) const
{
	_buf.cut(0);
	_buf.append("msgid=").append(getMsgIdString()).append("(").appendUint(PS_A_GET_TICKET_COUNTS).append(")");
	_buf.append(',');
	_buf.append("tickets=");
	tickets.toTraceString(_buf);
	return _buf.c_str();
}

void PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS::composeMsg(CommMsgBody& _msg) const
{
	tickets.composeMsg(_msg);
}

void PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS::parseMsg(CommMsgParser& _parser)
{
	tickets.parseMsg(_parser);
}

/*static*/ void PersonalizationATF::cli::Protocol_PS_A_GET_TICKET_COUNTS::validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent)
{
	const char *_descr = "PS_A_GET_TICKET_COUNTS";
	if(_checker)
	{
		if(!_checker->isValidationEnabled(_descr)) return;
		if(!_checker->hasLimitDefined(_descr)) _checker = nullptr;
	}

	PString _descbuf;
	int szTickets = ThinAtf::LAtfVector< TournTicketInfo, 4 >::validateMsg(_parser, _checker, _descbuf.assign(_descr).append('.').append("tickets"), _fieldsWithUnparsedContent);
	AtfValidator::validateInt(_descr, "tickets", szTickets, _checker, __FILE__, __LINE__);
	if(!_parser.parseEnded()) AtfValidator::logUnparsedInfo(_fieldsWithUnparsedContent, _descr, _parser);
}

//=================================================================
//                ProtocolFactory
//=================================================================

/* static */ bool PersonalizationATF::ProtocolFactory::validateProtocolMessage(const char *_nameSpace, UINT32 _msgId, CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsNotParseEnded)
{
	if(!strcmp(_nameSpace, "cli"))
	{
		switch(_msgId)
		{
			case PS_A_ADMIN_GET_RECENT_GAME_LIST: cli::Protocol_PS_A_ADMIN_GET_RECENT_GAME_LIST::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_A_ADMIN_UPDATE_LOBBIES: cli::Protocol_PS_A_ADMIN_UPDATE_LOBBIES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_A_FILTER_GAMES: cli::Protocol_PS_A_FILTER_GAMES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_A_GET_BRANDED_LOBBIES: cli::Protocol_PS_A_GET_BRANDED_LOBBIES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_A_GET_RECENT_GAME_LIST: cli::Protocol_PS_A_GET_RECENT_GAME_LIST::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_A_GET_SUGGESTED_GAMES: cli::Protocol_PS_A_GET_SUGGESTED_GAMES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_A_GET_TICKET_COUNTS: cli::Protocol_PS_A_GET_TICKET_COUNTS::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_A_GET_TICKET_TOURNS: cli::Protocol_PS_A_GET_TICKET_TOURNS::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_A_INIT_BRANDED_LOBBIES: cli::Protocol_PS_A_INIT_BRANDED_LOBBIES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_A_SEARCH_BY_NAME: cli::Protocol_PS_A_SEARCH_BY_NAME::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_ADMIN_GET_RECENT_GAME_LIST: cli::Protocol_PS_Q_ADMIN_GET_RECENT_GAME_LIST::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_ADMIN_UPDATE_LOBBIES: cli::Protocol_PS_Q_ADMIN_UPDATE_LOBBIES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_FILTER_GAMES: cli::Protocol_PS_Q_FILTER_GAMES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_GET_BRANDED_LOBBIES: cli::Protocol_PS_Q_GET_BRANDED_LOBBIES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_GET_RECENT_GAME_LIST: cli::Protocol_PS_Q_GET_RECENT_GAME_LIST::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_GET_SUGGESTED_GAMES: cli::Protocol_PS_Q_GET_SUGGESTED_GAMES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_GET_TICKET_COUNTS: cli::Protocol_PS_Q_GET_TICKET_COUNTS::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_GET_TICKET_TOURNS: cli::Protocol_PS_Q_GET_TICKET_TOURNS::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_INIT_BRANDED_LOBBIES: cli::Protocol_PS_Q_INIT_BRANDED_LOBBIES::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_Q_SEARCH_BY_NAME: cli::Protocol_PS_Q_SEARCH_BY_NAME::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
			case PS_U_GET_CURRENTLY_SEATED_AT: cli::Protocol_PS_U_GET_CURRENTLY_SEATED_AT::validateMsg(_parser, _checker, _fieldsNotParseEnded); return true;
		}
	}
	
	return false;
}

