/**
 * ..\CRMServer\upserverdbmprot_thin.h
 *
 * This file was auto-generated from ..\CRMServer\upserverdbmprot.txt by ATF protocol generator. 
 * Do not edit this file directly!
 *
 * Generator used the following keys: -genMoveConstructor -thin ..\CRMServer\upserverdbmprot.txt
 */

#ifndef ATF_PROTOCOL_DEFFILE____CRMSERVER_UPSERVERDBMPROT_THIN_H
#define ATF_PROTOCOL_DEFFILE____CRMSERVER_UPSERVERDBMPROT_THIN_H


#include "../upserver/upservercommonprot_thin.h"			// @only_thin_version
#include "crmserver.h"


#include "ThinAtfUserDefStructs.h"

namespace UPServerDBM
{
	class ProtocolFactory
	{
	public:
		static bool validateProtocolMessage(const char *_nameSpace, UINT32 _msgId, CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsNotParseEnded);
	};


	struct DBData
	{
		//! M( <FIXME>UPServerCommon::Property</FIXME> 4<4>) - M( <FIXME>property</FIXME> ,numUserIntIds<userIntIds>)
		UPServerCommon::Property property;
		ThinAtf::LAtfVector< UINT32, 4 > userIntIds;

		DBData();
		void clear();
		bool equals(const DBData&) const;
		const char *toTraceString(PString& _str) const;
		void composeMsg(CommMsgBody& _msg) const;
		void parseMsg(CommMsgParser& _parser);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
		DBData(DBData&&);
		DBData& operator=(DBData&&);
	private:
		DBData(const DBData&);  // prohibit
		DBData& operator=(const DBData&);  // prohibit
#endif
	};

	struct IsUpdateAndPrevValidUntil
	{
		//! M(b <FIXME>CommUtcTime</FIXME> ) - M(isUpdate, <FIXME>validUntilPrev</FIXME> )
		bool isUpdate;
		CommUtcTime validUntilPrev;

		IsUpdateAndPrevValidUntil();
		void clear();
		bool equals(const IsUpdateAndPrevValidUntil&) const;
		const char *toTraceString(PString& _str) const;
		void composeMsg(CommMsgBody& _msg) const;
		void parseMsg(CommMsgParser& _parser);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
		IsUpdateAndPrevValidUntil(IsUpdateAndPrevValidUntil&&);
		IsUpdateAndPrevValidUntil& operator=(IsUpdateAndPrevValidUntil&&);
	private:
		IsUpdateAndPrevValidUntil(const IsUpdateAndPrevValidUntil&);  // prohibit
		IsUpdateAndPrevValidUntil& operator=(const IsUpdateAndPrevValidUntil&);  // prohibit
#endif
	};

	struct DBDataIsUpdate
	{
		//! M( <FIXME>UPServerCommon::Property</FIXME> 4<4>4<M(b <FIXME>CommUtcTime</FIXME> )>t) - M( <FIXME>property</FIXME> ,numUserIntIds<userIntIds>,numIsUpdateForUserAndValidUntil<M(isUpdate, <FIXME>validUntilPrev</FIXME> )>,when)
		UPServerCommon::Property property;
		ThinAtf::LAtfVector< UINT32, 4 > userIntIds;
		ThinAtf::LAtfVector< IsUpdateAndPrevValidUntil, 4 > isUpdateForUserAndValidUntil;
		CommSrvTime when;

		DBDataIsUpdate();
		void clear();
		bool equals(const DBDataIsUpdate&) const;
		const char *toTraceString(PString& _str) const;
		void composeMsg(CommMsgBody& _msg) const;
		void parseMsg(CommMsgParser& _parser);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
		DBDataIsUpdate(DBDataIsUpdate&&);
		DBDataIsUpdate& operator=(DBDataIsUpdate&&);
	private:
		DBDataIsUpdate(const DBDataIsUpdate&);  // prohibit
		DBDataIsUpdate& operator=(const DBDataIsUpdate&);  // prohibit
#endif
	};

	//------------------------------------------------------------------------------
	// DBM save message
	//------------------------------------------------------------------------------

	// #define CRMDBM_Q_UPS_SAVE_PROPERTY				857 // UPServer -> DBM
	// #define CRMDBM_A_UPS_SAVE_PROPERTY				1857 // DBM -> UPServer

	struct Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY
	{
		//! M( <FIXME>UPServerCommon::Property</FIXME> 4<4>4<M(b <FIXME>CommUtcTime</FIXME> )>t) - M( <FIXME>property</FIXME> ,numUserIntIds<userIntIds>,numIsUpdateForUserAndValidUntil<M(isUpdate, <FIXME>validUntilPrev</FIXME> )>,when)
		DBDataIsUpdate dataRow;

		Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY();
		void clear();
		bool equals(const Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY&) const;
		const char *asTraceString(PString& _buf) const;
		void parseMsg(CommMsgParser& _parser);
		void composeMsg(CommMsgBody& _body) const;

		static UINT32 getMsgId() { return CRMDBM_Q_UPS_SAVE_PROPERTY; }
		static const char *getMsgIdString() { return "CRMDBM_Q_UPS_SAVE_PROPERTY"; }
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
		Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY(Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY&&);
		Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY& operator=(Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY&&);
	private:
		Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY(const Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY&);  // prohibit
		Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY& operator=(const Protocol_CRMDBM_Q_UPS_SAVE_PROPERTY&);  // prohibit
#endif
	};

	struct Protocol_CRMDBM_A_UPS_SAVE_PROPERTY
	{
		// 2[s] - errCode[errStr]
		INT16 errCode;

		PString errStr;

		Protocol_CRMDBM_A_UPS_SAVE_PROPERTY();
		void clear();
		bool equals(const Protocol_CRMDBM_A_UPS_SAVE_PROPERTY&) const;
		const char *asTraceString(PString& _buf) const;
		void parseMsg(CommMsgParser& _parser);
		void composeMsg(CommMsgBody& _body) const;

		static UINT32 getMsgId() { return CRMDBM_A_UPS_SAVE_PROPERTY; }
		static const char *getMsgIdString() { return "CRMDBM_A_UPS_SAVE_PROPERTY"; }
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
		Protocol_CRMDBM_A_UPS_SAVE_PROPERTY(Protocol_CRMDBM_A_UPS_SAVE_PROPERTY&&);
		Protocol_CRMDBM_A_UPS_SAVE_PROPERTY& operator=(Protocol_CRMDBM_A_UPS_SAVE_PROPERTY&&);
	private:
		Protocol_CRMDBM_A_UPS_SAVE_PROPERTY(const Protocol_CRMDBM_A_UPS_SAVE_PROPERTY&);  // prohibit
		Protocol_CRMDBM_A_UPS_SAVE_PROPERTY& operator=(const Protocol_CRMDBM_A_UPS_SAVE_PROPERTY&);  // prohibit
#endif
	};

	//------------------------------------------------------------------------------
	// DBM load all user properties
	//------------------------------------------------------------------------------

	// #define CRMDBM_Q_UPS_GET_DATA			858 // UPServer -> DBM
	// #define CRMDBM_A_UPS_GET_DATA			1858 // DBM -> UPServer

	struct Protocol_CRMDBM_Q_UPS_GET_DATA
	{

		Protocol_CRMDBM_Q_UPS_GET_DATA();
		void clear();
		bool equals(const Protocol_CRMDBM_Q_UPS_GET_DATA&) const;
		const char *asTraceString(PString& _buf) const;
		void parseMsg(CommMsgParser& _parser);
		void composeMsg(CommMsgBody& _body) const;

		static UINT32 getMsgId() { return CRMDBM_Q_UPS_GET_DATA; }
		static const char *getMsgIdString() { return "CRMDBM_Q_UPS_GET_DATA"; }
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
		Protocol_CRMDBM_Q_UPS_GET_DATA(Protocol_CRMDBM_Q_UPS_GET_DATA&&);
		Protocol_CRMDBM_Q_UPS_GET_DATA& operator=(Protocol_CRMDBM_Q_UPS_GET_DATA&&);
	private:
		Protocol_CRMDBM_Q_UPS_GET_DATA(const Protocol_CRMDBM_Q_UPS_GET_DATA&);  // prohibit
		Protocol_CRMDBM_Q_UPS_GET_DATA& operator=(const Protocol_CRMDBM_Q_UPS_GET_DATA&);  // prohibit
#endif
	};

	struct Protocol_CRMDBM_A_UPS_GET_DATA
	{
		//! 2[s|4<M( <FIXME>UPServerCommon::Property</FIXME> 4<4>)>] - errCode[errStr|numUserPropertiesWithExpiry<M( <FIXME>property</FIXME> ,numUserIntIds<userIntIds>)>]
		INT16 errCode;

		PString errStr;

		ThinAtf::LAtfVector< DBData , 4 > userPropertiesWithExpiry;	// all properties found in db

		Protocol_CRMDBM_A_UPS_GET_DATA();
		void clear();
		bool equals(const Protocol_CRMDBM_A_UPS_GET_DATA&) const;
		const char *asTraceString(PString& _buf) const;
		void parseMsg(CommMsgParser& _parser);
		void composeMsg(CommMsgBody& _body) const;

		static UINT32 getMsgId() { return CRMDBM_A_UPS_GET_DATA; }
		static const char *getMsgIdString() { return "CRMDBM_A_UPS_GET_DATA"; }
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, PString& _fieldsWithUnparsedContent);

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
		Protocol_CRMDBM_A_UPS_GET_DATA(Protocol_CRMDBM_A_UPS_GET_DATA&&);
		Protocol_CRMDBM_A_UPS_GET_DATA& operator=(Protocol_CRMDBM_A_UPS_GET_DATA&&);
	private:
		Protocol_CRMDBM_A_UPS_GET_DATA(const Protocol_CRMDBM_A_UPS_GET_DATA&);  // prohibit
		Protocol_CRMDBM_A_UPS_GET_DATA& operator=(const Protocol_CRMDBM_A_UPS_GET_DATA&);  // prohibit
#endif
	};
};

#endif
