ERR(eSCError_InternalError,          1, "Internal Error.")
ERR(eSCError_UserNotFound,           2, "No such user or authentication token failed.")
ERR(eSCError_UserClosed,             3, "The user's account is closed.")
ERR(eSCError_UserSelfExcluded,       4, "User self excluded.")
ERR(eSCError_UserNoPlayPrivilege,    5, "User has no play privilege.")
ERR(eSCError_UserIsAdmin,            6, "Users with admin privileges are not allowed.")
ERR(eSCError_InsufficientFunds,      7, "Insufficient funds.")
ERR(eSCError_InvalidAmount,          8, "Invalid Amounts")
ERR(eSCError_InvalidExternalTransId, 9, "Invalid External TransId.")
ERR(eSCError_InconsistentData,      10, "Inconsistent Data.")
ERR(eSCError_Blocked,               11, "User is blocked.")
ERR(eSCError_InvalidRefTransId,     12, "Invalid ref TransId.")
