#ifndef DFS_Server_WAPI_Msgs_H
#define DFS_Server_WAPI_Msgs_H

// FantasySports connection types
#define DFSUS_SERVER_CONN_TYPE_TOKEN_WALLET   "TWAPI"
// PYR-40346  StartsDraft connection types
#define DFSINTL_SERVER_CONN_TYPE_SD_AuthWAPI    "SD_AuthWAPI"
#define DFSINTL_SERVER_CONN_TYPE_SD_PlainWAPI   "SD_PlainWAPI"

enum DFS_WAPI_MsgIDs
{
// DFS_SERVER_CONN_TYPE_TOKEN_WALLET
    TWAPI_Q_GET_USER_INFO           = 721
,   TWAPI_A_GET_USER_INFO           = 722
,   TWAPI_Q_GET_USER_PAYMENTS_INFO  = 723
,   TWAPI_A_GET_USER_PAYMENTS_INFO  = 724
,   TWAPI_Q_GET_USER_BET_INFO       = 725
,   TWAPI_A_GET_USER_BET_INFO       = 726
// PYR-40346 DFS_SERVER_CONN_TYPE_SD_AuthWAPI
,   SDWA_Q_SECURE_FUNDS             = 727
,   SDWA_A_SECURE_FUNDS             = 728
,   SDWA_Q_USER_INFO                = 729
,   SDWA_A_USER_INFO                = 730
// PYR-40346 DFS_SERVER_CONN_TYPE_SD_PlainWAPI
,   SDWA_Q_CONTEST_PAYOUT           = 731
,   SDWA_A_CONTEST_PAYOUT           = 732
,   SDWA_Q_VOID_ENTRY               = 733
,   SDWA_A_VOID_ENTRY               = 734
,   SDWA_Q_REVERSE_PAYOUT           = 735
,   SDWA_A_REVERSE_PAYOUT           = 736
//,   SDWA_Q_KEEP_ALIVE               = 737
//,   SDWA_A_KEEP_ALIVE               = 738
,   SDWA_Q_REFUND_PARTIAL           = 739
,   SDWA_A_REFUND_PARTIAL           = 740
,   SDWA_Q_GET_TRANSACTION_STATUS   = 741
,   SDWA_A_GET_TRANSACTION_STATUS   = 742
,   SDWA_Q_CHECK_SECURE_FUNDS_DUP   = 743
,   SDWA_A_CHECK_SECURE_FUNDS_DUP   = 744
};

#endif
