// Copyright (C) Amaya Software Ltd. All rights reserved.

#include "CGapp.h"

//******************************************************************************
// This is the application definitions
//******************************************************************************

// Constant values definition
const char* help = 
{
	"\nCopyright (C) Amaya Software Ltd. All rights reserved.\n\n"
	"-d:directory\tSet new working directory\n"
	"-h\t\tHelp output\n"
	"-i:inifile\tSpecify INI file, may be used for multiple INI files\n"
	"-p\t\tDo not stop and show \"Press any key to continue...\" message\n"
	"\nYou can find full information in the user's manual!\n\n"
};

const gsSubFieldTypes gsSubFieldTypesData[] =
{
	{"vector",					1,	true,	"",			"vector"},
	{"set",						1,	false,	"",			"set"},
	{"map",						2,	false,	"",			"map"},
	{"list",					1,	false,	"",			"list"},
};
const size_t gsSubFieldTypesSize = sizeof(gsSubFieldTypesData)/sizeof(gsSubFieldTypes);

// Reserved words C++
const char* ForbiddenDefinitions[] = 
{
	"auto", 
	"asm", 
	"and", 
	"and_eq", 
	"__abstract", 
	"__alignof", 
	"abstract", 
	"array", 
	"__asm", 
	"__assume", 
	"__based", 
	"bitand", 
	"bitor", 
	"__box", 
	"break", 
	"case", 
	"catch", 
	"__cdecl", 
	"char", 
	"class", 
	"const", 
	"const_cast", 
	"continue", 
	"cin", 
	"cout", 
	"compl", 
	"__declspec", 
	"default", 
	"__delegate", 
	"delegate", 
	"delete", 
	"deprecated", 
	"dllexport", 
	"dllimport", 
	"do", 
	"double", 
	"dynamic_cast", 
	"else", 
	"enum", 
	"explicit", 
	"event", 
	"__event", 
	"__except", 
	"extern", 
	"endl", 
	"false", 
	"__fastcall", 
	"__finally", 
	"finally", 
	"float", 
	"for", 
	"for each", 
	"__forceinline", 
	"friend", 
	"friend_as", 
	"__gc", 
	"gcnew", 
	"generic", 
	"goto", 
	"__hook", 
	"__identifier", 
	"if", 
	"__if_exists", 
	"in", 
	"__if_not_exists", 
	"initonly", 
	"__inline", 
	"inline", 
	"include", 
	"INT_MIN", 
	"INT_MAX", 
	"iomanip", 
	"iostream", 
	"int", 
	"__int8", 
	"__int16", 
	"__int32", 
	"_int64", 
	"__interface", 
	"interface", 
	"interior_ptr", 
	"__leave", 
	"literal", 
	"long", 
	"__m64", 
	"__m128", 
	"__m128d", 
	"__m128i", 
	"__multiple_inheritance", 
	"mutable", 
	"main", 
	"MAX_RAND", 
	"naked", 
	"namespace", 
	"new", 
	"__nogc", 
	"noinline", 
	"__noop", 
	"noreturn", 
	"nothrow", 
	"novtable", 
	"nullptr", 
	"NULL", 
	"not_eq", 
	"not", 
	"npos", 
	"operator", 
	"or_eq", 
	"or", 
	"__pin", 
	"private", 
	"__property", 
	"property", 
	"protected", 
	"public", 
	"__raise", 
	"register", 
	"reinterpret_cast", 
	"return", 
	"safecast", 
	"__sealed", 
	"sealed", 
	"selectany", 
	"short", 
	"signed", 
	"__single_inheritance", 
	"sizeof", 
	"static", 
	"static_cast", 
	"__stdcall", 
	"struct", 
	"__super", 
	"switch", 
	"string", 
	"std", 
	"template", 
	"this", 
	"thread", 
	"throw", 
	"true", 
	"try", 
	"__try", 
	"__try_cast", 
	"typedef", 
	"typeid", 
	"typename", 
	"__unaligned", 
	"__unhook", 
	"union", 
	"unsigned", 
	"using", 
	"uuid", 
	"__uuidof", 
	"value", 
	"__value", 
	"virtual", 
	"__virtual_inheritance", 
	"void", 
	"volatile", 
	"__w64", 
	"__wchar_t", 
	"wchar_t", 
	"while", 
	"xor_eq", 
	"xor" 
};
const size_t ForbiddenDefinitionsSize = sizeof(ForbiddenDefinitions)/sizeof(char*);
