/**
 * NStackTournInfo_thin.h
 *
 * This file was auto-generated from NStackTournInfo.txt by ATF protocol generator. 
 * Do not edit this file directly!
 *
 * Generator used the following keys: -genMoveConstructor -thin NStackTournInfo.txt
 */

#ifndef ATF_PROTOCOL_DEFFILE_NSTACKTOURNINFO_THIN_H
#define ATF_PROTOCOL_DEFFILE_NSTACKTOURNINFO_THIN_H


#include "ThinAtfUserDefStructs.h"

namespace TournClientThin
{
	//PYR-25226
	struct NStackTournInfoStruct
	{
		// 4444b - initialStacks,unitStackChips,forceReloadAllStacksInLevel,forceReloadAllStacksInMinutes,reloadStacksOnlyWhenEmpty
		INT32 initialStacks;
		INT32 unitStackChips;
		UINT32 forceReloadAllStacksInLevel;
		UINT32 forceReloadAllStacksInMinutes;
		bool reloadStacksOnlyWhenEmpty;

		NStackTournInfoStruct();
		void clear();
		bool equals(const NStackTournInfoStruct&) const;
		const char *toTraceString(PString& _str) const;
		void composeMsg(CommMsgBody& _msg) const;
		void parseMsg(CommMsgParser& _parser);
		static void validateMsg(CommMsgParser& _parser, const AtfMsgChecker* _checker, const char* _descr, PString& _fieldsWithUnparsedContent);
	};
};

#endif
