/**
 * protocols\StarsStore\PsStarsStoreAPI_thin.h
 *
 * This file was auto-generated from protocols\StarsStore\PsStarsStoreAPI.txt by ATF protocol generator. 
 * Do not edit this file directly!
 *
 * Generator used the following keys: -thin -genMoveConstructor -dontGenValidationFuncs protocols\StarsStore\PsStarsStoreAPI.txt
 */

#ifndef ATF_PROTOCOL_DEFFILE_PROTOCOLS_STARSSTORE_PSSTARSSTOREAPI_THIN_H
#define ATF_PROTOCOL_DEFFILE_PROTOCOLS_STARSSTORE_PSSTARSSTOREAPI_THIN_H

// PYR-81644
#include "PsStarsStoreAPI_Msgs.h"


#include "ThinAtfUserDefStructs.h"

namespace PsStarsStore
{
	struct Warning
	{
		// M(2s) - M(code,description)
		INT16 code;
		PString description;

		Warning();
		void clear();
		bool equals(const Warning&) const;
		const char *toTraceString(PString& _str) const;
		void composeMsg(CommMsgBody& _msg) const;
		void parseMsg(CommMsgParser& _parser);

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
		Warning(Warning&&);
		Warning& operator=(Warning&&);
#ifdef ATF_GENERATE_DEFAULT_COPYCONSTRUCTOR
		Warning(const Warning&) = default;
		Warning& operator=(const Warning&) = default;
#endif
#endif
	};

	struct OrderItem
	{
		// M(824s) - M(orderItemID,itemQuantity,itemPrice,itemDescription)
		UINT64 orderItemID;
		UINT16 itemQuantity;
		INT32 itemPrice;
		PString itemDescription;

		OrderItem();
		void clear();
		bool equals(const OrderItem&) const;
		const char *toTraceString(PString& _str) const;
		void composeMsg(CommMsgBody& _msg) const;
		void parseMsg(CommMsgParser& _parser);

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
		OrderItem(OrderItem&&);
		OrderItem& operator=(OrderItem&&);
#ifdef ATF_GENERATE_DEFAULT_COPYCONSTRUCTOR
		OrderItem(const OrderItem&) = default;
		OrderItem& operator=(const OrderItem&) = default;
#endif
#endif
	};

	namespace AuthAPI	// from middle-tier to server object, authenticated (WebTokenGuard)
	{

		struct Protocol_MSG_SST_Q_GetUserInfo
		{
			// intentionally left blank

			Protocol_MSG_SST_Q_GetUserInfo();
			void clear();
			bool equals(const Protocol_MSG_SST_Q_GetUserInfo&) const;
			const char *asTraceString(PString& _buf) const;
			void parseMsg(CommMsgParser& _parser);
			void composeMsg(CommMsgBody& _body) const;

			static UINT32 getMsgId() { return MSG_SST_Q_GetUserInfo; }
			static const char *getMsgIdString() { return "MSG_SST_Q_GetUserInfo"; }
		};

		struct Protocol_MSG_SST_A_GetUserInfo
		{
			// ss8sss4<M(2s)> - userId,country,starsCoinsBalance,siteID,language,playerCurrency,numWarnings<M(code,description)>
			PString userId;
			PString country;
			INT64 starsCoinsBalance;
			PString siteID;
			PString language;
			PString playerCurrency;
			ThinAtf::LAtfVector< Warning, 4 > warnings;

			// PString            more parseEndOptB4Me;
			Protocol_MSG_SST_A_GetUserInfo();
			void clear();
			bool equals(const Protocol_MSG_SST_A_GetUserInfo&) const;
			const char *asTraceString(PString& _buf) const;
			void parseMsg(CommMsgParser& _parser);
			void composeMsg(CommMsgBody& _body) const;

			static UINT32 getMsgId() { return MSG_SST_A_GetUserInfo; }
			static const char *getMsgIdString() { return "MSG_SST_A_GetUserInfo"; }

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
			Protocol_MSG_SST_A_GetUserInfo(Protocol_MSG_SST_A_GetUserInfo&&);
			Protocol_MSG_SST_A_GetUserInfo& operator=(Protocol_MSG_SST_A_GetUserInfo&&);
#ifdef ATF_GENERATE_DEFAULT_COPYCONSTRUCTOR
			Protocol_MSG_SST_A_GetUserInfo(const Protocol_MSG_SST_A_GetUserInfo&) = default;
			Protocol_MSG_SST_A_GetUserInfo& operator=(const Protocol_MSG_SST_A_GetUserInfo&) = default;
#endif
#endif
		};

		struct Protocol_MSG_SST_Q_DebitStarsCoin
		{
			// 88884s44<M(824s)> - externalTransactionID,vendorID,cartID,starsCoins,totalPrice,currency,totalOrderItems,numOrderItems<M(orderItemID,itemQuantity,itemPrice,itemDescription)>
			UINT64 externalTransactionID;
			UINT64 vendorID;
			UINT64 cartID;
			INT64 starsCoins;	// this amount will be debited and also known as FPP.
			INT32 totalPrice;	// for reference only, this amount will not be debited.
			PString currency;	// currency associated to the totalPrice not the starsCoins.
			UINT32 totalOrderItems;	// how many orderItems in this messages,( = size of orderItems.)
			ThinAtf::LAtfVector< OrderItem, 4 > orderItems;

			Protocol_MSG_SST_Q_DebitStarsCoin();
			void clear();
			bool equals(const Protocol_MSG_SST_Q_DebitStarsCoin&) const;
			const char *asTraceString(PString& _buf) const;
			void parseMsg(CommMsgParser& _parser);
			void composeMsg(CommMsgBody& _body) const;

			static UINT32 getMsgId() { return MSG_SST_Q_DebitStarsCoin; }
			static const char *getMsgIdString() { return "MSG_SST_Q_DebitStarsCoin"; }

#ifdef MOVE_CONSTRUCTOR_SUPPORTED
			Protocol_MSG_SST_Q_DebitStarsCoin(Protocol_MSG_SST_Q_DebitStarsCoin&&);
			Protocol_MSG_SST_Q_DebitStarsCoin& operator=(Protocol_MSG_SST_Q_DebitStarsCoin&&);
#ifdef ATF_GENERATE_DEFAULT_COPYCONSTRUCTOR
			Protocol_MSG_SST_Q_DebitStarsCoin(const Protocol_MSG_SST_Q_DebitStarsCoin&) = default;
			Protocol_MSG_SST_Q_DebitStarsCoin& operator=(const Protocol_MSG_SST_Q_DebitStarsCoin&) = default;
#endif
#endif
		};

		struct Protocol_MSG_SST_A_DebitStarsCoin
		{
			// 8 - starsCoinsBalance
			INT64 starsCoinsBalance;

			Protocol_MSG_SST_A_DebitStarsCoin();
			void clear();
			bool equals(const Protocol_MSG_SST_A_DebitStarsCoin&) const;
			const char *asTraceString(PString& _buf) const;
			void parseMsg(CommMsgParser& _parser);
			void composeMsg(CommMsgBody& _body) const;

			static UINT32 getMsgId() { return MSG_SST_A_DebitStarsCoin; }
			static const char *getMsgIdString() { return "MSG_SST_A_DebitStarsCoin"; }
		};
	};
};

#endif
